### ISSUE TITLE
Track AX/Localization Information

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1006]
Extension to #1001 

Voiceover Enabled
Preferred Dynamic Font Size (Large is default; should we support dynamic fonts?)
Device Language
Any Others

**Comment by rnystrom** [comment]
Oh man, I almost think we should prioritize dynamic fonts over better VoiceOver. I'll make that part of 1.15.

**Comment by rnystrom** [comment]
We have this now
