### ISSUE TITLE
FBSnapshot Tests Broken

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1083]
Looks like the FBSnapshot tests were never functional on CI, but as CI was broken for other reasons we didn't realise! 😞 

As part of the work done in #1075 to fix all of the CI issues the tests have been commented out, we should add them back and get them fully functional to start reaping the rewards!

@Austinate - Are you able to help out at all with this?

**Comment by Austinate** [comment]
Hm, that's strange, sorry for that.
Will take a look

**Comment by Austinate** [comment]
After investigation i can say that part of issue was that i forgot to make `Freetime` scheme a shared one (so i only had 'environment variables' locally).
This is easily fixable.

Another part i realized right now is that for full-VC snapshots we will need snapshot-per-device or we should probably decide which device we will use for snapshot testing. (Also there is a same requirement for 2x/3x snapshots, we would need to make both or lockdown on 1 device probably).

**Comment by rnystrom** [comment]
Closing since I'm not sure this is worth the time
