### ISSUE TITLE
Master Sheet

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1085]
Wanted to create a quick issue which has basically every bit of markdown for testing purposes! Here's an emoji 💩 💩 (or two)

We have **bold** _italics_ and ~~strikethrough with a mis-aligned emoji 😞~~
Here's a **bold sentence with an _italics_ word in ~~the~~ middle**

# Tables (Title One)

Key | Value
--- | ---
1 | One
2 | Two
3 | Three

## Links (Title 2)

Normal:
[title](https://www.google.co.uk) [relative](..)
https://www.google.co.uk

Infer:
#1 
rnystrom/GitHawk#1
bb8a8ac45fc9fe5a5da175c4dbcc1ef4a8339a4b
rnystrom@bb8a8ac45fc9fe5a5da175c4dbcc1ef4a8339a4b
mojombo/github-flavored-markdown@16c999e8c71134401a78d4d46435517b2271d6ac

Shorten:
https://github.com/rnystrom/GitHawk/issues/1
https://github.com/rnystrom/GitHawk/
https://github.com/rnystrom/GitHawk/commit/bb8a8ac45fc9fe5a5da175c4dbcc1ef4a8339a4b

Tag Users:
@rnystrom @Ireallyhopenooneactuallyhasthisusername

### Code (Title 3)

Here's a bit of `inline` code because I really do like to drop a random `class` into sentences.

```swift
class AlertActionBuilder {

    typealias BuilderClosure = (AlertActionBuilder) -> Void

    init(_ buildClosure: BuilderClosure) {
        buildClosure(self)
    }
}
```

```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

```
Some unknown language
```

#### Lists (Title 4)

- Item
- Item (0 spaces prefix)
  - Here's a level two item (2 spaces prefix)
      - Here's a level three (6 spaces prefix)
 - This should be at root (1 space prefix)
  - (2 spaces prefix)
   - (3 spaces prefix)
    - (4 spaces prefix)
      - (6 spaces prefix)
        - (8 spaces)
       - (7)

Note about what we're seeing above ^^ - You must have two spaces more than the previous list item in order for it to indent otherwise it'll stay on the same line. Just one space less than the previous is enough to drop it down though.

1. One
2. Two
3. Three
5. Five but the number shouldn't skip, so four
- Start of check list, ensure it doesn't break
- [ ] Unchecked
- [x] Checked
- Within a checklist
1. Another numbered list
2. [x] Checklist in a numbered list
3. Test
* Using Asteriks
- Using Dash

Horizontal Line: (Needs 3 or more dashes)

---

##### Images (Title 5)

![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

Title inferred by a horizontal line underneath a sentence (only needs one dash)
-

Other things to do:
- HTML
- Quotes
- Do an audit of the app to see how it handles all of this
- Link mishandled things to other issues to fix them!

**Comment by Sherlouk** [comment]
Direct quote of the root comment to test all of the same things but within one level of quotation!

> Wanted to create a quick issue which has basically every bit of markdown for testing purposes! Here's an emoji 💩 💩 (or two)
> 
> We have **bold** _italics_ and ~~strikethrough with a mis-aligned emoji 😞~~
> Here's a **bold sentence with an _italics_ word in ~~the~~ middle**
> 
> # Tables (Title One)
> 
> Key | Value
> --- | ---
> 1 | One
> 2 | Two
> 3 | Three
> 
> ## Links (Title 2)
> 
> Normal:
> [title](https://www.google.co.uk) [relative](..)
> https://www.google.co.uk
> 
> Infer:
> #1 
> rnystrom/GitHawk#1
> bb8a8ac45fc9fe5a5da175c4dbcc1ef4a8339a4b
> rnystrom@bb8a8ac45fc9fe5a5da175c4dbcc1ef4a8339a4b
> mojombo/github-flavored-markdown@16c999e8c71134401a78d4d46435517b2271d6ac
> 
> Shorten:
> https://github.com/rnystrom/GitHawk/issues/1
> https://github.com/rnystrom/GitHawk/
> https://github.com/rnystrom/GitHawk/commit/bb8a8ac45fc9fe5a5da175c4dbcc1ef4a8339a4b
> 
> Tag Users:
> @rnystrom @Ireallyhopenooneactuallyhasthisusername
> 
> ### Code (Title 3)
> 
> Here's a bit of `inline` code because I really do like to drop a random `class` into sentences.
> 
> ```swift
> class AlertActionBuilder {
> 
>     typealias BuilderClosure = (AlertActionBuilder) -> Void
> 
>     init(_ buildClosure: BuilderClosure) {
>         buildClosure(self)
>     }
> }
> ```
> 
> ```javascript
> function fancyAlert(arg) {
>   if(arg) {
>     $.facebox({div:'#foo'})
>   }
> }
> ```
> 
> ```
> Some unknown language
> ```
> 
> #### Lists (Title 4)
> 
> - Item
> - Item (0 spaces prefix)
>   - Here's a level two item (2 spaces prefix)
>       - Here's a level three (6 spaces prefix)
>  - This should be at root (1 space prefix)
>   - (2 spaces prefix)
>    - (3 spaces prefix)
>     - (4 spaces prefix)
>       - (6 spaces prefix)
>         - (8 spaces)
>        - (7)
> 
> Note about what we're seeing above ^^ - You must have two spaces more than the previous list item in order for it to indent otherwise it'll stay on the same line. Just one space less than the previous is enough to drop it down though.
> 
> 1. One
> 2. Two
> 3. Three
> 5. Five but the number shouldn't skip, so four
> - Start of check list, ensure it doesn't break
> - [ ] Unchecked
> - [x] Checked
> - Within a checklist
> 1. Another numbered list
> 2. [x] Checklist in a numbered list
> 3. Test
> * Using Asteriks
> - Using Dash
> 
> Horizontal Line: (Needs 3 or more dashes)
> 
> ---
> 
> ##### Images (Title 5)
> 
> ![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
> 
> 
> Title inferred by a horizontal line underneath a sentence (only needs one dash)
> -
> 
> Other things to do:
> - HTML
> - Quotes
> - Do an audit of the app to see how it handles all of this
> - Link mishandled things to other issues to fix them!

And a sentence afterwards for past times sake

**Comment by BasThomas** [comment]
Seems like tapping a table doesn’t trigger the expand comment (saw this in the quoted comment here)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
@BasThomas Yea noticed that too, it is possible but pretty difficult to do! Will be making notes of all the things soon
