### ISSUE TITLE
Comment field is not respecting safe area

### ISSUE THREAD

**Issue by joerocca** [GitHawkApp/GitHawk#1153]
![GitHawk Upload by joerocca](https://i.imgur.com/I5YbtWo.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@joerocca what exactly is wrong here?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
@rnystrom I suspect the "Leave a comment" box is too close to the left/right sides, so if the notch was in the screenshot it would probably intercept?

(Can't confirm, I don't have an X 😢)

**Comment by rnystrom** [comment]
Ooooh now I see it. Ok cool.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Going to punt this, I think it's about time for `SLKTextViewController` to take a hike. I'll start hacking on a replacement in the next couple weeks.
