### ISSUE TITLE
Unable to swipe through multiple images in-app

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#123]
Eg. #120

**Comment by rnystrom** [comment]
What's the ref to #120 for? Not following how they are related?

I'm gonna add wishlist to this, I didn't intend for this to work. Probably not super complicated tho since we're using the NYT lib.

**Comment by BasThomas** [comment]
In #120 there are two images. :)

**Comment by rnystrom** [comment]
Oh! I get it 😆
