### ISSUE TITLE
Comments render white space

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1339]
![GitHawk Upload by BasThomas](https://i.imgur.com/A317Rou.jpg)

Happens on both iPad and iPhone. Have a feeling it’s been happening more the last few days? Also happened on previous version though.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1514903367)
Device: iPad7,3 (iOS 11.2.1)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Issue in question: https://github.com/Moya/Moya/issues/1523

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Hmm @BasThomas can you do some debugging here? I can't repro.

**Comment by SD10** [comment]
The spacing is even larger in the latest TestFlight: 1.17.0

![GitHawk Upload by SD10](https://i.imgur.com/X3nLocR.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Haven’t seen it lately - can you tap with three fingers to dig a bit with FLEX?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Sorry @BasThomas I don’t know what you mean.

It’s difficult to reproduce but once it happens, any comments have an excessive amount of spacing on any issue throughout the app. Once I kill GitHawk and reopen it’s gone.

It has happened by viewing an issue on a fresh app start, expanding a comment, posting a comment. Can’t single it down to one specific action and it’s inconsistent.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
In Testflight, you can tap with three fingers anywhere on the screen to have additional tools (see image), which enable you to debug the views, network requests and more. 

![GitHawk Upload by BasThomas](https://i.imgur.com/QiUavQX.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Sorry @BasThomas, noob moment. Thanks for getting me up to speed!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
@SD10 have you been seeing it in the last few days / been able to debug with FLEX?

**Comment by SD10** [comment]
I haven't seen any but I've had very limited GitHub activity in the past few days. We could close and re-open if I see it again

**Comment by rnystrom** [comment]
I think I saw this today caused by html comments and no actual content. Will investigate.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
https://github.com/SwifterSwift/SwifterSwift/pull/364

Not sure if the same bug, but the root comment in here has a bunch of HTML comments which render as massive blocks of white space in app

**Comment by SD10** [comment]
Steps to reproduce:
1. Open any issue / PR
2. Immediately stop view from scrolling to bottom
3. White space appears on all comments made through GitHawk and other HTML blocks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@SD10 hmmm I can’t seem to repro that. The html comments are definitely a thing though. I’m going to fix those for 1.17

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
PR fixes this big time, but still want to strip commented HTML out. For example, that Moya issue is totally empty.

**Comment by rnystrom** [comment]
Seems to be fixed
