### ISSUE TITLE
Reviewers Not Showing

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1357]
I might be mis-remembering the functionality but

SwifterSwift PR 356 - I can see the reviewers
Moya PR 1489 - I can't see the reviewers

Both of them are organisations
Both of them I'm not apart of
Both of them have reviewers

Not sure why they're being treated differently?

danielmiessler/SecLists PR 155 - I can't see the reviewers (has a tonne, which is where I saw the issue, but also on Moya which only has 1 - so the count isn't the issue)

**Comment by rnystrom** [comment]
Seems to be working as of latest master
