### ISSUE TITLE
Review Comments "Load More" stuck

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1358]
danielmiessler/SecLists PR 155

"View Comments" -> Scroll to bottom -> Load More -> Tap -> Button turns grey, but never does anything

Might be due to the shear amount of comments etc?

**Comment by rnystrom** [comment]
Seems to be working? Feel free to reopen if its still an issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Still an issue, though now it starts a infinite spinner!

**Comment by rnystrom** [comment]
@Sherlouk mind doing some digging? Doesn’t repro here.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Closing since been a while w/out repro or other reports
