### ISSUE TITLE
Upload dSYMs to Fabric

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1426]
There's a pretty bad crash at the moment but can't look into it as besides the file name we know nothing about what's happening!

**Comment by rnystrom** [comment]
Anyone know how to do this with BuddyBuild? Or whatever service we end up using.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Hmm build logs _look_ succesful

    ▸ Running Phase Script 'Run Fabric'
    ▸ [uploadDSYM] Fabric.framework/run 1.7.0 (208)
    ▸ [uploadDSYM] Using API Key: "45ebb3c197db95937d23c07145bb2da8226cd851"
    ▸ [uploadDSYM] Launched uploader in validation mode

**Comment by BasThomas** [comment]
Can we close this in favor of 1614?
