### ISSUE TITLE
UICollectionView deallocated while update was in flight

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1440]
#### in cow_cleanup

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/githawk/ios/apps/com.whoisryannystrom.freetime/issues/5a5fa2658cb3c2fa630859c7?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/githawk/ios/apps/com.whoisryannystrom.freetime/issues/5a5fa2658cb3c2fa630859c7?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by BasThomas** [comment]
Closing this for now, as it seems to have been resolved.
