### ISSUE TITLE
Support releases in notifications

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1449]
On GitHub web I have 3 notifications including 2 issues but also a tag/release but this isn't appearing inside of the app - I know we've had problems in the past but it boiled down to GitHub just not surfacing certain events in the API but this one is definitely available!

In terms of displaying it'll definitely need it's own cell, obviously the poor-mans functionality would be to just open a Safari VC like we do for commits or alternatively we could create a super basic tag UI using the V4 API (comes under the "Release" entity and has everything we need!

<details>
<summary>Expand for JSON</summary>
<pre>
{
    "id": "295014253",
    "unread": true,
    "reason": "subscribed",
    "updated_at": "2018-01-20T10:36:04Z",
    "last_read_at": null,
    "subject": {
      "title": "1.2",
      "url": "https://api.github.com/repos/louisdh/terminal/releases/9315552",
      "latest_comment_url": "https://api.github.com/repos/louisdh/terminal/releases/9315552",
      "type": "Release"
    },
    "repository": {
      "id": 116499200,
      "name": "terminal",
      "full_name": "louisdh/terminal",
      "owner": {
        "login": "louisdh",
        "id": 1129119,
        "avatar_url": "https://avatars0.githubusercontent.com/u/1129119?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/louisdh",
        "html_url": "https://github.com/louisdh",
        "followers_url": "https://api.github.com/users/louisdh/followers",
        "following_url": "https://api.github.com/users/louisdh/following{/other_user}",
        "gists_url": "https://api.github.com/users/louisdh/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/louisdh/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/louisdh/subscriptions",
        "organizations_url": "https://api.github.com/users/louisdh/orgs",
        "repos_url": "https://api.github.com/users/louisdh/repos",
        "events_url": "https://api.github.com/users/louisdh/events{/privacy}",
        "received_events_url": "https://api.github.com/users/louisdh/received_events",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/louisdh/terminal",
      "description": "OpenTerm, a sandboxed command line interface for iOS",
      "fork": false,
      "url": "https://api.github.com/repos/louisdh/terminal",
      "forks_url": "https://api.github.com/repos/louisdh/terminal/forks",
      "keys_url": "https://api.github.com/repos/louisdh/terminal/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/louisdh/terminal/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/louisdh/terminal/teams",
      "hooks_url": "https://api.github.com/repos/louisdh/terminal/hooks",
      "issue_events_url": "https://api.github.com/repos/louisdh/terminal/issues/events{/number}",
      "events_url": "https://api.github.com/repos/louisdh/terminal/events",
      "assignees_url": "https://api.github.com/repos/louisdh/terminal/assignees{/user}",
      "branches_url": "https://api.github.com/repos/louisdh/terminal/branches{/branch}",
      "tags_url": "https://api.github.com/repos/louisdh/terminal/tags",
      "blobs_url": "https://api.github.com/repos/louisdh/terminal/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/louisdh/terminal/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/louisdh/terminal/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/louisdh/terminal/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/louisdh/terminal/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/louisdh/terminal/languages",
      "stargazers_url": "https://api.github.com/repos/louisdh/terminal/stargazers",
      "contributors_url": "https://api.github.com/repos/louisdh/terminal/contributors",
      "subscribers_url": "https://api.github.com/repos/louisdh/terminal/subscribers",
      "subscription_url": "https://api.github.com/repos/louisdh/terminal/subscription",
      "commits_url": "https://api.github.com/repos/louisdh/terminal/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/louisdh/terminal/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/louisdh/terminal/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/louisdh/terminal/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/louisdh/terminal/contents/{+path}",
      "compare_url": "https://api.github.com/repos/louisdh/terminal/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/louisdh/terminal/merges",
      "archive_url": "https://api.github.com/repos/louisdh/terminal/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/louisdh/terminal/downloads",
      "issues_url": "https://api.github.com/repos/louisdh/terminal/issues{/number}",
      "pulls_url": "https://api.github.com/repos/louisdh/terminal/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/louisdh/terminal/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/louisdh/terminal/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/louisdh/terminal/labels{/name}",
      "releases_url": "https://api.github.com/repos/louisdh/terminal/releases{/id}",
      "deployments_url": "https://api.github.com/repos/louisdh/terminal/deployments"
    },
    "url": "https://api.github.com/notifications/threads/295014253",
    "subscription_url": "https://api.github.com/notifications/threads/295014253/subscription"
  },
</pre>
</details>

**Comment by BasThomas** [comment]
Same goes for those new security vulnerabilities

**Comment by rnystrom** [comment]
Wo! I don’t think I’ve ever seen the `Release` type! Super cool.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Happy to pick it up once I get a chance, but a bit busy at the moment!

**Comment by j-f1** [comment]
The app seems to be unable to load the notification list if you have an unread security vulnerability, and loading the All Notifications list back to where the read vulnerability is causes an error.

**Comment by BasThomas** [comment]
Hey @j-f1, can you create a separate issue for that? Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Also if anyone can grab a JSON response that’d be great. Just need to make a model.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I'll create a ticket and close this one; this should be resolved.

**Comment by rnystrom** [comment]
Closing this b/c we support releases now, tracking vulnerabilities elsewhere
