### ISSUE TITLE
List of users is incomplete

### ISSUE THREAD

**Issue by paulofierro** [GitHawkApp/GitHawk#1463]
In one of my private repos I can’t assign an issue to a user because the list of users stops at the letter O. No more users are loaded and thus they can’t be assigned.

I realise this is probably arbitrary but we only have 47 users.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513134612)
Device: iPhone X (iOS 11.2.2)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Oh shoot this is for assigning users? We probably don’t have paging working. This view needs an overhaul.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by paulofierro** [comment]
@rnystrom yep, I'm referring to the list that is displayed when viewing an issue and tap `Manage > Assignees`.

**Comment by SD10** [comment]
I'll fix this one

**Comment by SD10** [comment]
Looks like I only fixed this on the assignees view controller. Guessing that the assignees and mentions views aren’t getting the users from the same request?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Probably not, as they can be different.

**Comment by SD10** [comment]
Duh, thanks @BasThomas. I’ll fix this late tonight if no one does first

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
So it looks like `mentionableUsers` is being [limited to 20](https://github.com/GitHawkApp/GitHawk/blob/66dc61ace0a384419e390aeec2218a678fbb6b9d/gql/IssueOrPullRequest.graphql#L6) inside the `IssueOrPullRequest` query. I'm new to graphql but I'm thinking the best thing to do would be to separate this into its own query?

**Comment by BasThomas** [comment]
Closed by #2091
