### ISSUE TITLE
Checkboxes sometimes don't render

### ISSUE THREAD

**Issue by Killectro** [GitHawkApp/GitHawk#1482]
Sometimes in a long list of check boxes one doesn't render properly. Sadly this was in a private repo so I can't share the real example with you but I've attached a photo.

The context was that there was a chunk of text at the top, then a couple of empty check boxes that didn't render, and then an unrendered filled check box, and then all of the boxes below the first correctly rendered box worked fine. 

Githawk 1.17.1, iPhone X, iOS 11.2.5

![GitHawk Upload by Killectro](https://i.imgur.com/xBZRYM6.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Are you able to edit the original comment to get the exact mark down and post it in here? Would make this a lot easier to debug!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Killectro** [comment]
This is a list to keep track of things to look into while doing Localization.

- [ ] `normalizeError()` method is used for both analytics and user-facing errors. Either make the analytics value not localize, or refactor the other uses of `normalizeError()` to decouple them from the analytics-facing implementation.

- [ ] Do an audit of better, more consistent generic error messaging. Less translation and more consistency across both platforms?

- [x] Create `AppEnvironment` or similar that will handle locale and other app-wide info
- [x] Figure out whether or not we translate `Then & Now` ---- **We are**
- [x] How do we handle streak numbers on the outro? Right now "Timehops in a row" and the streak number are 2 separate labels for the animation. Do we combine them and use normal formatting rules? Do we somehow specify the number as being hidden from in the YAML and have the generated source handle it? Do we figure out the `few`/`many`/`one`/`two` in code and pass that as a parameter? How does Android handle this case?
- [x] Localize iOS-specific app names like "Messages" and "Camera Roll"
- [x] Convert Date logic to Swift and localize those strings
- [x] Do we need `LocaleLocator.swift`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Killectro** [comment]
That is the full comment scrubbed of any private info

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Seems to be fixed
