### ISSUE TITLE
Support for Custom Emojis

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1485]
https://github.com/Instagram/IGListKit/pull/1068#issuecomment-362641228

:trollface: 

Not sure on which other ones there are

**Comment by BasThomas** [comment]
A lot: https://www.webpagefx.com/tools/emoji-cheat-sheet/

**Comment by Sherlouk** [comment]
Not all of those are GitHub only though, like we have 90% of them already because we use the Unicode standard list of emojis

GitHub does have a handful of unique ones though

**Comment by BasThomas** [comment]
Yeah, but they do not work in the app now regardless.

**Comment by Sherlouk** [comment]
I'm not following? If I do `:smile:` then it does the correct emoji?

**Comment by Sherlouk** [comment]
Exactly! Maybe the titles a bit misleading, but GitHub has different emojis/emoticons/images that are not actual emojis but would be cool to support it since GitHub Desktop does!

**Comment by rnystrom** [comment]
Does anyone have a repo of GitHub supported emoji? Now that we have checkbox support via local images this ought to be really easy.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrtnrst** [comment]
I've used this one before @rnystrom 
https://gist.github.com/rxaviers/7360908
