### ISSUE TITLE
Unread badge count should reflect actual unread notifications

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#1534]
Currently it shows how many notifications are in the inbox, regardless of their read status.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1518753170)
Device: iPhone 6s (iOS 11.2.5)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
I might be misunderstanding what you mean, but your inbox *is* your unread notifications. You can swipe to mark the item as read, or use the tick in the navigation bar to mark everything as read.

Entering an issue/PR does not (automatically) mark the content as read as the desktop version does (unless you have the "Read on Open" option enabled in the settings)

**Comment by gingerbeardman** [comment]
Yes, I have "read on open" set.

For example, this screenshot makes no sense. Especially when you close the app and it still shows the badge. 

![GitHawk Upload by gingerbeardman](https://i.imgur.com/WjurVCr.jpg)

**Comment by BasThomas** [comment]
Indeed, seems like we would need to update the badge count if `read on open` is turned on.

**Comment by rnystrom** [comment]
Small bug, great starter task for anyone that wants to pick this up! Filtering happens in `NotificationsViewController`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
I'll take a look myself later

**Comment by travjunt** [comment]
Should this issue still be open? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@travjunt good call I think this is fine now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
