### ISSUE TITLE
Reply button on comments

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1551]
Far right (opposite reaction button). Tap and prefill text with `@mention` text. Maybe long press to mention _and_ quote?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1519059961)
Device: iPhone X (iOS 11.2.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
I prefer just quoting. If you are responding to someone in an issue, there's a high chance they are subscribed anyway, so they will receive a notification regardless of them being mentioned or not.

**Comment by SD10** [comment]
@BasThomas The thing I like about the mention though is it provides some context for the discussion. 
Maybe we could do something like automatically insert some form of visual representing where the quote came from 😛 

See below:

_**BasThomas**_:
>I prefer just quoting.

**Comment by BasThomas** [comment]
Fair point. At that point I would prefer to `@mention` anyway - to provide context as you said. It wouldn't hurt either (you'll get the notification regardless) and making it bold/italic to mimic something feels even weirder. 😛

**Comment by jdisho** [comment]
I am taking this 😊

**Comment by jdisho** [comment]
Adding the replay button on far right of the reaction button is a problem when it comes to the case when a lot of reactions are there. Moreover, when you have an iPhone SE. Too cluttered.

![simulator screen shot - iphone se - 2018-03-18 at 13 14 04](https://user-images.githubusercontent.com/8223362/37565705-42be93ee-2aae-11e8-9c60-5023e8d62ceb.png)


I have two suggestions regarding this: 

1. `Replay` is in the action sheet like `Edit`, `Delete`, `Share`.
2. Swipe from right to left on comment cell to replay. ❤️

Let me know what do you think @rnystrom

**Comment by rnystrom** [comment]
@jdisho let’s go with putting reply (“reply” btw 😉 ) in the action sheet menu. It’d be fun to convert that menu to a context menu anyways where we can add icons.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
