### ISSUE TITLE
Unable to view pdf image

### ISSUE THREAD

**Issue by remypanicker** [GitHawkApp/GitHawk#1552]
I have an iOS codebase where vector assets are supplied in pdf format. When I tried to view an asset, the app did not render the pdf. Instead I got an error saying “Cannot display file as text”.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.1 (1516660142)
Device: iPhone X (iOS 11.2.5)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
That’s unfortunately not supported yet. Maybe you can open a pull request to add support?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vanyaland** [comment]
@BasThomas  I'll try it the other day.

**Comment by vanyaland** [comment]
WIP
