### ISSUE TITLE
Thoughts on Waffle.io?

### ISSUE THREAD

**Issue by heshamsalman** [GitHawkApp/GitHawk#1584]
http://waffle.io

![image](https://user-images.githubusercontent.com/3388381/36636913-e209f938-199d-11e8-9a14-3e6366a28985.png)

Thoughts about using Waffle to manage the project and track work being done? @rnystrom would have to set up the hooks. It's pretty lightweight -- tickets are just GitHub issues, and the WaffleBot just moves them across lanes and closes issues linked to PRs.

**Comment by Sherlouk** [comment]
Pardon my naivety but what does Waffle give us that GitHub Projects doesn't? (Though I do agree that a tool, irrespective of which one, would definitely help with prioritisation of features and better transparency of objectives)

**Comment by heshamsalman** [comment]
I think the only things it does over GitHub projects is move tickets through the kanban board automatically, and auto-label tickets (in-progress, needs-review, etc). 

It also tracks new PRs opened up by non-collabs as a new ticket in a separate swim-lane. 

AFAIK those are the only differences but their may be others. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Another benefit of GitHub projects though is it would give us an excuse to start implementing it into the app 😉

**Comment by jdisho** [comment]
Should we close this?

**Comment by BasThomas** [comment]
Can always re-evaluate in the future!
