### ISSUE TITLE
Integration with Working Copy

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1586]
Working Copy.app has fantastic URL scheme docs. Still parsing them, but I'd _love_ to get something working where integration w/ Working Copy is seamless.

https://workingcopyapp.com/url-schemes.html

What sort of stuff could you envision doing?

**Comment by Sherlouk** [comment]
I think the most common would be the show/clone option

`working-copy://show?remote={{git url}}`

**Comment by palmin** [comment]
This issue looks complete.
