### ISSUE TITLE
Change hollow bullets icon for Settings to something else

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#160]
Version: 1.2.0 (910)
Device: iPad Pro (iOS 10.3.2)

In Splitview, you can see both the settings icon and the more options icon of an issue, but both button images are the same, which is confusing. Maybe we can change the settings to some sort of gear icon instead?

**Comment by rnystrom** [comment]
I really dislike the gear icon for the home splash, maybe I can change the one on issues? I'll play around w/ this sometime.

**Comment by BasThomas** [comment]
Closing as we do not have the more options in the master view anymore, which resolves this.
