### ISSUE TITLE
Warn that signing out removes bookmarks

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1606]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1519713428)
Device: iPhone X (iOS 11.2.5)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Should we just put some copy in the logout message to the effect of "all your stuff will be gone"?

**Comment by BasThomas** [comment]
Sounds like a good idea.

**Comment by jdisho** [comment]
@rnystrom I don’t understand.. why removing the bookmarks in logout? 😔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Probably because we do not link recent searches to a user. Should we?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
That means they would be removed upon logout as well, though.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
@BasThomas why not leaving bookmarks and “recent searches” in there after a logout?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
So right now bookmarks will be lost, but recent searches won’t. Bookmarks are tied to a user (which you log out off), recent searches are global.

The reason for not “leaving” bookmarks at that point is that if we wanted to do so, we’d have to also keep a reference to the user, which wouldn’t be ideal.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Probably fine to nuke searches too, not too offended by it tho

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I'm not sure what's so bad about keeping them around tbh? We don't need to hold a reference to the user per-sè rather the name of the bookmarks file (where it's saved) should be the same irrespective of the logged in state

If I have a file stored on the device as "Bookmarks-Sherlouk" then I sign in as a different account, I wouldn't see them. but if I logged back in as Sherlouk, I would see it once again - this only fails if it's based on a per-session ID which I don't think it should be?

Probs missing something

**Comment by BasThomas** [comment]
That would work, just not a big fan of dangling information.

Also, although I don't think we'd have to worry about it, you can change your GitHub name and then we'd lose the connection to those files.

**Comment by Sherlouk** [comment]
Definitely a valid point, so rather than the username it _could_ be something else like the user ID - though I think this is so much of an edge-case that I think we're okay to just deal with it? If that's the only circumstance you lose your data, I think that's fair

I also don't think dangling info is too bad here, i get what you're saying in principle but the data is so trivial/small and can be cleaned completely with a super quick reinstall I don't think it's an issue

Though I'm happy to leave this to other people to decide, but IMO I wouldn't want to lose the data!

**Comment by gingerbeardman** [comment]
Just signed out to sign in using Personal Access Tokens... lost all my bookmarks 😡
