### ISSUE TITLE
Support emoji in labels

### ISSUE THREAD

**Issue by lleger** [GitHawkApp/GitHawk#1616]
GitHub [recently released](https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/) a feature allowing you to add emoji to label names. This allows you to do `bug 🐛` instead of the boring `bug`.

GItHawk doesn’t yet recognize emoji in labels and just renders it as a string. It looks like this:
![a914c35c-6302-4604-9bd7-e23261202107](https://user-images.githubusercontent.com/52359/37014011-428d0184-20c3-11e8-909d-262bf321a091.jpeg)

**Comment by BasThomas** [comment]
> API and Enterprise support for these features is coming soon!

☹️

**Comment by SD10** [comment]
@BasThomas I think this issue is just about replacing the emoji token with the proper emoji. I don’t think it has anything to do with the GitHub API. The new features for labeling were more fields. ie) Description. Maybe I’m mistaken?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Ah, I don't know what their backwards-compatability is; they previously would choke on emoji, so I would assume they don't support emoji in the responses at this point either? That could potentially break old clients. We can check?

**Comment by BrianLitwin** [comment]
+ 1 now that we've got emoji's in our bug label.. I'm going to look at this since I'm working on a few things related to labels already, but if anybody else knows how to fix, feel free!
