### ISSUE TITLE
Recreate Things 3 menu UI

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1621]
I'm pretty obsessed w/ T3 right now. I want to hack around at making an open source UI control for their menu. Maybe it could serve as a replacement for managing issues/repos vs the action buttons?

Also could satisfy #1598.

Started sketching out some ideas, will find some time to play w/ it, even if it just ends up being for fun. Such a wonderful UI element.

**Comment by BasThomas** [comment]
Can you show us how it looks? 😃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
![img_1511](https://user-images.githubusercontent.com/739696/37123176-3b42c44e-2231-11e8-810e-a42b763bc71e.gif)

![img_1512](https://user-images.githubusercontent.com/739696/37123116-111af93e-2231-11e8-9ad9-ccf0f135887e.jpeg)

![img_1513](https://user-images.githubusercontent.com/739696/37123117-1147511e-2231-11e8-8731-d1bad5b98f93.jpeg)

**Comment by rnystrom** [comment]
Hacked at it last night. I'm really happy w/ it so far. Will open source as its own control!

![img_1522](https://user-images.githubusercontent.com/739696/37217897-d8c01fbc-238c-11e8-9b1c-d182ec440319.gif)

**Comment by SD10** [comment]
This can be closed. The new project for this is hosted at https://github.com/GitHawkApp/ContextMenu
