### ISSUE TITLE
View source code should open in GitHawk

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#1629]
View source code should open repo in GitHawk rather than web view? 

![GitHawk Upload by gingerbeardman](https://i.imgur.com/86GWhKs.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1520219174)
Device: iPhone 6s (iOS 11.2.6)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Ya! Would def accept a PR on this. Should be easy.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
I'll take a look

**Comment by ajfigueroa** [comment]
@gingerbeardman  I was curious to how this would work and ended up implementing it under: https://github.com/GitHawkApp/GitHawk/pull/1698. 

I can close my PR though if you already had one ready though, it's no problem!

**Comment by gingerbeardman** [comment]
I never got round to it, so thanks!

**Comment by ajfigueroa** [comment]
@gingerbeardman Oh shoot, I meant to say I had opened a PR but it has not been approved/merged yet.

I think this issue can remain open until then.
