### ISSUE TITLE
Can’t upload any image

### ISSUE THREAD

**Issue by erkekin** [GitHawkApp/GitHawk#1635]
iPhone 6 ios 11.3 beta 
Cant upload image, says something went wrong

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1519488669)
Device: iPhone 6 (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Hmm odd, is anyone else hitting this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@erkekin still happening?

**Comment by Sherlouk** [comment]
I'd be interested to know what image you're trying to upload too, imgur has a maximum file size limit which _could_ return this error (which is the reason we added compression) - I tried a lot of fairly big images though and couldn't get this to happen!

**Comment by shaps80** [comment]
Oops sorry about lock/unlock. Was trying to scroll and my phone locked up. My bad 😬

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erkekin** [comment]
Still happening. I topk a screenshot of that “sth went wrong” toast message now. But can’t upload.

**Comment by rnystrom** [comment]
@erkekin could you debug with FLEX (three finger tap) and post back with the networking response?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
No Testflight right?

**Comment by BasThomas** [comment]
Can't replicate on an iPhone 6 sim running 11.3 😕

**Comment by erkekin** [comment]
No Testflight. Now I'm trying to debug with FLEX, trying to figure out how to do that :)

**Comment by BasThomas** [comment]
Yeah, FLEX is only available in Testflight builds I am afraid :(

**Comment by erkekin** [comment]
Oh, I didn't know that. Could you add me? _erkekin {at} gmail {dot} com_

**Comment by BasThomas** [comment]
ping @rnystrom

**Comment by rnystrom** [comment]
Will add!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by erkekin** [comment]
curl -v -X GET 'https://api.imgur.com/3/credits' -H 'User-Agent: Freetime/1.19.0 (com.whoisryannystrom.freetime; build:1520915257; iOS 11.3.0) Alamofire/4.4.0' -H 'Accept-Language: tr-TR;q=1.0, en-US;q=0.9' -H 'Authorization: Client-ID 903b9dfdddeaab4' -H 'Accept-Encoding: gzip;q=1.0, compress;q=0.5' -H 'Cookie:'        İt gave this curl

**Comment by rnystrom** [comment]
@erkekin can you view and copy/paste the response body?

**Comment by erkekin** [comment]
I updated it in Testflight, I can't reproduce it now.
