### ISSUE TITLE
Remove done button from label/people/milestone

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1647]
Just update as you select things. Esp with the new menu, I want to just select stuff and then tap the bg to dismiss.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
> Just update as you select things.

Do you mean to update on dismissal? If not, I think updating as we select things can lead to some messy issue history 😕

**Comment by rnystrom** [comment]
On dismiss would be fine

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Resolved by #1655
