### ISSUE TITLE
Report bug broken now that org changed

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1648]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Good to know that the API doesn't respect redirects 🤔

**Comment by rnystrom** [comment]
Ya 🙄 broke bookmarks too. API seems to work when reading, but breaks when writing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Maybe something to report? Seems like an oversight.

**Comment by rnystrom** [comment]
@BasThomas good idea

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by YuryBogdanov** [comment]
Not only report bug was broken. 
It seems that new pull requests are not built on CI :( can anyone check that?

**Comment by rnystrom** [comment]
Ruh roh, I’ll take a look

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Fixed CI
