### ISSUE TITLE
Handoff to GitHub.com on Mac

### ISSUE THREAD

**Issue by schrodincat** [GitHawkApp/GitHawk#1649]
It would be nice to have support for handoff feature.

The use case is pretty obvious, say I’m opening an issue or something else after reading notification in the app, what if I want to dig deeper in the code or conversation and my Mac is nearby? It would be handy (😅) to have handoff to Safari on Mac with a link to corresponding issue or something else you’re currently viewing in the app on GitHub.com. It also fits pretty nicely in the philosophy of the app to not have full-blown GitHub experience on mobile.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas how much handoff support did you add before?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schrodincat** [comment]
@rnystrom zero, I’m afraid, I’m not familiar with iOS developmnet

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
Handoff works when you are in an issue or pull request. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schrodincat** [comment]
@jdisho argh, you're absolutely right, it is working. Maybe it was some quirkiness in my home network when I've tried it the first time. I'll close the issue then.

**Comment by BasThomas** [comment]
Yup, issues and pull requests are supported. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
