### ISSUE TITLE
[Proposal] Supporting GitLab

### ISSUE THREAD

**Issue by jdisho** [GitHawkApp/GitHawk#1650]
What if, in a near future GitHawk supports also Gitlab? 

Thoughts? 💭

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
This is a duplicate of #408

**Comment by jdisho** [comment]
Aah!!! 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
