### ISSUE TITLE
Share bookmarks between two devices

### ISSUE THREAD

**Issue by marcuswu0814** [GitHawkApp/GitHawk#1660]
Is it possible share bookmarks when using multi device? Maybe store data on the iCloud etc.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Could totally be possible, but isn't atm. iCloud storage seems like the safest bet for this!

**Comment by BasThomas** [comment]
Closing in favor of #702
