### ISSUE TITLE
Limited Permissions with GitHub 2FA

### ISSUE THREAD

**Issue by SD10** [GitHawkApp/GitHawk#1667]
~After dismissing the users context menu, it shows the assignee added in the timeline view, then the add request errors out with a generic error from toast, and the assignee is removed from the timeline view.~

Logging in to a 2FA account through Safari does not allow me to assign users to issues.

Logging in using a personal access token with the `repo` and `user` scopes allows me to assign users on repos which I am a owner of (but not collaborator).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@SD10 able to debug in flex? Not happening for me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Looking into it. This error does not occur on the GitHawk test playground. It only occurs for me on my MessageKit repo. 

```
Request URL: https://api.github.com/repos/MessageKit/MessageKit/issues/575/assignees
Request Method: POST
Status Code: 403
Response Body: "message": "Must have admin rights to the Repository."
```

**Comment by SD10** [comment]
When trying to unassign myself from this issue, it shows `SD10 unassigned SD10` locally but no changes persist on GitHub or after leaving the controller 😂 

```
Request URL: https://api.github.com/repos/GitHawkApp/GitHawk/issues/1667/assignees
Request Method: DELETE
Status Code: 200 OK
Response Body: ... a lot of JSON
```

**Comment by SD10** [comment]
Sorry to spam but @rnystrom could it be that I enabled 2FA yesterday?

**Comment by rnystrom** [comment]
Dang that’s tricky. Maybe we need better alerting when you lose permissions for certain actions? I could imagine pulling my hair out over something like this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Yeah, I haven’t had time to investigate but I’m going to try a personal access token with all options next. Not sure what effect that will have because the remaining options are unrelated to what I want to accomplish.

I find it perplexing that I would not have full permissions after logging in with safari + GitHub 2FA

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Weird, as of today I’m able to perform write operations again without having changed anything. So glad I can finally start using GitHawk again 😍 Closing this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
