### ISSUE TITLE
Personal repo browse

### ISSUE THREAD

**Issue by djanjic** [GitHawkApp/GitHawk#1668]
Hello, how can I check my github repos and projects without using a search function? Can’t find that option in the app.

**Comment by SD10** [comment]
Hey @djanjic,

I don't think there's any way to do this at the moment. You can currently only see:
- Activity from repos you are subscribed to
- Repos you search for
- Repos you have bookmarked

This may be something that becomes available through #317

**Comment by djanjic** [comment]
Hi @SD10 
Looks interesting, thanks for the answer.
I will close this now.
