### ISSUE TITLE
Increase iPad Contextmenu sizes

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1669]
We should calculate the size based on... what?

![GitHawk Upload by BasThomas](https://i.imgur.com/PgXYHgz.jpg)

**Comment by rnystrom** [comment]
What would you suggest?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
What about the app’s window size? It’s tricky though with updating splitview sizes and rotation. :/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
The window size? Wouldn’t that be huge?

I’m confused about what’s wrong or could be better.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
It’s not “wrong”, just that I think it could be bigger (in this case, at least more vertical room)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
And I meant based on the window, not the whole window of course. :p

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Not really sure he best action here, gonna close unless we’ve got a solid plan

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
