### ISSUE TITLE
Issue with apollo-codegen

### ISSUE THREAD

**Issue by jdisho** [GitHawkApp/GitHawk#1672]
I am trying to run GitHawk, but somehow apollo script is not working. API.swift have no content after the script runs.
I am lost on this because globally I have `apollo-codegen@0.18.8`, the same as the one in the app.  😕

**Comment by jdisho** [comment]
<img width="1056" alt="screen shot 2018-03-21 at 13 40 45" src="https://user-images.githubusercontent.com/8223362/37710312-8bccbea6-2d0d-11e8-876c-7288bd7fa4ea.png">

... and this is weird

**Comment by rnystrom** [comment]
What happens if you run `npm install` from the project dir?

**Comment by jdisho** [comment]
@rnystrom Tried that before, not working. 😕
Probably there is a problem with apollo script? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
Any idea? 💡  @SD10 @BasThomas

**Comment by BasThomas** [comment]
Have you followed the installation instructions from [the Readme](https://github.com/GitHawkApp/GitHawk#installation)? What is the output for `brew install node`? You shouldn't have to run `npm install` in the beginning; only after you've cloned. I think we should update this documentation to make that more clear.

**Comment by jdisho** [comment]
@BasThomas Sure, I followed the installation instructions. This problem occurred as soon as I pulled the changes from `master`. Before updating to `apollo-codegen@0.18.8` everything was working fine.

Btw, the outputs output for `brew install node` and `npm install `:

<img width="452" alt="screen shot 2018-03-22 at 22 02 56" src="https://user-images.githubusercontent.com/8223362/37799142-19ae7f9a-2e1f-11e8-9517-b98c8b926e82.png">
<img width="516" alt="screen shot 2018-03-22 at 22 00 39" src="https://user-images.githubusercontent.com/8223362/37799143-1ab2c9f0-2e1f-11e8-938f-db928efa1c1c.png">

**Comment by jdisho** [comment]
@rnystrom Is it necessary to add the apollo script in the repo when the API.swift is there?

**Comment by SD10** [comment]
Hey @jdisho, sorry I've had little time for GitHawk lately 😭 I did get the same error a few days ago I think when upgrading apollo. I just fixed it in a brutish way by clearing all derived data, restarting simulators, Xcode, and a fresh install.

**Comment by BasThomas** [comment]
A fresh install of what? 😛

**Comment by rnystrom** [comment]
@jdisho hmm I’m really not sure tbh... if the file is empty and the script is writing there’s def a problem with the local install.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I ran the instructions in a separate clone of the repository and that just worked. 🤔
It does, however, only generate the `Freetime-AppCenter` scheme (not sure if related), what's up with that @rnystrom?

**Comment by SD10** [comment]
Sorry, I meant a fresh `npm install`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas leftover scheme from trying AC, but I already migrated Bitrise to use it. Uses the shared scheme with dummy env vars.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
@jdisho May be your `npm install` doesn't work properly.  


Can you confirm you can find this folder in your repo.

`node_modules/apollo-codegen/`

Btw, this is what I get when I run project from master branch now.

![screen shot 2018-03-23 at 6 24 04 pm](https://user-images.githubusercontent.com/12063704/37830108-7c1d44ba-2ec7-11e8-983d-634ae24afbdc.png)

**Comment by BasThomas** [comment]
@rnystrom yeah but it does not generate a normal “GitHawk” scheme :/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by orta** [comment]
You probably want to run ‘npm uninstall -g Apollo-codegen’
