### ISSUE TITLE
Show hover cards for user profiles

### ISSUE THREAD

**Issue by SD10** [GitHawkApp/GitHawk#1675]
Not directly related to #317 user profiles but could be a lightweight solution/addition.

![screen shot 2018-03-21 at 9 06 22 pm](https://user-images.githubusercontent.com/7445580/37747163-dbd92086-2d4b-11e8-850b-1bc801570706.png)

Kind of also fits well with things if we decide to go the context menu route.

**Comment by BasThomas** [comment]
I would think this is something for a long press / 3d touch on an avatar. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I'm gonna close out, just tapping on it should open profile. 3D touch into profile could supplement this.
