### ISSUE TITLE
Use GitHub to get the combined status of a pull request

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1679]
TIL "there's an endpoint for that"

https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref

**Comment by rnystrom** [comment]
What’s this offer vs what we fetch now via GQL?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
We do this manually now 😬
Should do via GraphQL if available. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas are we talking about different things? We get PR commit context info via GQL:

https://github.com/GitHawkApp/GitHawk/blob/master/gql/IssueOrPullRequest.graphql

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Are we doing this manually then though we have the info? https://github.com/GitHawkApp/GitHawk/blob/ddddb6363f008c2ec50bb010031cbd851676dc8a/Classes/Issues/Merge/MergeHelper.swift

**Comment by rnystrom** [comment]
The contexts come in as a list for each (push, pull, different CIs, etc). To make a call on mergeability, we have to reduce them all down.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah but the reducing is exactly what is done by the endpoint, right? I don't understand 😔
