### ISSUE TITLE
Viewing archived repo notifications shows all

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1682]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I think this was intended somehow?

**Comment by rnystrom** [comment]
No I mean tapping on a repo in the action sheet shows all notifications, should be only for that repo.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
I will take a look 👀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Sorry @jdisho, fixed this already when debugging other stuff 😁
