### ISSUE TITLE
Merge via chevron seems to no-op

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1684]

**Comment by rnystrom** [comment]
It just changes the merge type to “merge” 😂 maybe we can update the naming?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Ah! Yeah, good idea. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Because there’s no visual feedback at all if it was already that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Maybe add a title to the sheet? “Merge strategy is now: x”. 
Message: “change to...”
And then remove the currently selected one so you can only choose the others?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya title sheet sounds great!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Why did you close this one?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Oh ya we’re just changing the title

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
