### ISSUE TITLE
Merge pull request 404s

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1685]
![GitHawk Upload by BasThomas](https://i.imgur.com/CJiR1vW.jpg)

![GitHawk Upload by BasThomas](https://i.imgur.com/DAPSmKi.jpg)

https://github.com/tryswift/trySwiftAppFinal/issues/60

**Comment by BasThomas** [comment]
So I am getting a 404.
This is the URL: `"https://api.github.com/repos/tryswift/trySwiftAppFinal/pulls/62/merge"`

JSON response:

```
▿ 2 elements
  ▿ 0 : 2 elements
    - key : message
    - value : Not Found
  ▿ 1 : 2 elements
    - key : documentation_url
    - value : https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button
```

and a `nil` error. Can't figure out what's going wrong on our end. 😕

**Comment by jdisho** [comment]
What is the request body? 😕

**Comment by BasThomas** [comment]
This is V3 so there is none

**Comment by jdisho** [comment]
Should't this be part of the body?
<img width="658" alt="screen shot 2018-03-28 at 16 11 53" src="https://user-images.githubusercontent.com/8223362/38034526-c5d0c49a-32a2-11e8-849e-179cd0d2e338.png">

**Comment by BasThomas** [comment]
Oops, of course - you're absolutely right.

I merged the pull request earlier, but I am pretty sure we only provide the `merge_method`, which, in my case, was `merge` - set explicitly.

**Comment by jdisho** [comment]
Does it work now @BasThomas ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I guess not? Not sure
(Checked: no)

**Comment by rnystrom** [comment]
@BasThomas any progress on this?

**Comment by BasThomas** [comment]
Not yet

**Comment by BasThomas** [comment]
Still failing as of today 😐

**Comment by rnystrom** [comment]
@BasThomas is there a chance you’re trying to merge with a strategy (rebase/squash/merge) not allowed by the repo?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
The SHA part doesn’t seem right because that doesn’t explain why it works in other repos...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Could be! It was Swift Weekly Brief; I think we squash by default. Will check!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I’ve been meaning to log that as an issue. I haven’t seen a way to restrict the merge options yet. If anything if this response returns 404 the error should say “can’t merge with x”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
They did add the API! Putting up a PR now. I'm so glad this is a thing now!
