### ISSUE TITLE
Mark repo as read doesn't update cells

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1690]
1. Go to notifications
2. Go to ... And enter a repos archives
3. Mark all as read
4. Notice that they still look as if they haven't been read
5. (Bonus) pull to refresh doesn't fix it either, have to leave and come back in before it does its stuff

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
I will take care of this, unless you haven’t @Sherlouk  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Nah I'm on my hols at the moment haven't even got a laptop to do it if I wanted to 😂 free to pick up!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
