### ISSUE TITLE
View archives list doesn't update

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#1691]
1. Go to notifications
2. Go to ... And visit a repos archives
3. Mark as read
4. Go back
5. Go to ... And visit the same repos archives
6. Notice how the page you've gone to is for all notifications not the repos specifically

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
7. (Bonus) notification count doesn't update immediately either 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Ahh this is dupe, we should probs fix the notification count and the fact it doesn't remove from list until refresh?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Closing since dupe
