### ISSUE TITLE
Cannot use self inside a super.init function - Xcode 9.3

### ISSUE THREAD

**Issue by orta** [GitHawkApp/GitHawk#1695]
Pretty sure this is a new Swift 4.1 rule, but code like 

<img width="1028" alt="screen shot 2018-04-01 at 9 03 38 am" src="https://user-images.githubusercontent.com/49038/38173380-a0def850-358b-11e8-997b-bf7b020e014d.png">

Doesn't compile anymore

**Comment by rnystrom** [comment]
Well crap

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah we should fix these, its 4.1. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
