### ISSUE TITLE
Make bookmark button disabled instead of not appearing

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1700]
On an issue load, the bookmark button is not shown until it has fully loaded. 

Although small, I propose to allways show said button but make it disabled during loading. Feels a bit more intuitive.

**Comment by rnystrom** [comment]
Ya I dig this, it’s not like we’ll never show the button anyways. Great suggestion.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jamala** [comment]
I'll take a crack at this.
