### ISSUE TITLE
Difficult to tap the paper plane button

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#1710]
Why does it always take me 2 or 3 taps to activate the paper plane button?

**Comment by gingerbeardman** [comment]
![GitHawk Upload by gingerbeardman](https://i.imgur.com/SOqDI8n.jpg)

**Comment by BasThomas** [comment]
It does seem like the hit target is rather small. Can you open an issue on https://github.com/GitHawkApp/MessageViewController?

<img width="517" alt="screen shot 2018-04-10 at 11 41 12" src="https://user-images.githubusercontent.com/4190298/38549347-184d24aa-3cb4-11e8-9840-2da3c548eae1.png">

**Comment by BasThomas** [comment]
I've created https://github.com/GitHawkApp/MessageViewController/issues/55, closing this.
