### ISSUE TITLE
Crash when opening a pull request overview

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1719]
I get a `Thread 1: Fatal error: Unhandled object: Freetime.IssueTargetBranchModel` [here](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Issues/IssuesViewController.swift#L460).

All pull requests seem to crash; issues are unaffected.

**Comment by BasThomas** [comment]
Also crashes when viewing the pull request from somewhere else.

**Comment by jdisho** [comment]
@BasThomas How can you replicate it? It doesn’t happen to me 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
On `master` or latest TestFlight. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
I am having a look at it now @BasThomas

**Comment by BasThomas** [comment]
Awesome! Any idea what broke this? 🤔

**Comment by jdisho** [comment]
@BasThomas This was missing https://github.com/jdisho/GitHawk/blob/85e2fc10352efefd013410dd53069d1707c85bd5/Classes/Issues/IssuesViewController.swift#L460 😕

**Comment by BasThomas** [comment]
Yeah I get that, but where was it introduced? 😕

**Comment by jdisho** [comment]
Accidentally I have deleted it @BasThomas .. 😱😇https://github.com/GitHawkApp/GitHawk/commit/2a7664968b967d74b446b06f817207b9941563e0#diff-70bd4c3000d4bf517bb83b2662ab56a0L429
