### ISSUE TITLE
Opening PR causes crash

### ISSUE THREAD

**Issue by bobheadxi** [GitHawkApp/GitHawk#1722]
Opening [this PR](https://github.com/ubclaunchpad/inertia/pull/139) causes a crash

iPhone SE, iOS 11.4

Edit: looks like I can’t open any PRs :(

**Comment by jdisho** [comment]
Duplicate of #1719 and is already fixed by this PR #1720. @bobheadxi 
I tried it with the latest version of `master` branch and it works.
Try it with that one 😊
