### ISSUE TITLE
Add an indication when no scroll can be performed tapping "manage"

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1723]
When you have the whole viewport in view and tap the Manage button, nothing happens. It would be a nice addition to somehow indicate that the manage options are at the bottom.

We can either add a small "bump" animation that something happened or a small flash on the manage buttons below?

Other ideas are most welcome too!

**Comment by jdisho** [comment]
I like the "bump" animation idea, but it would be useless if @rnystrom will add the buttons in the ContextMenu 🤔

**Comment by BasThomas** [comment]
Ah wait that plan was there.
