### ISSUE TITLE
Inbox cell redesign

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1727]
Teaching myself Sketch.app and using the inbox cell as a starting point. I'm trying to accomplish a few things:

- Faster interactions (tap button instead of hidden swipe)
- More, balanced whitespace
- Better information hierarchy

cc @orta you've always had great insight!

<img width="557" alt="screen shot 2018-04-14 at 6 02 17 pm" src="https://user-images.githubusercontent.com/739696/38772844-39bb0adc-400e-11e8-890b-d188d739b0ea.png">

**Comment by BasThomas** [comment]
One thing I can see being tricky with this (if I am correct that the buttons are supposed to be buttons) is tap targets.

**Comment by rnystrom** [comment]
Taking a lot of inspiration from Twitter where I find these little buttons really easy to use. Tap targets are easy to adjust.

![GitHawk Upload by rnystrom](https://i.imgur.com/rSfDUmm.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by orta** [comment]
I'm into it. 

The "..." should probably have the same right margin as the date above.  Perhaps a 0 comment could be greyed vs one with comments which could have darker text/type?

**Comment by jdisho** [comment]
My suggestion @rnystrom would be: 

Swipe right to **read**.
Swipe left to **bookmark**

… menu can also contain “copy link” and “mute/unmute” 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
Also another idea would be to replace “... more” with a long press on the cell? 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@jdisho you're suggesting no buttons?

**Comment by jdisho** [comment]
Yes, no buttons, just the the icons for **comments**, **un/subscribe** indicating the un/subscribe action  and **....**

What do you think? 😊
