### ISSUE TITLE
Can't view Issues or PRs on any repo?

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#1736]
Tried multiple repos. 

API status says Good. 

1.19.0 (1523930581)

Having to add this through the website. 

![37bb53e7-e098-4bd3-a8d9-910a986bd8c9](https://user-images.githubusercontent.com/49612/38978122-5d6930aa-43ae-11e8-8335-8212750ae8e9.png)

**Comment by jazzbox** [comment]
Same here! And CodeHub is still working....

**Comment by BasThomas** [comment]
I think this is related:

https://twitter.com/githawk/status/986783506524246017

If you're experiencing issues tonight, we've filed a report with @GitHubEng! https://platform.github.community/t/typename-field-requires-specific-token-scopes/5657

**Comment by rnystrom** [comment]
Yup was pretty frustrating right. The annoying part is that we don't explicitly use the `__typename` field anywhere, that's inserted by Apollo.

Good news is that this is an actual bug that GitHub is rolling back right now. Should be resolved shortly.

**Comment by rnystrom** [comment]
It’s working!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jazzbox** [comment]
Yeah. It‘s working again. Except for Githawks own repo....

**Comment by BasThomas** [comment]
Works for me? Do you still have the `rnystrom/GitHawk` app in your search results / bookmarks?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jazzbox** [comment]
@BasThomas that‘s it! Problem solved, thanks! 👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
