### ISSUE TITLE
Status icons not colored

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1745]
Seen this a few times, especially on a cold launch. Refreshing fixes it. 

![GitHawk Upload by BasThomas](https://i.imgur.com/pm3SwFa.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1524358860)
Device: iPhone X (iOS 11.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Models are probably cached before the status fetch finishes or something? Great issue for someone to pitch in!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rob-nash** [comment]
I haven't seen this issue and it's going to be hard to reproduce, but I think I know how the issue might be caused.

### Perform Fetch

```swift
githubClient.client.send(V3RepositoryNotificationRequest(all: all, owner: repo.owner, repo: repo.name)) { ...
```

### On Fetch Success

Create view models

```swift
CreateNotificationViewModels(
    width: width,
    contentSizeCategory: contentSizeCategory,
    v3notifications: response.data
) { [weak self] in
    self?.fetchStates(for: $0, page: response.next, completion: completion)
}
```

### During ViewModels Create

Set state to `.pending`

```swift
state: .pending, // fetched later
```

### On Create Completion

Fetch States. If `case .failure` overwrite cache (with view models in initial state `.pending`).

```swift
githubClient.client.send(ManualGraphQLRequest(query: query)) { result in
            let processedNotifications: [NotificationViewModel]
            switch result {
            case .success(let json):
                var updatedNotifications = [NotificationViewModel]()
                for notification in notifications {
                    if let alias = notification.stateAlias,
                        let result = json.data[alias.key] as? [String: Any],
                        let issueOrPullRequest = result["issueOrPullRequest"] as? [String: Any],
                        let stateString = issueOrPullRequest["state"] as? String,
                        let state = NotificationViewModel.State(rawValue: stateString),
                        let commentsJSON = issueOrPullRequest["comments"] as? [String: Any],
                        let commentCount = commentsJSON["totalCount"] as? Int {
                        var newNotification = notification
                        newNotification.state = state
                        newNotification.comments = commentCount
                        updatedNotifications.append(newNotification)
                    } else {
                        updatedNotifications.append(notification)
                    }
                }
                processedNotifications = updatedNotifications
            case .failure:
                processedNotifications = notifications
            }
            cache.set(values: processedNotifications)
```

**Comment by rob-nash** [comment]
I was thinking of maybe adding a conditional check upfront to ensure we pull a view model out of the cache or create if it doesn’t. Would happen in fetch closure.

At the moment the fetch closure is creating an empty view model every time, expecting it to be populated by new data.

**Comment by rob-nash** [comment]
I'm not up to speed with the project so I'm kinda reverse engineering as I go 😅

I can see you have a cache with a get `func` like so

```swift
func get<T: Cachable>(id: String) -> T?
```

So it looks like the view model must first be created and populated with an ID because it conforms to Cachable. Got it!

Ok, so fetch > create view model > assignID > consult cache for any existing data

if data exists then pass that cached data along to be updated.

What you think?

**Comment by rnystrom** [comment]
@rob-nash yup! Exactly

**Comment by rob-nash** [comment]
Ok, I'll give this a go this morning. 

@rnystrom would you mind giving [this one](https://github.com/GitHawkApp/GitHawk/pull/2175) a once over please?
