### ISSUE TITLE
Code blocks using different font-sizes

### ISSUE THREAD

**Issue by hacknug** [GitHawkApp/GitHawk#1746]
Code blocks font-size in this issue are different. I guess this is some kind of bug right?

https://github.com/FullHuman/purgecss/issues/67

![img_0032](https://user-images.githubusercontent.com/1107521/39095659-45b6c6be-4644-11e8-89c8-37e0804322c2.jpeg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1524358860)
Device: iPad7,5 (iOS 11.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Aha, great call out. We’re using Highlightr.js to parse code, and that lib uses a fixed font size. After the styled text refactor this should be a lot easier.

_Great_ starter task for someone!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
