### ISSUE TITLE
TestFlight beta feedback for GitHawk for GitHub

### ISSUE THREAD

**Issue by Maryom** [GitHawkApp/GitHawk#1749]
Hi,

Thanks for sending me the TestFlight.

So far it’s good. I didn’t find any bug. I just have some suggestions:

1. In the settings view I think there is no need for app ID near the version number.

2. Kindly check the attached image. Why there is an UIActionController with one option?! It will be better if the action triggers when the user click on GitHawk.

Best regards,
Mariam AlJamea.

![image4](https://user-images.githubusercontent.com/3218401/39097162-80e0cac4-4661-11e8-96fb-a0b2844f7eea.png)
![image3](https://user-images.githubusercontent.com/3218401/39097164-84337780-4661-11e8-9a72-24ac2b6c6d11.png)

**Comment by Maryom** [comment]
Hello again,

One more suggestion if you don't mind: I really like how [GitBucket](https://itunes.apple.com/cn/app/id961330940?mt=8) implements the time line. I would like to see it on GitHawkApp :)

**Comment by Maryom** [comment]
Hello again,

Today I found an issue. My inbox was one, I used GitHawkApp to reply to the message. It replied successfully but it should remove one from the inbox and display Inbox zero with the awesome animation 🎉 Kindly check the attached image.

Thanks.

Best regards,
Mariam.

![image1](https://user-images.githubusercontent.com/3218401/39253395-6b82e1fc-48b0-11e8-88cd-912da41b91ce.png)

**Comment by BasThomas** [comment]
Hey @Maryom, you can turn on “read on open” in the settings. That will mark an issue as read once opened. Is that the behavior you’re expecting?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
@rnystrom re the alertcontroller actionsheet in the original post: how do we want to handle this? Just opening it directly also feels weird having the chevron. What do you think?

**Comment by Maryom** [comment]
>@rnystrom re the alertcontroller actionsheet in the original post: how do we want to handle this? Just opening it directly also feels weird having the chevron. What do you think?

@BasThomas what about adding it to this alertcontroller 👇🏼 ?

![GitHawk Upload by Maryom](https://i.imgur.com/LjNthfk.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
The tricky thing is that we already use the navigation bar for the exact functionality (opening either the org/user and repo), but from a repo overview itself that only leaves the org/user. Putting that in the `...` is also confusing.

**Comment by rnystrom** [comment]
Ya I'm not terribly concerned w/ the single-action alert. It's nice that it's consistent w/ the rest of the app, so you expect it.

**Comment by SD10** [comment]
> Well I think it’s better to make on as the default value. What do you think?

I think making "Read On Open" the default value doesn't demonstrate this feature very well. And it's one of the main reasons I use GitHawk. I often check an issue, intend to reply later, and 💨 it's gone forever

**Comment by Maryom** [comment]
Hello,

I noticed that number of messages in the below view 👇🏼is less than the real number of messages

![GitHawk Upload by Maryom](https://i.imgur.com/IrbUd2j.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
What about after a refresh?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Maryom** [comment]
>What about after a refresh? ...

@BasThomas same issue 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Do you have a screenshot of your actual notifications? I feel like there was an issue where the API doesn’t return historical notifications (stuff prior to using GitHawk).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
It probably wouldn't hurt to start opening separate issues for different pieces of feedback/potential bugs. I'm pretty out of date with GitHawk at the moment but I'm having trouble following this thread 😅

**Comment by Maryom** [comment]
@rnystrom No I don’t have 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
+1 @SD10 that’ll help us keep hinges tracked and organized

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Maryom** [comment]
Ok I will open new issues if I find new ones 😅 sorry I thought I have to write all my feedback in one issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Closing this as I don't see any clear action points in this issue. :)
