### ISSUE TITLE
Splitview divider is white?

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1758]
There is a white vertical divider between master and detail views right now, any idea what caused this? Looks weird.

![GitHawk Upload by BasThomas](https://i.imgur.com/RkHTazP.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1524439576)
Device: iPad7,3 (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Only when collapsed is safer in that case I suppose.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas think this is worth resubmitting 1.19 for?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
We can do a followup 1.19.1 maybe?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Fixed in https://github.com/GitHawkApp/GitHawk/pull/1989
