### ISSUE TITLE
Pull Request statuses display an incorrect avatar

### ISSUE THREAD

**Issue by j-f1** [GitHawkApp/GitHawk#1762]
If you view a pull request on prettier/prettier, you’ll notice that the Travis CI statuses have @**azz**’s avatar on them in the app, but they have the correct Travis avatar on them on the desktop site.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1524439576)
Device: iPhone 8 (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Pretty sure I brought this up before and it seems to be a GitHub bug - it's the information they send back to us for the request that we use to display the status, which is sometimes incorrect. 🤷‍♂️

**Comment by rnystrom** [comment]
Yup tracking in #1558
