### ISSUE TITLE
Crash on issue view

### ISSUE THREAD

**Issue by schrodincat** [GitHawkApp/GitHawk#1765]
Opening this issue https://github.com/lhc70000/iina/issues/1641 causes GitHawk to crash.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I’ll take a look. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Oh no! Crashes for me too 😭

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schrodincat** [comment]
What the hell, is this issue crashes GitHawk too now?

**Comment by rnystrom** [comment]
Yup, something w/ the StyledText lib. Symbolicating crashes in Fabric and preparing a 1.19.1 hotfix!

**Comment by BasThomas** [comment]
Ah you're on it @rnystrom?

**Comment by rnystrom** [comment]
@BasThomas yup, more involved fix. It's an assert from cmark.

**Comment by BasThomas** [comment]
You sure? Seems like the out of bounds in `StyledText` to me.

This is the `key` and `value` before the crash (on line 75 of `StyledText.swift`):

```
NSAttributedStringKey(_rawValue: NSFont) <UICTFont: 0x7f8c5f54c470> font-family: ".SFUIText"; font-weight: normal; font-style: normal; font-size: 14.00pt
2018-04-25 19:44:18.929592+0200 Freetime[50196:11971659] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds'
```

**Comment by rnystrom** [comment]
@BasThomas yup its actually 2 things

**Comment by Maryom** [comment]
>No new beta yet probably.

@BasThomas
I received new version at 9:55 pm 🇰🇼
![GitHawk Upload by Maryom](https://i.imgur.com/JqfUxmE.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Maryom that’s the crashing version, sending beta soon.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
