### ISSUE TITLE
Reaction bar oddness is back

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#1770]
![GitHawk Upload by gingerbeardman](https://i.imgur.com/89grLqy.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1524439576)
Device: iPhone 6s (iOS 11.3.1)
TestFlight: false
</pre>
</details>

**Comment by jdisho** [comment]
What happens after dequeueing that cell? @gingerbeardman 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
Sorry I'm not sure what you mean? @jdisho

**Comment by jdisho** [comment]
What happens after scrolling up and down or refreshing? 
This issue also happened to me sometimes ago, but looked fine after scrolling/refreshing. @gingerbeardman 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Haven't seen this lately with the redesign, closing. Feel free to reopen if it occurs again/still.
