### ISSUE TITLE
TDT23

### ISSUE THREAD

**Issue by TDT23** [GitHawkApp/GitHawk#1772]
Tracking

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.1 (1524679484)
Device: iPhone 7 (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
