### ISSUE TITLE
Unexpected grey items

### ISSUE THREAD

**Issue by jazzbox** [GitHawkApp/GitHawk#1774]
I often see grey items in the input list that are not read yet. Refreshing does not change that but a program restart does.

I suppose that happens to items that are already shown and read and are then modified a second time. 

![GitHawk Upload by jazzbox](https://i.imgur.com/WbfIgfN.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.1 (1524679484)
Device: iPhone 7 (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Possible. You do have read on open turned on right?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jazzbox** [comment]
@BasThomas Yeah. Since two days 😉 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Ah yeah, these might not be reset once they have updates.

**Comment by rnystrom** [comment]
I think this is on hold til #1539 and we refactor models to hold all state. Right now having a mutable store of read client data is the issue. It needs to be in the model.

**Comment by BasThomas** [comment]
Pretty sure this is fixed?
