### ISSUE TITLE
Can not load inbox error

### ISSUE THREAD

**Issue by RishabhTayal** [GitHawkApp/GitHawk#1777]
I have been seeing "Can not load inbox" error when viewing the seen notifications.

![b78abe86-a4cf-484e-a042-132091d0b2af](https://user-images.githubusercontent.com/2100166/39399069-e3b8fa8e-4adc-11e8-9496-b2c734447d4a.png)
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.1 (1524679484)
Device: iPhone X (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
@RishabhTayal want to join TestFlight to help debug? Also what are your desktop notifications? Could you send a screenshot?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
Send me invite for TestFlight. 

This is my notifications on website. 

![GitHawk Upload by RishabhTayal](https://i.imgur.com/4J8NeAs.jpg)

**Comment by rnystrom** [comment]
@RishabhTayal are there any “odd” notifications? Security warnings, invites, etc?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
Yes I have security warnings in my notifications.

**Comment by BasThomas** [comment]
Ah, that's the issue. Closing in favor of #1776. Thanks for bringing it up again, @RishabhTayal!
