### ISSUE TITLE
Doesn't show issues 

### ISSUE THREAD

**Issue by RishabhTayal** [GitHawkApp/GitHawk#1778]
I am not able to see the issues when looking at a repository. It used to work for me. Recently broken. 

![84b1a823-8bd3-4bd2-a572-cf0d7a968b69](https://user-images.githubusercontent.com/2100166/39399082-239119f2-4add-11e8-91e8-210976435e14.png)

**Comment by BasThomas** [comment]
Hey @RishabhTayal, this is because of the repo moving to `GithawkApp/GitHawk`. If you search for that repository it should work as expected. :)
