### ISSUE TITLE
When posting a review comment fails, make sure the text does not get lost

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1783]
Is just posted a review comment which failed to be posted, and since the keyboard and input bar was already dismissed, I lost the whole post 😭.

Either we can have the message be posted with a “not sent” state (and a retry option) or at least be able to recover the text from the dismissed input bar somehow.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1524439576)
Device: iPad7,3 (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
I dig this. @BasThomas want to give it a shot? Maybe we just expose [this cache() function](https://github.com/GitHawkApp/MessageViewController/blob/master/MessageViewController/MessageViewController.swift#L141-L150) so we can manually do caching? Or maybe we move posting/caching out to its own thing entirely (w/in the client or something).
