### ISSUE TITLE
Cannot connect to GitHub

### ISSUE THREAD

**Issue by kennysmoothx** [GitHawkApp/GitHawk#1785]
Hello,

I just signed in the for the first time and authorized the app with my GitHub account however the home screen says "Cannot connect to GitHub"

I have twitter messages Ryan with screenshots. 

Not sure what to do, I have logged out and logged back in and still having the same problem,

Thanks!

---

UPDATE: FIXED by clearing "Security Vulnerabilities" notifictions on github.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.1 (1524679484)
Device: iPhone X (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Do you have any notifications about security vulnerabilities by any chance?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kennysmoothx** [comment]
Oh, yes I did!

I cleared that specific notification and the Inbox is working now :)

Thanks so much
