### ISSUE TITLE
„Crystal“ lang code not syntax highlighted

### ISSUE THREAD

**Issue by hanneskaeufler** [GitHawkApp/GitHawk#1786]
![GitHawk Upload by hanneskaeufler](https://i.imgur.com/C2M47lD.jpg)

The crystal code I have is not highlighted. Filenames are *.cr so highlight.js _should_ pick up on it, as it supports crystal (from my short investigation).

**Comment by BasThomas** [comment]
This is not GitHawk, I think this is Working Copy?

**Comment by hanneskaeufler** [comment]
>This is not GitHawk, I think this is Working Copy?

@BasThomas Aww man thanks you sir are of course correct. I switched back and forth between the two that I obviously got confused. Sorry for that!

**Comment by BasThomas** [comment]
No worries :)
