### ISSUE TITLE
Bitrise stuck with Watch App

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1787]
After merging #1781, Bitrise is stuck trying to code sign the TestFlight build. The dev build worked just fine, but now when I'm trying to archive, it fails w/:

```
Last lines of the Xcode's build log:
Check dependencies
Code Signing Error: No profiles for 'com.whoisryannystrom.freetime.watchkitapp.watchkitextension' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.whoisryannystrom.freetime.watchkitapp.watchkitextension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'WatchKit Extension' in SDK 'watchOS 4.3'
** ARCHIVE FAILED **
```

I've created + uploaded the WatchKit App and Extension provisioning profiles (both dev _and_ distribution) and nothing works. Running the `xcodebuild` command locally works fine, archiving w/in Xcode works fine... I'm stumped.

Does anyone have any advice? @viktorgardart maybe?

**Comment by viktorgardart** [comment]
Hmm, I actually have no idea, @KrauseFx maybe?

**Comment by rnystrom** [comment]
Er sorry meant @viktorbenei

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by viktorbenei** [comment]
My guess is a missing dev profile which exists on your Mac but did not upload it to Bitrise.io

Try https://github.com/bitrise-tools/codesigndoc it was designed exactly for this, to collect all required signing files 😉

PS you can also find the codesigndoc

**Comment by rnystrom** [comment]
@viktorbenei I actually tried the script and it outputs an empty directory 😕 I’ll check the Xcode logs.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by viktorbenei** [comment]
@rnystrom without logs it's really hard to tell - can you share the terminal/log output of codesigndoc?

**Comment by rnystrom** [comment]
@viktorbenei here's the `codesigndoc` output:

https://gist.github.com/rnystrom/93bcd2da6b0ad113f840fd0cc312c0b9

Archive and everything succeeds, but exports is empty.

<img width="415" alt="screen shot 2018-05-04 at 3 40 23 pm" src="https://user-images.githubusercontent.com/739696/39655950-832c5178-4fb1-11e8-8853-059a982588d7.png">

**Comment by KrauseFx** [comment]
Alright, let's keep the tagging game going. Maybe @joshdholtz knows more?

**Comment by rnystrom** [comment]
Wait I wonder if I need to select the dev profile when archiving... 🤔 ... will try and report back!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joshdholtz** [comment]
Totes out getting Mexican food right now so only able to look at things on my phone but seems like the profiles need to be selected in Xcode (if they aren’t) and bitrise (if they aren’t) since match and/or sigh isn’t being used 🤔

I don’t know much about bitrise but maybe match/sigh could be integrated into the Fastfile to do all the heavy lifting of certs and profiles so things don’t need to be manually done? ☺️

**Comment by rnystrom** [comment]
Looks like `codesigndoc` just needed dev profiles (not app store)

**Comment by joshdholtz** [comment]
BTW, I just downloaded GitHawk (I didn’t know it was a thing) and it is awesome 👌 Thanks for making this!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
Cool @joshdholtz 👌
See, we should do this tagging game more often @rnystrom 😄

**Comment by joshdholtz** [comment]
I think so! Hope to get tagged again by you all sometime soon 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
