### ISSUE TITLE
Viewing a specific issue crashes GitHawk

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#1788]
https://github.com/Microsoft/vscode/issues/5402

Reproducible: always

![GitHawk Upload by gingerbeardman](https://i.imgur.com/DZ9AUfN.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1524439576)
Device: iPhone 6s (iOS 11.3.1)
TestFlight: false
</pre>
</details>

**Comment by SD10** [comment]
@gingerbeardman Can you dig deeper using FLEX?

**Comment by gingerbeardman** [comment]
>@gingerbeardman Can you dig deeper using FLEX?

@SD10 happy to do whatever but I'll need directions/link because I'm not familiar with FLEX

**Comment by SD10** [comment]
No worries @gingerbeardman because FLEX doesn’t seem to be working on the most recent test flight 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Update to 1.19.1 for the fix 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
I didn’t get a test flight for 1.19.1 😕 Latest is 1.19.0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
It *is* available in the App Store. But that's not ideal of course.
