### ISSUE TITLE
Cannot connect to GitHub

### ISSUE THREAD

**Issue by hpurmann** [GitHawkApp/GitHawk#1789]
I used a token to access my account. The token has user and repo scope. It used to work before. Now I get no connection on the Inbox page anymore. I re-newed my token but no change.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.1 (1524679484)
Device: iPhone 6 (iOS 11.3.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hey @hpurmann, can you check if you have any vulnerability alerts in your notifications? This makes it so other notifications don't show up at the moment. Should be fixed soon!

**Comment by hpurmann** [comment]
Wow yes I did, thank you! I marked them as read and it is working again 👍
