### ISSUE TITLE
Image rendering issue

### ISSUE THREAD

**Issue by mackoj** [GitHawkApp/GitHawk#1790]
GitHawk don’t render image when they are in a table properly.

| GitHawk | GitHub |
| --- | --- |
| ![GitHawk rendering by mackoj](https://i.imgur.com/eZnJfnN.jpg) | ![GitHub renderin by mackoj](https://i.imgur.com/HNwaOLr.jpg) |

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.1 (1524679484)
Device: iPhone X (iOS 11.3.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Ya images in tables aren't supported at this time. Would take a little bit of elbow-grease to get this wired up, but not impossible.

**Comment by mackoj** [comment]
@rnystrom can you give me some pointers on how I can contribute to fix this ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@mackoj sure thing! This might be a little more complicated than I first thought. Let me know what you think!

Check out how we dynamically [download and resize image cells](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Issues/Comments/Images/IssueCommentImageCell.swift) in issues. We [cache](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Systems/ImageCellHeightCache.swift) the sizes as well.

Atm table cells are assumed to be all text. We precompute the sizes and put them in [these models](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Issues/Comments/Tables/IssueCommentTableModel.swift). Then we use [this cell](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Issues/Comments/Tables/IssueCommentTableCell.swift) to display the whole table. 

So we'd need to add a new model (or update the existing one) w/ image info, async load the image, and on load refresh the table.

Another tricky part is that the height/width of the image will change the size of the rows/columns of other cells.

**Comment by BrianLitwin** [comment]
I was trying to approach this issue and got a little blocked. It seems like [this file](https://github.com/GitHawkApp/GitHawk/blob/master/Pods/cmark-gfm-swift/Source/Block%2BTableRow.swift) in the cmark-gfm-swift pod would need to be modified to pass in images.. I'm not sure how to go about making modifications to project dependency. 

Also, would it be a good idea or overkill to refactor [the current cell](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Issues/Commit/IssueCommitCell.swift)  that displays the markdown table to use a ListAdapter/ListSectionController?

**Comment by rnystrom** [comment]
@BrianLitwin ya I think you’re right. Need to update that library as well. The nice part is we can do this in stages, and that library is setup with tests.

Not sure about refactoring to use IGListKit on that. What would we be trying to gain?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by billybooth** [comment]
The same issue applies to images in numbered lists.  Not a humongous deal, but it’d be nice to not be missing content altogether, even if the rendering isn’t an exact match.  Seeing something like this makes a user question every rendering he or she sees, and forces me to pop any rendering that looks odd into Safari to confirm that I’m not missing something relevant.

![6f2f71e2-e43e-45ca-ad9a-bae4895b411a](https://user-images.githubusercontent.com/20958170/47953761-dbedb800-df4f-11e8-9605-a24afbc56007.png)

Thanks for all of your diligent work on this project.  Is there any way we can donate to support this project?

**Comment by rnystrom** [comment]
@billybooth thank you! Re: donations, I appreciate the thought, but since this is a community operation, I’d rather donations go to a cause in GitHawks name.

http://hispanicfederation.org/unidos/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Also a review on the App Store is free and helps out the entire project 😉❤️
