### ISSUE TITLE
Can’t connect

### ISSUE THREAD

**Issue by else** [GitHawkApp/GitHawk#1793]
Hi, I can’t connect via oauth or personal token. The permissions and details are correct. 

Can you help me?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.1 (1524679484)
Device: iPhone SE (iOS 11.3.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Do you have any security vulnerability notifications by chance? What is the error you’re seeing?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by else** [comment]
Yes I do. Here’s what I see:

![8ae358a7-bfa6-407c-b6b6-b942b11db835](https://user-images.githubusercontent.com/77769/39841493-34c37c42-53e3-11e8-87dd-ec0be95ad206.png)

**Comment by else** [comment]
I can confirm marking them as read fixes the issue.

**Comment by rnystrom** [comment]
Ok great! We’re tracking this issue and will have a fix out ASAP!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
