### ISSUE TITLE
It’s saying cannot connect to GitHub

### ISSUE THREAD

**Issue by stephanieatrtr** [GitHawkApp/GitHawk#1801]
I just authorized the app and it can’t connect and load my inbox

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.1 (1524679484)
Device: iPhone X (iOS 11.3.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Do you have a security vulnerability notification on GitHub.com?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
