### ISSUE TITLE
Cannot load your inbox

### ISSUE THREAD

**Issue by jish** [GitHawkApp/GitHawk#1804]
Every time I open the app it says “cannot load your inbox”. That initial page does not work, but when I tap into “View All” then I do see notifications, and can comment on them. So everything else seems to work fine.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.1 (1524679484)
Device: iPhone X (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by jdisho** [comment]
Do you have a security vulnerability notification on GitHub? 😊


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jish** [comment]
No, I do not see any security messages on GitHub. Interestingly, now I can see a notification for this message in the app inbox and there is no error. Maybe it happens when the inbox is empty, or when the app is first launched? 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jish** [comment]
Now I see a message which says “inbox zero 🎉”. So everything appears to be working for me now. Maybe a fresh install combined with an empty inbox causes the failure? 🤔

Oh well, thanks for the help!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
