### ISSUE TITLE
Can't build project because of apollo 

### ISSUE THREAD

**Issue by ashleyng** [GitHawkApp/GitHawk#1806]
I did a fresh clone of the project and trying to build off master. I did the setup in the readme as well as the registering an OAuth app here https://github.com/GitHawkApp/GitHawk/blob/master/Setup.md

* when building the app, the apollo build step just removed everything in the API.swift file.
I tried altering the script to specify the temp file to be `temp.swift` instead of `$(mktemp)` to just get pass this step. 

* after I got it to generate the API.swift file, I'm getting errors `Use of undeclared type GraphQLMappable`, `Use of undeclared type Selection` and `Type ... does not conform to protocol GraphQLSelectionSet`

is there something I'm missing to get apollo-code-gen to work properly?

XCode 9.3 (9E145)
Macbook 10.13.3
npm: 3.8.6
node: 5.12.0

**Comment by jdisho** [comment]
Hey @ashleyng 
What global version of Apollo do you have? It should to be the same as the one in the GitHawk package file.
Also, have a look at this issue #1672, if it helps 😊

**Comment by ashleyng** [comment]
I'm still having the same issues. Even following https://github.com/GitHawkApp/GitHawk/issues/1672. I tried uninstalling the global apollo-codegen as well as installing the same apollo-codegen version globally (0.18.8). I think the problem might be because I have nvm installed on my machine and it's using the nvm version instead of the local bin one. that is really the only difference I notice from https://github.com/GitHawkApp/GitHawk/issues/1672 and my setup. 
![screen shot 2018-05-13 at 6 36 53 pm](https://user-images.githubusercontent.com/5355231/39972888-1f6b2b54-56dd-11e8-9855-124fb7eb5d92.png)

**Comment by jdisho** [comment]
Strage! 🙃
However, if you still cannot run GitHawk, I would suggest to reset the changes (git reset), remove the apollo script and run it again. @ashleyng

**Comment by ashleyng** [comment]
@jdisho I removed the apollo build step script and got the app up and running! Should I close this issue now or should there be something to look into with .nvm setups?

**Comment by BasThomas** [comment]
It would certainly be nice if we can prevent these issues in the future, so if you have any additions to help troubleshoot the setup process, that would be awesome!

**Comment by jdisho** [comment]
Well, I think is not necessary to add the apollo script in the repo if the API.swift is there. IMO, this could prevent this issue in the future.

**Comment by BasThomas** [comment]
That would mean you can’t develop any GraphQL related things anymore?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
