### ISSUE TITLE
Check for Testflight at runtime

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1809]
We can check if the app is running via Testflight at runtime (see [here](https://stackoverflow.com/questions/26081543/how-to-tell-at-runtime-whether-an-ios-app-is-running-through-a-testflight-beta-i)), is that something we'd want? That would allow us to debug release builds with FLEX.

**Comment by rnystrom** [comment]
I’m not sure it’s worth the hassle. The final build will only have 1-2 small bugs fixes prior to release.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
FWIW one of the reasons I didn't do this in the first place is the difference between compile time and runtime flags - With that check, we'd still need to include FLEX inside of the App Store build just a normal user wouldn't be able to access it.

Might not be a big deal either way, but that was my main reason :)

**Comment by BasThomas** [comment]
Ah that's a good point @Sherlouk!
