### ISSUE TITLE
Not able to comment

### ISSUE THREAD

**Issue by RishabhTayal** [GitHawkApp/GitHawk#1811]
Getting error when replying to comment.

https://photos.app.goo.gl/qz3ZxG14wMauQcXb8

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.20.0 (1526182208)
Device: iPhone X (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Closing in favor of #1784.
