### ISSUE TITLE
Milestone progress inverted again?

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1825]
![GitHawk Upload by BasThomas](https://i.imgur.com/2TNq77i.jpg)
![GitHawk Upload by BasThomas](https://i.imgur.com/Yx8yBuV.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1526771292)
Device: iPhone X (iOS 11.3.1)
TestFlight: true
</pre>
</details>

**Comment by jdisho** [comment]
I don't get the problem here 🙆‍♂️

**Comment by BasThomas** [comment]
On web it states the milestone is 0% completed; we show a 100% completion. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
There are only PRs in the milestone. See #1300

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Ahh right. Bummer!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
