### ISSUE TITLE
Handle unauthorized comments

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1827]
```json
{
  "data" : {
    "addComment" : null
  },
  "errors" : [
    {
      "path" : [
        "addComment"
      ],
      "message" : "Although you appear to have the correct authorization credentials,\nthe `tryswift` organization has enabled OAuth App access restrictions, meaning that data\naccess to third-parties is limited. For more information on these restrictions, including\nhow to whitelist this app, visit\nhttps://help.github.com/articles/restricting-access-to-your-organization-s-data/\n",
      "type" : "FORBIDDEN",
      "locations" : [
        {
          "line" : 2,
          "column" : 3
        }
      ]
    }
  ]
}
```

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1526915740)
Device: iPhone X (iOS 11.3.1)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
This just shows a generic “something went wrong” error, which is not very helpful. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Might be a tad excessive, but I wonder if we could make it so you can tap on the toast and see a full error message?

(Maybe TF only, but could also just be something everything gets for easier bug reports)

**Comment by BasThomas** [comment]
So #753? :)

**Comment by Sherlouk** [comment]
Ahh... well then! Great minds and all that

**Comment by rnystrom** [comment]
I’d be happy simply piping the error message to the toast in this case. Thoughts?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Seems like an OK start :)
