### ISSUE TITLE
Closed pull requests should not show merge buttons

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1828]
![GitHawk Upload by BasThomas](https://i.imgur.com/Wb7XQDr.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1526327365)
Device: iPad7,3 (iOS 11.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Would love help fixing this!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
