### ISSUE TITLE
Adding reviewers fails

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1829]
I think this whole API is broken. 😐

Also we show the author of the pull request, which can never be a reviewer as far as I know.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1526327365)
Device: iPad7,3 (iOS 11.3)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
![GitHawk Upload by BasThomas](https://i.imgur.com/CXzO6lZ.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
https://developer.github.com/v3/pulls/review_requests/#list-review-requests

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas “api” being our usage or the GitHub API?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya reproduces for me too. Anyone able to jump in and help fix?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
The GitHub API.

**Comment by rnystrom** [comment]
Hmm this was def working before, I think the networking refactor might have broken something

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrianLitwin** [comment]
I'm gonna take a hack at this.. shouldn't "issues" be "pulls" in the url? I think Assignees and Reviewers need diferent path components
