### ISSUE TITLE
Emoji reaction not working

### ISSUE THREAD

**Issue by RishabhTayal** [GitHawkApp/GitHawk#1830]
https://photos.app.goo.gl/9HoLpEiRFcj99BXPA

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.20.0 (1526182208)
Device: iPhone X (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
https://github.com/fastlane/fastlane/issues/12573

Emojis seem to have been disabled for one reason or another, wonder if we can pick up the error and see if there's an API to detect it. Might be the temporary lock feature?

**Comment by rnystrom** [comment]
Can anyone get the network response? Are you able to disable emoji on repos? Or specific issues?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Sorry I was being an idiot, sat here like "there's no reaction bar at the bottom" yh that's not how web version works 😂 ignore me

**Comment by rnystrom** [comment]
Error is same as #1872

![GitHawk Upload by rnystrom](https://i.imgur.com/yzgMMhV.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
