### ISSUE TITLE
Use solid icons instead of stroked in Tab Bar and other UI

### ISSUE THREAD

**Issue by zhubofei** [GitHawkApp/GitHawk#1836]
It's more consistent with Github's design language. I attached some example icons blew.
![bell](https://user-images.githubusercontent.com/770482/40588928-e233a7d0-61b2-11e8-86dc-9f865ed9d048.png)
![mailbox](https://user-images.githubusercontent.com/770482/40588929-e3aada8e-61b2-11e8-934f-79061801d638.png)
![search](https://user-images.githubusercontent.com/770482/40588930-e4ddd2e4-61b2-11e8-8d2b-03d8c155b19c.png)
![settings](https://user-images.githubusercontent.com/770482/40588931-e60717f2-61b2-11e8-8aad-3310413ff8f6.png)
![star](https://user-images.githubusercontent.com/770482/40588933-e8309e5e-61b2-11e8-8ae1-db88b1949720.png)

**Comment by BasThomas** [comment]
For what it's worth this was deliberately changed in #1275

**Comment by rnystrom** [comment]
Ya this is all intended

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
