### ISSUE TITLE
Support GitHub comment editing history

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1846]
You can see comment editing history on web now.
Taking a leap here but I think this is not available via the API yet, is it?

<img width="797" alt="screen shot 2018-06-01 at 17 52 33" src="https://user-images.githubusercontent.com/4190298/40850351-aac36e0a-65c4-11e8-852b-4bf544e95dfc.png">
<img width="677" alt="screen shot 2018-06-01 at 17 52 29" src="https://user-images.githubusercontent.com/4190298/40850350-aaa7dad2-65c4-11e8-8e53-8ef6f77fa211.png">
<img width="710" alt="screen shot 2018-06-01 at 17 52 37" src="https://user-images.githubusercontent.com/4190298/40850352-aaf108c4-65c4-11e8-9f3e-c3acea6c9dc1.png">

**Comment by Sherlouk** [comment]
Was about to create a new issue for this but GitHub's brand new "Related Issues" told me this existed 😆 Here are my notes, API now exists!

**Is your feature request related to a problem? Please describe.**
GitHawk currently supports displaying when a message has been edited but we can take this a step further by supporting GitHub's new comment history.

This can all be done with some additional GQL values on Issue and PullRequest nodes "userContentEdits":
https://developer.github.com/v4/object/usercontenteditconnection/

https://developer.github.com/v4/object/pullrequest/
https://developer.github.com/v4/object/issue/

**Describe the solution you'd like**
I believe we can just change the GQL query for loading an Issue/PR and pull in the edit information. I think we can take advantage of [ContextMenu](https://github.com/GitHawkApp/ContextMenu) to show (in chronological order) the name of the person who changed it and the time they changed it. Tapping on an option can show a very simple page with the diff!

**Describe alternatives you've considered**
Exact UI I believe is up for debate but I believe using the GQL API is the most appropriate given our current setup for loading issues and PRs.

**Additional context**
Believe this is a rather low priority suggestion as the value of this could be disputed for many!
