### ISSUE TITLE
Do not allow review request from PR author

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1850]

**Comment by BasThomas** [comment]
I guess this fails in the request, right? Why would GitHub return it as an option?

Otherwise we can just filter out the currently logged in (and active, in case of multiple logins) user?

**Comment by rnystrom** [comment]
They just return status 422 with an error message. Lame!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
