### ISSUE TITLE
Long press share not working with GitHawk signature

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1857]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528075587)
Device: iPhone X (iOS 11.4)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Oooh that’s an actual web view. I guess it doesn’t work out if the box?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
