### ISSUE TITLE
App needs OAuth whitelisting because Microsoft Github

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#1858]
![GitHawk Upload by gingerbeardman](https://i.imgur.com/8brfAwX.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528075587)
Device: iPhone 6s (iOS 11.4)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Is this something we do on GitHawk? Or is it up to each org to whitelist?

Looks like it’s [done by the org](https://help.github.com/articles/approving-oauth-apps-for-your-organization/), not the app. Someone will have to request access.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
