### ISSUE TITLE
Don’t set the notification # to 0 if loading fails

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1869]
If you have a certain amount of notifications and then open the app without connection, it will reset the counter to 0.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528075587)
Device: iPhone X (iOS 11.4)
TestFlight: true
</pre>
</details>

**Comment by TheCodeTalker** [comment]
you mean to say caching to do here??

**Comment by BrianLitwin** [comment]
@BasThomas  @TheCodeTalker The classes in charge of this issue are being updated in #1870 so prob re-check this issue after that PR is merged.

**Comment by TheCodeTalker** [comment]
Any update on this??

**Comment by BasThomas** [comment]
Yep, still up for grabs.

Re caching: no, that should not be needed.

**Comment by TheCodeTalker** [comment]
My understanding for this issue if open the app without a connection it should be zero only right because not able fetch the count. @BasThomas

**Comment by BasThomas** [comment]
When you open the app without a connection, it shouldn't update the badge count (also not to 0).

**Comment by TheCodeTalker** [comment]
ok make sense.  i will make a PR

**Comment by romankl** [comment]
is this one still a problem/ pr worth if no one is working at it?

**Comment by BasThomas** [comment]
Yep, go for it @romankl!
