### ISSUE TITLE
Limit autocomplete

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#188]
Currently if you type just a colon, you get a massive list of matches - First off we should probably only show the first 20? matches.

Secondly, maybe we should wait for at least one character before doing the search?

**Comment by rnystrom** [comment]
What's wrong w/ the massive list when the physical height is limited?

**Comment by Sherlouk** [comment]
Technically, nothing - but when compared to other autocomplete solutions there is usually a cap. 

There is also no order to them when using just a colon - You go from 🤣 to 🌸, 🚼  in the space of four!

Happy to close if not deemed an issue

**Comment by BasThomas** [comment]
It seems to also lock the UI for a bit now.

**Comment by Sherlouk** [comment]
Mm just checked it definitely takes a second to load the scroll view, presumably because of all the elements

**Comment by rnystrom** [comment]
I'll do a quick profile and see if there's something to improve

**Comment by Sherlouk** [comment]
One improvement in terms of ordering, would be if we keep track of the "category" field in the JSON file and order based on that? (Much like the Emoji Keyboard, how you swipe left to right through each category) So "People" (faces) all appear first, flags are grouped etc
