### ISSUE TITLE
Not receiving Push Notifications

### ISSUE THREAD

**Issue by pkrmf** [GitHawkApp/GitHawk#1888]
Wanted to ask first under what circumstances you get a push notifications. I have been mentioned in PRs and issues but I have never received push notifications.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528145114)
Device: iPhone X (iOS 11.4)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hey @pkrmf, we do not support push notifications (yet). Access to push notifications is used to display badges (the numbered red dot) on the app icon.
