### ISSUE TITLE
Checking file content view doesn't respect safe area

### ISSUE THREAD

**Issue by maniramezan** [GitHawkApp/GitHawk#1891]
As shown below, the view for checking file content, doesn't respect safe area so part of the content goes under the notch.

<img width="853" alt="screen shot 2018-06-30 at 5 32 43 pm" src="https://user-images.githubusercontent.com/2628592/42129340-3e8d84a4-7c90-11e8-89a7-aeb96f3b343e.png">

**Comment by rnystrom** [comment]
Oof, good find.

All that needs to happen is adjust for safe area insets in the [CodeView](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Views/CodeView.swift) or [view controller](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Repository/RepositoryCodeBlobViewController.swift).
