### ISSUE TITLE
Mark as read button still produces haptic after it has already been read

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1893]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1530022158)
Device: iPhone X (iOS 11.4)
TestFlight: true
</pre>
</details>

**Comment by maniramezan** [comment]
I also noticed it gives Haptic feedback when all messages are already read. What should be the feedback when no unread message exists? Should the button be disabled if no unread message exists?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I don’t think these buttons are enabled/disabled; they work with locations. That said, we should check the trigger and omit the haptic if it has no unreads. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
That logic is in NotificationCell.swift. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maniramezan** [comment]
Sounds good. Thank you for your help. I'll look into it.
