### ISSUE TITLE
 Watch Support

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#190]
Genuinely think this is the sort of app that I would love to have on an Apple Watch with the ability to quickly see notifications

**Comment by rnystrom** [comment]
I love it. LONG way off, but would be super cool for a basic activity overview.

**Comment by rnystrom** [comment]
Reviving, anything cool we could do here? Tbh I don't use **any** watch apps, just the complications. Maybe we could do something there?

**Comment by Sherlouk** [comment]
Gonna join the gang next month when I get my series 3 😃 

I think the main thing I'd like to see at a glance is how many unread notifications I have.

Obviously we could go insane and make it so you can actually see messages and use canned responses (different card) to reply - Much like how I see iMessages dealing with it

**Comment by BasThomas** [comment]
Just like @rnystrom, I am not using any 3rd party apps on the Watch. I think a complication would make sense as a first step. 

Also curious how the Series 3 will perform; that might make it more interesting to look into building an app too. Think it should focus on something (eg. replying with saved replies) without trying to recreate a lot of the main app’s features.

**Comment by rnystrom** [comment]
Btw, I'm basically open to anything here. If someone wants to hack at it I'll probably accept anything. I don't think I'll spend any time on this, but could be a neat side-kick. The today and home screen widgets are probably a lot more impactful.

**Comment by rnystrom** [comment]
So this might actually help w/ App Store ranking. Might be worth hacking together something stupid simple just to have it...

**Comment by Sherlouk** [comment]
Fun Fact: My Apple Watch went to dispatched today 😄 24th Oct and I'll be all over watch development!

The more Apple things you support the more they feature you, had first hand experience of that

**Comment by BasThomas** [comment]
tvOS?!

**Comment by Sherlouk** [comment]
I don't watch TV often, but when I do, it's to check my GitHub notifications 😂

**Comment by Sherlouk** [comment]
So what were people actually thinking of having for Apple Watch support?

A complication that just says how many unread notifications you have?

**Comment by BasThomas** [comment]
I would probably not use more than a complication to be honest.

**Comment by Sherlouk** [comment]
As a starting point it'll give us enough structure to at least get notification information to the watch, as well as background polling to get information

It's definitely a start!

**Comment by Sherlouk** [comment]
😁 I love it when things arrive early 😁😁

**Comment by BasThomas** [comment]
No pic no prove 😉 Enjoy the watch!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
![image](https://user-images.githubusercontent.com/15193942/31830858-680ff7c4-b5b9-11e7-9364-87377ac107a9.png)

🤷‍♂️

**Comment by rnystrom** [comment]
Oh shiiiiiitt! Those rings are pretty dope. Honestly that alone is worth shipping. Are there any rules around shipping only a complication? Does there have to be an app too?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
So yeah I was just messing with how we can display the information. There's about 7 different display modes ("families") we can support (this is just the small modular one).

You have to have an app if you ship a complication (it opens automatically when you tap on the item). We could just have a screen which is like "Open App" or something (and deeplinks to the notifications page).

That right there is using fixed data, need to follow RayWenderlich's tutorial on watch connectivity to get notification info across.

I was hoping we could customise exactly how complications look, but from what I can tell you have to use one of about 8 different templates (image, text, combination of the two in different formats). The above is a bit of a trick, using CoreGraphics to take the outer bit of the app icon and then draw the text overlay (notification count). Text size is dynamic, and centered. (Get's smaller with bigger numbers!)

Unfortunately though we can't have different colours for the ring vs text (would've been amazing if we could!)

Using a different template we could just put the logo above the number? (That way we could have two colours). Or do we like this design? Really just playing around to see what's possible! Obviously when it's in the app we have a lot more creative control! -- I'd quite like this complication though, but again (as I've complained about before) counting how many people mention me rather than any notification! 😅  - Could be an option though!

**Comment by rnystrom** [comment]
For sharing code, we probably want to look into migrating the networking + model stuff into a shareable framework to do this "right".

Also move authentication/tokens into app group containers 😬

**Comment by Sherlouk** [comment]
Would also need the minimal persistency stuff in there for notifications as well so the number is actually correct. I'd say this is pretty dependent on #620 as well

**Comment by rnystrom** [comment]
Claiming this to experiment w/ App Store ranking in the next release. Here's the app that I have in mind:

- Open to list of notifications grouped by repo
  - Show repo name, number of notifications for repo, and button to mark them read (check mark)
  - Should show notification type (issue, PR, etc)
  - _stretch_: Get notification status. Requires breaking out V3+gql hack into shared lib.
- Tapping cell shows list of all that repo's notifications w/ button to mark read
  - Long press on notification to show option to unsubscribe
- Handle not-logged in state w/ a view saying you need to sign into GitHub via GitHawk app

**Comment by rnystrom** [comment]
Have a local branch w/ extension + cocoapods refactor setup and building. Just a matter of slapping it together. Very curious how/if this impacts App Store ranking!

**Comment by BasThomas** [comment]
Closing this; any idea if this had any effect on ranking?

**Comment by rnystrom** [comment]
@BasThomas nothin 😭

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
😔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
