### ISSUE TITLE
preferredContentSizeCategory called on background thread 

### ISSUE THREAD

**Issue by BrianLitwin** [GitHawkApp/GitHawk#1907]
Repeat of #1225.. as stated in original thread, not an urgent issue, just throwing a "Main Thread Checker: UI API called on a background thread" warning in XCode. 

The preferredFont property that's causing the warning is accessed [here](
https://github.com/GitHawkApp/GitHawk/blob/3028081c3c0d5b052ad6dc16f916208ff9d6517b/Classes/Notifications/NotificationCell.swift#L28) and then [here](https://github.com/GitHawkApp/GitHawk/blob/3028081c3c0d5b052ad6dc16f916208ff9d6517b/Classes/Notifications/NotificationCell.swift#L22) in NotificationCell, from [this function](https://github.com/GitHawkApp/GitHawk/blob/3028081c3c0d5b052ad6dc16f916208ff9d6517b/Classes/Notifications/CreateNotificationTitle.swift#L22).

**Comment by BrianLitwin** [comment]
yeah that must be it, calling NotificationCell.inset anywhere on the main thread silences the warning

**Comment by ismetanin** [comment]
@BrianLitwin @rnystrom 
Fixed #2037
