### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by kijiro92** [GitHawkApp/GitHawk#1922]
We are unable to connect to GitHub

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528145114)
Device: iPad Pro (iOS 11.4)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
I think that might have been [GitHub](https://status.github.com/messages) servers having some issues.

**Comment by kijiro92** [comment]
👍🏻

**Comment by rnystrom** [comment]
If you check the settings tab, there’s a GitHub API status check.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
![GitHawk Upload by rnystrom](https://i.imgur.com/KrfeUsX.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kijiro92** [comment]
Thank you for the tech support! Cool app and great service!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
