### ISSUE TITLE
Make X on close menu item red

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1923]
Requires adding color to items struct

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1531698972)
Device: iPhone X (iOS 11.4)
TestFlight: true
</pre>
</details>

**Comment by jdisho** [comment]
Sorry, I was just testing. 😅 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom Is this not already red?
