### ISSUE TITLE
Feature request: Limit a user's inbox to their own assignments/mentions

### ISSUE THREAD

**Issue by jbraem** [GitHawkApp/GitHawk#1924]
As mentioned in #287 I would love the ability to filter the inbox/notifications to only include issues that I'm personally assigned to or mentioned in.

My company uses Github Issues across several projects, and a lot of our team's activity isn't directly relevant to me. In cases like this, an unfiltered inbox makes for a low signal-to-noise ratio.

**Comment by rnystrom** [comment]
Love it! Does anyone know if we would achieve this via API params? Or do we have to manually do some filtering?

Also omg I want the notifications API on GraphQL so bad 😭

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Would love this as well

**Comment by BasThomas** [comment]
This is in now :)
