### ISSUE TITLE
Push Notifications with local push?

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1928]
The biggest ask I keep seeing is push notifications, however I _really_ don't want to setup a server to send APNs for multiple reasons: I don't want to build/maintain it, and I also don't want to store people's info off of their device (esp a token!).

I've hacked push notifications before using local push. We already have a background job to update the app badge. We could update the local cache with what has been "pushed" before, and for new notifications just queue a local push notification instead.

What do you think? Should we try it?

**Comment by rodrigobdz** [comment]
That would be great! I‘m missing this feature as well.
