### ISSUE TITLE
Missing space when replying to issue comment

### ISSUE THREAD

**Issue by rodrigobdz** [GitHawkApp/GitHawk#1930]
When replying to a comment in an issue, the text is quoted and you are replying to is automatically pre-filled in the response.
A space after the person you are replying to would be nice, to save the user some time.

![Missing space between comment and person by rodrigobdz](https://i.imgur.com/h27mEyj.jpg)

**Comment by rnystrom** [comment]
All great ideas! Would accept both PRs 😄

**Comment by rodrigobdz** [comment]
>All great ideas! Would accept both PRs 😄 

@rnystrom could you give me a hint where should I make such change?

**Comment by rnystrom** [comment]
Actually @jdisho added the reply feature, I’m sure he can point out where might be best!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
