### ISSUE TITLE
Add “clear” button on all menus

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1942]
Labels, milestone, people

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Maxador** [comment]
I would like to tackle this issue. Is there more indication on what the “clear” button should look like and how can I access those views with some relevant data?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrianLitwin** [comment]
@Maxador you do need permissions to get the [ContextMenu](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Issues/IssueManagingContextController.swift) to show up on the screen. For a quick hack if you just want to mess with it/ see what it looks like, return `[ .labels, .milestone, .assignees ]` [in this method](https://github.com/GitHawkApp/GitHawk/blob/b70e2649a01d3aa8f0ad93ad60a303b666aa1450/Classes/Issues/IssueManagingContextController.swift#L83) and you'll get the button to show up on Issues. 

Prob want the clear button to look similar to the current done button, possibly in the upper left hand corner. Although, currently Assignees has a leftHand nav bar item so maybe others have ideas about what the UI should look like? 

The done button is added in viewDidLoad() of each VC through [this method](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/View%20Controllers/UIViewController+MenuDone.swift), so you can prob look there for styling cues. 

I could be wrong but I don't thinkkk you need to worry about sending any GraphQL mutations or network requests after clear is pressed or the context menu is dismissed, but you probably do need to re-set the selection state of the SectionControllers and update the UI.

**Comment by rnystrom** [comment]
@BrianLitwin 🔥
