### ISSUE TITLE
Read animation

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1944]
Would love a cool animation when marking stuff read. Maybe a swipe fade effect, or particle explosion out of the read button. Idk, something fun.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1532006598)
Device: iPhone X (iOS 11.4)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
@rnystrom Where in the project do the cells get updated (dimmed out)?

**Comment by rnystrom** [comment]
@Huddie `NotificationCell.swift` where we manually change some view alphas.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
![slide_animation](https://user-images.githubusercontent.com/10662471/42971208-7f8b5f6a-8b79-11e8-8824-355eaff5b7f9.gif)

I wouldn't say this is fun but if its a bit nicer of way to fade.

**Comment by rnystrom** [comment]
Very cool! I was gonna also explore a circular `CAShapeLayer` mask emanating from the read button.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom Oh that would probably looks great since the animation would appear to emanate from the tap! I did a similar thing with CAShapeLayer mask here. Not sure if i did it the best way possible so im excited to see your circular one.
