### ISSUE TITLE
Whitelist the GitHawk app OAuth Access

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1945]
<img width="433" alt="screen shot 2018-07-19 at 21 52 54" src="https://user-images.githubusercontent.com/4190298/42966654-2dff3ae8-8b9e-11e8-987b-52cbe56beccf.png">

Seems like you can't comment / interact with this repository from the app as it seems some OAuth restrictions were activated 😬

**Comment by rnystrom** [comment]
Whaaaat. Why don’t I get this? Cause I’m the owner?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Wait, it works from my phone. Did you change something? I didn’t do anything different on the simulator as far as I know. Logged in normally, no access token. 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Don’t think so. 🤷‍♂️
Might investigate a bit more later. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
