### ISSUE TITLE
Small tweak on tab bar icons

### ISSUE THREAD

**Issue by zhubofei** [GitHawkApp/GitHawk#1952]
![simulator screen shot - iphone 8 - 2018-07-20 at 14 28 11](https://user-images.githubusercontent.com/770482/43019040-8eb5fcec-8c29-11e8-97e6-a9bc03285c35.png)
![simulator screen shot - iphone 8 - 2018-07-20 at 14 28 15](https://user-images.githubusercontent.com/770482/43019046-92016a1c-8c29-11e8-89e9-4becbd1e2b8d.png)
![simulator screen shot - iphone 8 - 2018-07-20 at 14 28 17](https://user-images.githubusercontent.com/770482/43019047-9211873a-8c29-11e8-97b2-5f87c41494fc.png)
![simulator screen shot - iphone 8 - 2018-07-20 at 14 28 20](https://user-images.githubusercontent.com/770482/43019048-92234d26-8c29-11e8-8d29-89d3ecbd491a.png)

**Comment by zhubofei** [comment]
Less sharp edges and same stroke-thickness. Bring them closer to the Outlook style in #1271

**Comment by Huddie** [comment]
Just keep bookmark consistency (issue #1950)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Is the font heavier too?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zhubofei** [comment]
@rnystrom The font is the same. iPhone8 simulator might be the reason why it looks heavier.

**Comment by Huddie** [comment]
@zhubofei @rnystrom If you look at Outlook or Twitter they remove the text from the Tabbar. I think this could allow for a cleaner look in GitHawk as well.

**Comment by rnystrom** [comment]
I'm gonna make a call to leave them as is. Don't feel persuaded that this is the right change.

**Comment by zhubofei** [comment]
@rnystrom I agree! Icons are also of lower priority compare to feed layouts. These tweaks can wait until the layouts are stable 👍
