### ISSUE TITLE
No network crash in Issue VC

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#1954]
Steps to reproduce:
1) Open app with good network connection (Inbox should load)
2) Turn airplane mode on
3) Navigate into an open issue. 

[Crash should occur]
iPhone 6s running 11.4.1

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1532006598)
Device: iPhone 6s (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
I can't seem to reproduce this :(

**Comment by BasThomas** [comment]
Could reproduce, but not on the simulator. Can't find a crash log in Crashlytics. Ryan?

**Comment by rnystrom** [comment]
Awesome, wanna keep that crash rate at 0. I’ll see if this is in the logs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom Any update on the logs here?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Nope, haven’t seen it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
