### ISSUE TITLE
Remove text from tabbar

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#1956]
The tab icons are pretty self explanitory and other apps (Twitter, Outlook, Facebook, Instagram) have already started removing the text for a cleaner look.

**Comment by BasThomas** [comment]
We could experiment with this, but I'm not too big of a fan.

**Comment by rnystrom** [comment]
- We could def give it a try. I’d say only if we can also slim the size of the bar

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
- We could def give it a try. I’d say only if we can also slim the size of the bar.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom  ^ duplicate posts. Is this that a GitHawk error? 

Also sounds good. I have no idea how it will look but outlook was mentioned so I though id suggest it

**Comment by rnystrom** [comment]
Might have been 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Making a call to leave them as is
