### ISSUE TITLE
Bookmark icon should be right-aligned

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1958]
Too much space between the icons

![GitHawk Upload by rnystrom](https://i.imgur.com/duCrcT2.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1532006598)
Device: iPhone X (iOS 11.4)
TestFlight: true
</pre>
</details>

**Comment by ashleyng** [comment]
I was taking a stab at this, and should this only affect the `IssueViewController` or should it also include the icon on the `RepositoryViewController`?

**Comment by rnystrom** [comment]
@ashleyng both please! Mind knocking out the repo VC too?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ashleyng** [comment]
yep! I can do that!

**Comment by BasThomas** [comment]
Fixed in #2255 right?
