### ISSUE TITLE
Use GH MD rendering

### ISSUE THREAD

**Issue by vihanb** [GitHawkApp/GitHawk#1962]
I don’t know exactly how Markdown rendering is being done but GitHub offers a REST [markdown API](https://developer.github.com/v3/markdown/#render-an-arbitrary-markdown-document) and the [CSS](https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/github-markdown.css) is also publicly available so with that the Markdown could look more like the GitHub website.

**Comment by rnystrom** [comment]
That requires using webviews to render all Markdown. We've done _extensive_ work to make our Markdown rendering almost completely native (fast!!). We definitely looked into this when we started 😉
