### ISSUE TITLE
unable to set any milestones for my project / Unable to decode milestones without a description

### ISSUE THREAD

**Issue by nurpax** [GitHawkApp/GitHawk#1978]
I’m unable to set any miles for my project https://guthub.com/nurpax/petmate

The UI always just gives an error. Posted screencap in a comment.

**Comment by nurpax** [comment]
Screencap: https://youtu.be/3Je4zgixw-o

Do the milestone names matter? My project has 0.1 and 0.2.

**Comment by nurpax** [comment]
I added the mikestones in github web after I had syncd githawk.

**Comment by BasThomas** [comment]
The milestone names should not matter, but thanks for sharing them regardless. It could be that some decoding fails. Do you only have issue with adding milestones? Can you add assignees / comment / do other things on the project?

**Comment by nurpax** [comment]
comments, labels and assignees work well for me

**Comment by rnystrom** [comment]
@nurpax are you using the beta version? We could inspect the network response if so.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nurpax** [comment]
i’m using the app store version 1.21.0. i can try beta toi if that helps. that’s a separate entry in the app store or how do i get it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@nurpax you can DM me on Twitter with your email and I can send the beta 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nurpax** [comment]
Done.

**Comment by nurpax** [comment]
Got beta running. Same problem w/ milestones. (which I guess was expected)

**Comment by BasThomas** [comment]
Awesome, can you three-finger tap (tap once with three fingers) and check the menu > network history?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nurpax** [comment]
They're all HTTP 200 OK (5 requests)

**Comment by nurpax** [comment]
`[
  {
    "id" : 3514116,
    "description" : null,
    "open_issues" : 6,
    "state" : "open",
    "created_at" : "2018-07-22T13:29:11Z",
    "labels_url" : "https://api.github.com/repos/nurpax/petmate/milestones/1/labels",
    "url" : "https://api.github.com/repos/nurpax/petmate/milestones/1",
    "node_id" : "MDk6TWlsZXN0b25lMzUxNDExNg==",
    "closed_issues" : 6,
    "title" : "0.1",
    "creator" : {
      "id" : 297823,
      "organizations_url" : "https://api.github.com/users/nurpax/orgs",
      "received_events_url" : "https://api.github.com/users/nurpax/received_events",
      "following_url" : "https://api.github.com/users/nurpax/following{/other_user}",
      "login" : "nurpax",
      "avatar_url" : "https://avatars0.githubusercontent.com/u/297823?v=4",
      "url" : "https://api.github.com/users/nurpax",
      "node_id" : "MDQ6VXNlcjI5NzgyMw==",
      "subscriptions_url" : "https://api.github.com/users/nurpax/subscriptions",
      "repos_url" : "https://api.github.com/users/nurpax/repos",
      "type" : "User",
      "html_url" : "https://github.com/nurpax",
      "events_url" : "https://api.github.com/users/nurpax/events{/privacy}",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/nurpax/starred{/owner}{/repo}",
      "gists_url" : "https://api.github.com/users/nurpax/gists{/gist_id}",
      "gravatar_id" : "",
      "followers_url" : "https://api.github.com/users/nurpax/followers"
    },
    "html_url" : "https://github.com/nurpax/petmate/milestone/1",
    "number" : 1,
    "updated_at" : "2018-07-26T22:35:52Z",
    "due_on" : null,
    "closed_at" : null
  },
  {
    "id" : 3514117,
    "description" : null,
    "open_issues" : 4,
    "state" : "open",
    "created_at" : "2018-07-22T13:30:01Z",
    "labels_url" : "https://api.github.com/repos/nurpax/petmate/milestones/2/labels",
    "url" : "https://api.github.com/repos/nurpax/petmate/milestones/2",
    "node_id" : "MDk6TWlsZXN0b25lMzUxNDExNw==",
    "closed_issues" : 0,
    "title" : "0.2",
    "creator" : {
      "id" : 297823,
      "organizations_url" : "https://api.github.com/users/nurpax/orgs",
      "received_events_url" : "https://api.github.com/users/nurpax/received_events",
      "following_url" : "https://api.github.com/users/nurpax/following{/other_user}",
      "login" : "nurpax",
      "avatar_url" : "https://avatars0.githubusercontent.com/u/297823?v=4",
      "url" : "https://api.github.com/users/nurpax",
      "node_id" : "MDQ6VXNlcjI5NzgyMw==",
      "subscriptions_url" : "https://api.github.com/users/nurpax/subscriptions",
      "repos_url" : "https://api.github.com/users/nurpax/repos",
      "type" : "User",
      "html_url" : "https://github.com/nurpax",
      "events_url" : "https://api.github.com/users/nurpax/events{/privacy}",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/nurpax/starred{/owner}{/repo}",
      "gists_url" : "https://api.github.com/users/nurpax/gists{/gist_id}",
      "gravatar_id" : "",
      "followers_url" : "https://api.github.com/users/nurpax/followers"
    },
    "html_url" : "https://github.com/nurpax/petmate/milestone/2",
    "number" : 2,
    "updated_at" : "2018-07-26T20:51:18Z",
    "due_on" : null,
    "closed_at" : null
  }
] `

**Comment by nurpax** [comment]
Could it be due to the description field being "null" in milestones?  I'll try to set a milestone description and see if that fixes it.

**Comment by nurpax** [comment]
Yeah, I think that was the problem.  I added a description in github to all my milestones and it works now.

I think it'd make sense to turn null to maybe an empty string.  Editing the milestone description is hidden behind an "Edit milestone" button that I never clicked on before.

**Comment by BasThomas** [comment]
Awesome, I think we can fix this in the decoding of milestones! 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
