### ISSUE TITLE
Resign keyboard when tapping manage button

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1979]
Kind of annoying to have the kb flying around

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1532006598)
Device: iPhone X (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
If nobody has done this one already I don’t mind doing it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Huddie all yours!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Just to make sure - Manage button is the blue hamburger button?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Huddie yup!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
