### ISSUE TITLE
Inbox always empty

### ISSUE THREAD

**Issue by BBarone1** [GitHawkApp/GitHawk#1980]
I get my notifications through github per day, but none show up here. My organization has granted access. Please let me know if there is anything else I need to do. 

Thanks

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528145114)
Device: iPhone X (iOS 11.4)
TestFlight: false
</pre>
</details>

**Comment by BBarone1** [comment]
hey @rnystrom , thanks for following up. here's a screenshot of my notifications on github:

<img width="742" alt="screen shot 2018-07-26 at 4 38 39 pm" src="https://user-images.githubusercontent.com/21130918/43287248-76d5c8dc-90f2-11e8-81e4-5bc1e93f57c4.png">

^i'm guessing I need to enable web notifications?

re: GitHawk settings -> review access - the relevant organization has a green check next to it for approval

**Comment by rnystrom** [comment]
@BBarone1 sorry I meant your actual notifications list. The little bell in the top right.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Or github.com/notifications :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BBarone1** [comment]
Ah got it - turns out turning on those checkboxes was the key. Notifictions now pulling through to GitHawk. 

Thanks for the help, marking this resolved. Closing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah makes sense, you'd need web alerts for them to be available via the API. :)
