### ISSUE TITLE
Router infra for better navigation and deep linking

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#1981]
Want to kick off a discussion about routing. I’d like to tackle this in the next-next release. Some goals I had in mind:

- Decouple view controllers from nav events
  - No more push/dismiss etc. make this more declarative
- Enable string-based routing with data
  - Basically URL paths with params.
- Support app deep linking
  - I’d actually like GitHawks routing to be its own framework so other apps can install the kit for typed navigation into GitHawk
- Support complex and custom transitions
  - Nav controllers, tab selection, split VC, present/dismiss

I’ve been thinking about building this from scratch, but maybe there is an _awesome_ lib that does this all already.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1532006598)
Device: iPhone X (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
This still valid?
