### ISSUE TITLE
Inconsistency between GitHub and GitHawk about merging a pull request 

### ISSUE THREAD

**Issue by jdisho** [GitHawkApp/GitHawk#1984]
Apparently in **GitHub** I cannot merge a PR, but in **GitHawk** looks mergeable.

**GitHawk:** 
![img_0304](https://user-images.githubusercontent.com/8223362/43315394-23c23906-9196-11e8-8922-f3b207da8d8d.jpg)

**GitHub:**
<img width="712" alt="screen shot 2018-07-27 at 12 04 00" src="https://user-images.githubusercontent.com/8223362/43315397-27cc2728-9196-11e8-9d3c-e6b1eb59bc13.png">

**Comment by BasThomas** [comment]
I guess we don’t take approvals into account. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
We should probably use the endpoint to check if we can merge after all. 😢

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrianLitwin** [comment]
@BasThomas is this the same?

https://developer.github.com/v4/reference/enum/statusstate/

**Comment by rnystrom** [comment]
See #1866

Just need to update GQL to use merge info preview and add the feature

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
