### ISSUE TITLE
UIWebBrowserView has black vertical line on the right

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1985]
![img_0060](https://user-images.githubusercontent.com/4190298/43342367-c0a315d2-91e2-11e8-915d-5eb8c2188621.jpg)
![img_0061](https://user-images.githubusercontent.com/4190298/43342368-c0b85e88-91e2-11e8-98c8-6cc14a644375.PNG)
![img_0062](https://user-images.githubusercontent.com/4190298/43342369-c0ce67aa-91e2-11e8-9535-54ec7fc5e431.PNG)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1532703791)
Device: iPad7,3 (iOS 12.0)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Running the iOS 12 beta, it *could* be that.

**Comment by rnystrom** [comment]
Any chance you can use flex and tap on it? We can prob just set a views bg to white.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
It is part of this `UIWebBrowserView` (see image) that has no subviews. So it’s part of that. Its parent is a `_UIWebViewScrollView`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
