### ISSUE TITLE
Issues that can't be reopened still show a reopen manage button

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1992]
Had this in https://github.com/apple/swift-evolution/pull/832. Not sure if we can figure this out via the API? If not, I guess we can close this / potentially improve the error.

Request url: https://api.github.com/repos/apple/swift-evolution/issues/832 (PATCH)

Request body:

```
{
  "state" : "open",
  "access_token" : "xyz"
}
```

Response body:

```
{
  "message" : "Validation Failed",
  "errors" : [

  ],
  "documentation_url" : "https://developer.github.com/v3/issues/#edit-an-issue"
}
```

Status code: `422 client error`

Shown error: `Something went wrong.`

**Comment by rnystrom** [comment]
@BasThomas why aren't you able to reopen it?

Oh you're the author, but not a collaborator. Is that why?
