### ISSUE TITLE
Increase “view files” heigt / tap area

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#1996]
A bit hard to hit right now 

![GitHawk Upload by BasThomas](https://i.imgur.com/xH2bNp5.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1532703791)
Device: iPhone X (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by BrianLitwin** [comment]
@rnystrom how'd you fix this one?
