### ISSUE TITLE
Leave a comment input section feels a bit cluttered 

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2005]
This new update shrunk the input section of the issue page and changed the send button.

1) I personally am a bigger fan of the old send button
2) The input section feels a bit cramped now that its shrunk, some padding should be added between the textfield and the options section (preview/@/bold...etc), like it used to have.
Example (Idk how to do that cool UI measure/outline stuff):

![img_1693](https://user-images.githubusercontent.com/10662471/43374911-06e45170-9380-11e8-8d57-945e806bf7c8.jpg)

**Comment by rnystrom** [comment]
Agreed, it’s really tight. I’ll give it some more spacing 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom Cool! Awesome updates this weekend! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah, definitely too small of a hit area at the moment



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
