### ISSUE TITLE
Don’t show action button if there are no available actions

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2009]
![GitHawk Upload by BasThomas](https://i.imgur.com/WUYWZkc.jpg)

https://github.com/WeTransfer/WeScan/issues/43

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1532907001)
Device: iPhone X (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
😱

Great find, lol this looks so goofy

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
