### ISSUE TITLE
Choosing double tap emoji

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2013]
Previously posted under a different account. Trying to keep it on my personal account so here it is again.

[Feature]
I just learnt about the double tap to like feature. Pretty cool.

Some people like hearts, some like other emojis. Maybe users can set which emoji the double tap will add.

I’d love to try and get this thing working if the community wants it.

Sent with GitHawk

**Comment by rnystrom** [comment]
Love it!! Would be a great setting

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
KK i'll see what I can do :)

**Comment by Huddie** [comment]
@rnystrom Heres what I got. 

![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/10662471/43438426-2db81700-945c-11e8-8712-cc6a52f7f6c1.gif)

**Comment by BasThomas** [comment]
I think there's an issue for this already, but I think it would help if we clean up the settings a bit. Then we could add a "double tap on a comment to leave this reaction" or similar below the cell.

**Comment by Huddie** [comment]
@BasThomas Which issue?

**Comment by BasThomas** [comment]
https://github.com/GitHawkApp/GitHawk/issues/323

**Comment by Huddie** [comment]
@BasThomas Isn't that issue about cleaning up/redoing the settings page?

**Comment by BasThomas** [comment]
Yeah that's what I was referring to.

> Also which cell are you refering to?

The one you added could use that description is what I was thinking.

**Comment by BasThomas** [comment]
I know. Sorry, I should be more clear. You mentioned that you only just realised that you can double tap to leave a 👍 reaction. I can imagine that someone looking at this “Set Default Reaction” setting does not understand how that can be used. If that cell would have a footer that explains you can leave this reaction by double-tapping a comment, that would help give some context to the specific setting.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jazzbox** [comment]
Would be great™ if one could choose “none” too to disable the double click. Very often I accidentally triggered this function!

BTW, one way to do this is to tap down and hold for several seconds and then lift and immediately tap again. This will be interpreted as a double click even when the two tap down events have seconds between them. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@jazzbox I’ll add that!
@BasThomas Ahhhh I understand what you meant now. I agree. 

I’ll make these changes!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
We could also look at fixing these issues @jazzbox mentioned though :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
