### ISSUE TITLE
New Issue posted from incorrect account

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2014]
I'm pretty sure this is an issue, but would love for someone to confirm.

I have 2 accounts set up on githawk. I was on one of them, switched to the other and added a new issue. That issue was posted under the other account.

Possibly not switching over accounts properly?

**Comment by rnystrom** [comment]
This was when reporting an issue for GitHawk? Or using the “new issue” UI on repos?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Report Bug pretty sure. Deff the New Issue UI

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I think I hit this before too

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
