### ISSUE TITLE
Adding emoji to last comment when keyboard present bug

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2015]
Steps to repoduce:

1. Swipe down to bottom comment
2. Make sure keyboard is showing (With bottom comment above it)
3. Tap the smiley face
- Keyboard should resign & emoji picker appears (Bottom comment will be hidden now) -
4. Swipe to show bottom comment
- The emoji bar on the bottom comment should not appear - 

I'll try getting a video/pic up soon

**Comment by rnystrom** [comment]
@Huddie would love a video! Following your steps, the UI is maybe a little whacky w/ the offset after the kb resigns, but not sure how big a deal this is.

**Comment by Huddie** [comment]
I’ll try getting a gif soon (sorry about the delay) here are a few snaps.

![GitHawk Upload by Huddie](https://i.imgur.com/OTAgOyk.jpg)![Notice no emoji symbol by Huddie](https://i.imgur.com/AnhgFrU.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Aha! I can reproduce this now. Maybe we tackle this with #2031

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom Makes sense. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
