### ISSUE TITLE
iOS 12

### ISSUE THREAD

**Issue by movdev12** [GitHawkApp/GitHawk#2019]
Please make the app more stable on iOS 12

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528145114)
Device: iPhone 8 (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hey @movdev12 — are there any specific issues you're seeing?

**Comment by rnystrom** [comment]
+1 what is unstable about it? I haven’t used it on iOS 12

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by movdev12** [comment]
Hi my iPad on GitHawk is slow o
