### ISSUE TITLE
Reloading notifications does not remove selection state

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2021]
The cell that was previously selected will stay selected

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1532907001)
Device: iPad7,3 (iOS 12.0)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Is it supposed to? If you select a cell and view the issue, then reload, you're still viewing the issue and it should be selected.

Am I missing something?

**Comment by BasThomas** [comment]
Fair enough!
