### ISSUE TITLE
Make sidebar collapsible on iPad

### ISSUE THREAD

**Issue by rhysforyou** [GitHawkApp/GitHawk#2026]
When using the app on a 9.7-inch iPad in portrait orientation, over a third of the screen real estate is taken up by the sidebar, making it feel like the main content area doesn’t have enough room to breathe. I personally like the way Working Copy handles this by showing a button to collapse the sidebar in either orientation like so:

![GitHawk Upload by rhysforyou](https://i.imgur.com/dMI47QW.jpg)
![GitHawk Upload by rhysforyou](https://i.imgur.com/AvBUGxC.jpg)

We could also go for a more traditional design akin to Mail.app, where the sidebar is always visible in landscape, and hidden in portrait with a button on the detail view’s navigation bar to slide it in from the side.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Just a heads-up that out of the box this will be collapsible on iPhone Plus devices in landscape too.

**Comment by rnystrom** [comment]
Yup, holding strong on that stance
