### ISSUE TITLE
Can't view branches on iPhone?

### ISSUE THREAD

**Issue by thirtytwobits** [GitHawkApp/GitHawk#2028]
Under the "code" tab for a repository there's no way to select a branch to browse.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528145114)
Device: iPhone 7 Plus (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by jdisho** [comment]
Dupe of https://github.com/GitHawkApp/GitHawk/issues/372, https://github.com/GitHawkApp/GitHawk/issues/1796
