### ISSUE TITLE
Change emoji picker to use ContextMenu

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2031]
Not sure about the design. Maybe on the left the image is the emoji, then a text label of what the emoji means? "Like", "Heart", etc?

I like the UX of the ContextMenu so much more.

**Comment by Huddie** [comment]
@rnystrom Is this for settings or on the Issues page? Or both

**Comment by rnystrom** [comment]
@Huddie issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
I think its nice that you would be able to react with multiple emojis without having to keep clicking the react button. It also matches labels, assigness, milestones...etc which makes sense. +1

**Comment by rnystrom** [comment]
Have an idea to solve this. Gonna try to get this working tomorrow.

**Comment by Huddie** [comment]
This should be closed by #2112 ya?

**Comment by BasThomas** [comment]
Yeah

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
