### ISSUE TITLE
Close issue action available on issues where I’m not allowed to close them

### ISSUE THREAD

**Issue by viktorgardart** [GitHawkApp/GitHawk#2042]
![GitHawk Upload by viktorgardart](https://i.imgur.com/jo7rz5R.jpg)

Caused by #2033 I believe.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1533487686)
Device: iPhone X (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by viktorgardart** [comment]
Same with reopen if issue is already closed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I think this is a dupe of #1992

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
