### ISSUE TITLE
Manage button behind message view

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2044]
Hovers above auto complete

![GitHawk Upload by rnystrom](https://i.imgur.com/bIDBmRe.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Actually solution should just be to insert the button behind the message view. It’s fine if it’s hidden while the autocomplete is active

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
That makes sense

**Comment by Huddie** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
