### ISSUE TITLE
Making send button inline with edit buttons

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2046]
I love the new send icon but I still feel that two button stacked above each other has abit of a tight feel (Send + 1 of the bar buttons)

I know slack has the send button on inline with the bar items. 

Heres a quick render of the concept.

![group 11](https://user-images.githubusercontent.com/10662471/43728648-b964ca8e-9973-11e8-8c51-87915ddf32dc.png)

**Comment by rnystrom** [comment]
Considering the actions scroll, how would we render the rest of them? Maybe a gradient on the right and fix the send button?

I’m pretty open to this idea. The send button and manage button are too much visual clutter to me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Yes a gradient was what I was thinking would look great!


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ok I’m sold

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Yes! As much as I’d love to help with this one I’m not sure I could do it justice. I looked into it and seems like it will require a bit of restructure change In MessageViewController. 
Just out of curiosity, MVC doesn’t have the edit bar below it that’s added in GitHawk itself right? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
It doesn’t, but I’ve got some ideas to unblock this one! Shouldn’t be an issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
