### ISSUE TITLE
Merge Button Gradient

### ISSUE THREAD

**Issue by BrianLitwin** [GitHawkApp/GitHawk#2051]
Updated the background of the Merge Button in #2049: 

<img width="284" alt="screenshot 2018-08-06 12 38 38" src="https://user-images.githubusercontent.com/26695477/43735944-fc652bce-9989-11e8-8a63-81ff66584327.png">

<img width="283" alt="screenshot 2018-08-06 13 22 36" src="https://user-images.githubusercontent.com/26695477/43735928-f18052ba-9989-11e8-922c-9379c644e167.png">

Is this consistent with the design patterns in the app? There aren't any gradients applied elsewhere. On the other hand, the merge button is one of the larger UI elements on which a gradient background would stand out.

**Comment by Huddie** [comment]
I’m torn if it’s consistent.
Looks great but there’s no gradient anywhere else. That being said, there aren’t many places a gradient could be. 
Labels seems to be the closest thing that aren’t gradient and I could see the distinction being actionable vs non-actionable. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya I think it looks slick, just wondering about consistency. Maybe we should just try it and see how it feels? Since this button is huge and kind of special, it could emphasize the importance.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Seeing this on the phone I have the same feeling. Looks nice but a bit out of place. Maybe if we went the card design route rather than the horizontal divider if would have fit in better. I’d say if the app ever moved slightly away from the flat look it employs right now, this button would be amazing for it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Idk I’m actually kind of digging it. Let’s try it for a week and see if it sticks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
I think this can be closed @BrianLitwin
