### ISSUE TITLE
Login should render inbox

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2052]
Steps to reproduce. 

1. Log out (I guess log in first)
2. Log In

You should see the settings page. 
Brings you back to where you left off I guess.. I feel like it should always render the inbox

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1533487686)
Device: iPhone 6s (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Sure

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ismetanin** [comment]
@rnystrom @Huddie 
Fixed in #2058
