### ISSUE TITLE
Report a bug not showing sent with githawk

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2053]
If you report a bug there’s no sent with githawk signature. Not sure why.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Correction. It did appear this time. 
Here’s a picture of my other one.
Maybe I did New Issue for that one. 
![GitHawk Upload by Huddie](https://i.imgur.com/adHJsD7.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Could have to do with the fact that I copied and pasted my body text. Not sure.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
There might be a diff between the report bug via settings and report bug via repo? What is the expected behavior here?

**Comment by Huddie** [comment]
I expected to show the githawk symbol. 
I honestly have no clue where I reported the bugs from each time. :/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Report a bug doesn't append the signature. "New Issue" does.

https://github.com/GitHawkApp/GitHawk/blob/master/Classes/New%20Issue/NewIssueTableViewController.swift#L38

I think this is fine.

**Comment by Huddie** [comment]
Oh okay cool. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
