### ISSUE TITLE
Resign keyboard when tapping merge button

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2057]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1533487686)
Device: iPhone X (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
I guess I could knock this one out

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
