### ISSUE TITLE
Source code browsing with a specific branch

### ISSUE THREAD

**Issue by vanyaland** [GitHawkApp/GitHawk#2062]
Currently, we can browse the source with `default` branch. It would be nice to add the ability to select a branch to browse for.

Like this **GitHub** menu:
<img width="139" alt="screen shot 2018-08-08 at 10 41 50" src="https://user-images.githubusercontent.com/8586063/43823452-bc4c45a8-9af7-11e8-8029-047025381e8d.png">

**Comment by rnystrom** [comment]
I def think this is doable. We need a UX for picking the active branch. Maybe as part of the repo header?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
We could start with an easy `UIAlertController` like this and have the "Branch" as the title. It supports scrolling if the alert actions overflow the screen height.

Not sure how ideal it is as that won't support searching / pagination.

**Comment by Huddie** [comment]
Maybe make use of ContextMenu. 
Matches UI
Lists the branches with a checkmark next to the one your currently viewing 
Not sure if ContextMenu supports search but I feel it could be added.

**Comment by rnystrom** [comment]
Ya I’d love to covert the alert menu for tapping the title to ContextMenu. Then it makes doing this advanced stuff really really easy. 

Also we need a way to show what branch you’re currently on.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom NavigationTitle? GitHawkApp/GitHawk/Master? May be a bit long. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vanyaland** [comment]
I think navigation title looks as it should, it’s not the best solution to make it a bit more complicated.

Exists repositories with longer names, which can cause problems.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Let's poke around on other apps and design sites to get some ideas. I browse [Dribbble](https://dribbble.com/) daily to pull inspiration or find new ideas. Maybe there's something that'll help.

**Comment by vanyaland** [comment]
Implemented #2162 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
