### ISSUE TITLE
View Participating Threads

### ISSUE THREAD

**Issue by BrianLitwin** [GitHawkApp/GitHawk#2065]
I noticed that getting the threads in which users are participating, ie the Participating tab on Github, is as easy as flipping [this value ](https://github.com/GitHawkApp/GitHawk/blob/38023e8fb317994988dc0b90e687a3eb552694e8/Local%20Pods/GitHubAPI/GitHubAPI/V3NotificationRequest.swift#L17) to true... feels like a low-cost feature, maybe under the "View All" tab in the more options alert controller? 

I don't know if there is a way to get a count of those Participating threads beforehand. That would be really nice. 

I also noticed the v3 api provides a reason for each notification and we're capturing capturing it [here](https://github.com/GitHawkApp/GitHawk/blob/38023e8fb317994988dc0b90e687a3eb552694e8/Local%20Pods/GitHubAPI/GitHubAPI/V3Notification.swift#L13-L25). Probably a stretch but an even softer touch could be to use that information to make an inference about whether a user is participating in a thread and convey it in the UI somehow.

**Comment by BrianLitwin** [comment]
![appvideo](https://user-images.githubusercontent.com/26695477/43925204-a36b4f4a-9bf4-11e8-9cd3-488e5c3aabf6.gif)

**Comment by rnystrom** [comment]
What's the value here?

**Comment by BrianLitwin** [comment]
My thought was providing the Participating Tab functionality, a list of issues you're actively participating in: 

<img width="252" alt="screenshot 2018-08-10 11 01 01" src="https://user-images.githubusercontent.com/26695477/43977149-32f99c22-9cb1-11e8-9f47-5cb8b9e0cfa2.png">

I always shoot straight for that tab, but I could be missing something.

**Comment by rnystrom** [comment]
Interesting! I don't think I've _ever_ used that tab before.

At the very least, we could add this into the ... menu bar item? Under "View All" .

**Comment by BrianLitwin** [comment]
Okay no probs, I'll close this issue. If there's ever a stampede of users demanding this feature, its a ~ 5 min job to build.
