### ISSUE TITLE
Add a "Is something wrong?" button on inbox zero

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2067]
I get the question a lot that there are notifications missing when they exist on the web. Maybe we can add a "fine print" button at the bottom of the inbox-zero display that opens the "Review Github Access" page. That usually seems to solve the problem.

**Comment by BrianLitwin** [comment]
Is this the right track? 

![simulator screen shot - iphone x - 2018-08-09 at 23 32 21](https://user-images.githubusercontent.com/26695477/43937588-9f869bae-9c2c-11e8-9814-9ffcb56f4119.png)

**Comment by rnystrom** [comment]
Ya! Few notes: can the text be even smaller? Also no border, we don’t want to over emphasize.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrianLitwin** [comment]
V2.. bumped the font from 13 to 12. 
<img width="300" alt="screenshot 2018-08-10 19 16 10" src="https://user-images.githubusercontent.com/26695477/43984975-ee87f23e-9cd1-11e8-9c62-afe7e1cee841.png">

What you think @Huddie ?

**Comment by rnystrom** [comment]
Ok last nit, maybe it just says “Review GitHub Access” in all grey. Single line, simple and clear, but not a dominant color that takes away from the animation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Looks great. I agree removing the ... and upper casing the to Access.
Removing the blue makes me feel like it’s not clickable.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
