### ISSUE TITLE
FeedRefresh only not calling beginRefreshing (only endRefreshing)

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2070]
Is there any chance that beginRefreshing (In `FeedRefresh.swift`) is seldomly called?

My research:
Checked the call hierarchy. It led me to 2 places

1. `Feed.refreshHead`
2. `RepositoryCodeBlobViewController`

I didn't focus on the 2nd one but in the first one I checked the call hierarchy again (For refreshHead)

1. `NotificationsViewController.didForeground(handler:)`

I took a guess on this one that it had to do with the app moving from inactive/background -> active/foreground. 

So i'm going to assume `FeedRefresh.beginRefreshing` isn't called regularly (When user pulls down on list)

Not sure if this is on purpose. Pretty sure everything is getting updated and pull to refresh will "work" fine with just endRefreshing called but 

1. It doesn't allow for custom pull to refresh animations to occur on begin
2. It's a bit weird that begin refreshing isn't called IMO -  especially since a public function exists for this purpose.

**Comment by rnystrom** [comment]
`beginRefreshing` is to manually start the refresh animation. When you pull down and trigger a refresh, only the target/action are called.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
But beginRefreshing if the refresh control should be called no?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Got it. Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
