### ISSUE TITLE
Resign keyboard when select search result

### ISSUE THREAD

**Issue by ismetanin** [GitHawkApp/GitHawk#2074]
Now when I select search result on the Bookmarks tab it looks buggy - keyboard hides on the repository screen

![2fmfqp](https://user-images.githubusercontent.com/11653316/43949146-5a9dee52-9c95-11e8-891b-0a617cd794d8.gif)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ew yes!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Huddie wanna pick this off too? Probably exactly the same fix as #2071

**Comment by Huddie** [comment]
@rnystrom Sure. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Fixed in #2077 :)
