### ISSUE TITLE
Multiple replies

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2081]
You can reply to a comment but if you’re writing a reply and want to reply to another comment (within your current comment) it will erase all that you wrote and start a new reply.

I’d rather just append the reply to the current comment being written

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1533779662)
Device: iPhone 6s (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Seems pretty edge case and user initiated. Not too worried.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
