### ISSUE TITLE
Can do everything except create comments on some repos that aren’t mine

### ISSUE THREAD

**Issue by cormacrelf** [GitHawkApp/GitHawk#2092]
The issue title says most of it.

Take 3 example repos. All are public.

- cormacrelf/xxxxx - I am the owner
- somebody/once-told-me - I am a contributor
- sharpest/tool - I have no special status

I can do almost every operation I normally can, including closing, labelling, merging, etc, on all three. I can even edit comments on all three.

But I cannot create comments on the latter two. Trying fails with “something went wrong”.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528145114)
Device: iPhone 6 (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by cormacrelf** [comment]
Test comment

**Comment by cormacrelf** [comment]
Ok, nope, that’s not it, i clearly just commented there. Have I just filed a dumb issue about OAuth access? I don’t know.

- cormacrelf/angular-skyhook — mine, can comment
- valor-software/ng2-dragula — contributor, everything but create comment
- stackblitz/core — unrelated, everything but
- GitHawkApp/GitHawk — unrelated, ok (???)

**Comment by cormacrelf** [comment]
No errors like the ones described in other issues on here. Just “something went wrong”. I can repro over and over again on ng2-dragula#874.

**Comment by cormacrelf** [comment]
The weird thing is being able to do everything else. Especially editing any comments I create elsewhere.

**Comment by cormacrelf** [comment]
Do you have a debug build?

**Comment by BasThomas** [comment]
Yes, see [here](https://github.com/GitHawkApp/GitHawk#contributing).
