### ISSUE TITLE
Markdown - only double newlines should cause new paragraphs

### ISSUE THREAD

**Issue by cormacrelf** [GitHawkApp/GitHawk#2093]
According to the GFM spec, at https://github.github.com/gfm/#paragraphs,
you may spread a paragraph over multiple lines.
For example, this sentence and the previous
one should render in one paragraph, not four.

But double newlines cause new paragraphs, like this. You can see how this can make it hard to read.

I write READMEs in vim with hard wrapping on, so all of them are hard to read, especially on iPhone in portrait mode. It is not typically a problem in comments and issues, because who is using hard wrapping there?

Example or hard to read README: https://github.com/valor-software/ng2-dragula

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528145114)
Device: iPhone 6 (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
I wonder where this diverges. We use GitHubs C parser. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jgm** [comment]
The parser has a setting that turns this behavior on or off, CMARK_OPT_HARDBREAKS.  See cmark(3) man page for details.  This should be turned on for rendering issues and code comments, off for READMEs and other md content.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
This is fixed now
