### ISSUE TITLE
Load more consistency

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2097]
![GitHawk Upload by Huddie](https://i.imgur.com/rGGahQk.jpg)

![GitHawk Upload by Huddie](https://i.imgur.com/yf0BTNr.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534015300)
Device: iPhone 6s (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
I can get this one

**Comment by BrianLitwin** [comment]
looking ahead at #317, there'll be a need for two more "load more" cells in user repositories and starred repositories.. would be really nice to have a standardized cell to drop in.

**Comment by rnystrom** [comment]
@BrianLitwin definitely. That was my original intention. We should be using the same cell for everything. We can do a sweep and delete the ones we don’t want.

Should we stick with the blue or grey? Also we need to use the one with the spinner.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Gray looked disabled IMO

**Comment by Huddie** [comment]
There’s already a loadMore cell problem is that there is an IssueNeckLoadCell or something like that also. I’m gonna just fix up LoadMore to support the needed functions and clear out the IssueLoadMore. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
