### ISSUE TITLE
Use same cell (size) for Search and Bookmarks

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2099]
<img src="https://user-images.githubusercontent.com/4190298/44003817-4af1dd68-9e59-11e8-9037-323cc3039e14.PNG" width="300"><img src="https://user-images.githubusercontent.com/4190298/44003818-4b0a8c14-9e59-11e8-8c13-2fc3271b972d.PNG" width="300">

**Comment by rnystrom** [comment]
Are they just different heights or actually different cells?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Different cells (`SearchRecentCell` vs `BookmarkCell`) according to FLEX.
