### ISSUE TITLE
Evaluate routing libraries and blog posts

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2105]
### Blog Posts

- [ ] [A Flexible Routing Approach in an iOS App](https://medium.com/rosberryapps/the-flexible-routing-approach-in-an-ios-app-eb4b05aa7f52)
- [ ] [URL Routing in iOS apps: Compass Beginner Guide](https://medium.com/flawless-app-stories/url-routing-with-compass-d59c0061e7e2)
- [ ] [Universal links in iOS](https://medium.com/@abhimuralidharan/universal-links-in-ios-79c4ee038272)
- [x] [Coordinator essentials pt 1](https://medium.com/blacklane-engineering/coordinators-essential-tutorial-part-i-376c836e9ba7)
- [x] [Coordinator essentials pt 2](https://medium.com/blacklane-engineering/coordinators-essential-tutorial-part-ii-b5ab3eb4a74)

### Criteria

- **Deep Links:** Does the lib have external "open url" support?
- **Data Params:** Can you provide arbitrary data when navigating?
- **Deep Nav:** Does navigation support arbitrary nesting (not just push a single VC)
- **Tab Selection:** Does the lib allow selection of `UITabBarController`?
- **Split VC:** Does the lib automatically support `UISplitViewController`?
- **Custom Transitions:** Can you do custom VC transitions?

### Legend

- ✅ Supported
- ❌ Not supported
- ⚠️ Supported with manual implementation

### Libraries

Name | Deep Links | Data Params | Deep Nav | Tab Selection | Split VC | Custom Transitions
---|:-:|:-:|:-:|:-:|:-:|:-:|
[Compass](https://github.com/hyperoslo/Compass) |✅|✅|❌|❌|❌|⚠️|
[URLNavigator](https://github.com/devxoul/URLNavigator) |✅|✅|❌|❌|❌|⚠️|
[DeepLinkKit](https://github.com/button/DeepLinkKit) |✅|✅|❌|❌|❌|⚠️|
[routable-ios](https://github.com/clayallsopp/routable-ios) |✅|✅|❌|❌|❌|❌|
[Router](https://github.com/freshOS/Router) |✅|✅|❌|❌|❌|⚠️|
[WAAppRouting](https://github.com/Wasappli/WAAppRouting) |✅|✅|❌|✅|❌|⚠️|
[HHRouter](https://github.com/Huohua/HHRouter) |✅|✅|❌|❌|❌|❌|
[Marshroute](https://github.com/avito-tech/Marshroute) |✅|⚠️|❌|❌|❌|✅|
[swift-deep-linking](https://github.com/ijoshsmith/swift-deep-linking) |⚠️|✅|❌|❌|❌|✅|
[RxCoordinator](https://github.com/quickbirdstudios/RxCoordinator) |❌|⚠️|❌|❌|❌|✅|
[route-composer](https://github.com/saksdirect/route-composer) |❌|⚠️|❌|❌|❌|🤷‍♀️|
[JLRoutes](https://github.com/joeldev/JLRoutes) |✅|✅|❌|❌|❌|⚠️|

**Comment by BasThomas** [comment]
JLRoutes / knil?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
# URLNavigator

- Params can string, int, float, path
- Register urls with handlers
  - Handlers return view controllers
  - Can also return "true" and do your own handling
- Can add a `wrap:` param to wrap a VC in another VC (e.g. `UINavigationController`)
- Set "extra" data in a context object
- [Custom value converters](https://github.com/devxoul/URLNavigator#defining-custom-url-value-converters)

**Comment by rnystrom** [comment]
# DeepLinkKit

- Register handlers for path strings with params
  - Exactly like Compass
- Blocks or classes as handlers
- Extremely limited, but maybe a good thing

**Comment by rnystrom** [comment]
# routable-ios

- Set a global `UINavigationController` that you always nav to
- Register classes to strings
  - Must implement `initWithRouterParams:` in VC
- Can have anon blocks execute for routes
- Options object with modal, presentation style, transition style, and default params

**Comment by rnystrom** [comment]
# Router

- Create a navigation enum
- Handle enum in switch and return VCs
- Faster compile times??? I don't think this is real

**Comment by rnystrom** [comment]
# WAAppRouting

- Register block handlers to strings with params
- VCs implement `reloadFromAppLinkRefresh`
  - VCs have a dictionary of stuff, access dictionary in this method
  - Weird that its not just a param
- Create entities that can have:
  - Source VC type
  - Target VC type
  - "presenting controller" (example has this as a nav)
  - Modal, params

**Comment by rnystrom** [comment]
# HHRouter

- Register VC for string path

**Comment by rnystrom** [comment]
# Marshroute

- Transition events forwarded to "top view controller"
- Use different method names to do different transitions (push, present)
- Supports UIKit custom transitions
- 3d touch baked in

**Comment by rnystrom** [comment]
# swift-deep-linking

- Create paths w/ `.term(...)` enums and params. Strict typing on paths
- Params can be string, int, bool, double
- In AppDelegate method, use `DeepLinkRecognizer` to cast to registered link
  - Then have to do your own `switch` type fork + custom handling method

> There are other deep linking libraries for Swift developers, some of which have much more functionality and flexibility. Based on my experience developing iOS and tvOS apps that need deep linking, this suits my needs. Sometimes less is more.

😊

**Comment by rnystrom** [comment]
# RxCoordinator

- "Reactive" navigation 😬
- Create an enum with all paths "for a particular flow"
  - "Flows" are modularized
  - "create a new Route/Coordinator whenever a new navigation controller is needed."
  - Implement "prepareTransition" method and handle
- Return custom animation objects
- NOT for app links, purely a "coordinator"
- Can have custom coordinators too

**Comment by rnystrom** [comment]
# JLRoutes

- Has the most stars so must be the best 😜 
- String paths and params like normal
- Handler block registration
  - Return `YES` when its handled
- Can register anything as `JLRRouteHandlerTarget` and implement `initWithRouteParameters`

**Comment by BasThomas** [comment]
Do you still want to do more investigating? This is an _awesome_ resource ticket by the way, maybe we should put it in a blog post of some sorts.

**Comment by rnystrom** [comment]
Closing since what I built solves the problem. Agree, this could def be a blog post along w/ where we landed!

**Comment by bellebethcooper** [comment]
Just wanted to drop a link here to [this related PR](https://github.com/GitHawkApp/GitHawk/pull/2241), because I was curious how this issue turned out and it took me a while to find the answer.

**Comment by rnystrom** [comment]
Thanks @bellebethcooper! I’ll be updating with more ideas for basic routing in GitHawk soon too 😇

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
