### ISSUE TITLE
Editing first child photo loads 2nd child photo

### ISSUE THREAD

**Issue by kinggoff** [GitHawkApp/GitHawk#2109]
https://atschooltoday.slack.com/archives/CAB2RL3K7/p1534127196000076

Watch posted video

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528145114)
Device: iPhone X (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Can you upload a gif? I can't watch the video w/out signing into Slack.

**Comment by kinggoff** [comment]
Sign into slack. Github is limited.

GJ

**Comment by rnystrom** [comment]
I don't use Slack 🤷‍♀️

**Comment by kinggoff** [comment]
Hi Ryan,

I am confused. I thought I was responding to a dev member.  I am using GitHawk to communicate with my team. Wondering how you got access to our private project? I know githawk needs acces but not sure why you have access? 

Are you an iOS and android developer? 

Do you happen to know react?

I am looking for good developers.

GJ
