### ISSUE TITLE
Some alignment issue?

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2115]
Picture I think explains this rare issue. 

![GitHawk Upload by Huddie](https://i.imgur.com/GlBvTxu.jpg)

My thought is that this is related to #2015.
It appears that once the keyboard is shown and collapsed the emoji bar can get displaced.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534118943)
Device: iPhone 6s (iOS 11.4.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
It's probably the same issue. Banking on #2112 fixing all of this.

**Comment by Huddie** [comment]
Didn’t see that pull request. Looks so cool!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
