### ISSUE TITLE
2nd child disappeared in app

### ISSUE THREAD

**Issue by kinggoff** [GitHawkApp/GitHawk#2116]
https://atschooltoday.slack.com/archives/CAB2RL3K7/p1534186574000044

My second child, Teighan has disappeared from the app.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.21.0 (1528145114)
Device: iPhone X (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Is this different from #2109?

**Comment by kinggoff** [comment]
Ryan,

My total mistake. I thought I was reporting a bug to my project.

I have a cool project on the go and wondering if you do contract work?

GJ
