### ISSUE TITLE
3D concept

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2127]
I had posted a profile concept in #2106 which wasn't as "flat" as the current app. 
I just decided to post it here instead. Probably could be used in the current app.

![artboard](https://user-images.githubusercontent.com/10662471/44290670-c4a00800-a247-11e8-994a-28d3028788dd.jpg)

**Comment by BrianLitwin** [comment]
can you move these back to the wireframe thread? I like looking at all the designs in one place

**Comment by rnystrom** [comment]
I like using shadows for some things, but it should be reserved for high-importance actions or info IMO. The visual language of shadows puts whatever info “above” everything else.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
>can you move these back to the wireframe thread? I like looking at all the designs in one place 

@BrianLitwin ya I can do that 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom That makes sense. I’m going to close this and move back the profile picture as @BrianLitwin  suggested.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
