### ISSUE TITLE
Can't do code review

### ISSUE THREAD

**Issue by genebean** [GitHawkApp/GitHawk#2139]
I can comment on pull requests and merge them but can't seem to do a formal review that includes the in line comments or the approve / request changes actions.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone 7 Plus (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Yeah, will close this one in favor of #1547. :)
