### ISSUE TITLE
Move the “lock” button to below the divider line

### ISSUE THREAD

**Issue by j-f1** [GitHawkApp/GitHawk#2140]
**Is your feature request related to a problem? Please describe.**
When clicking on the hamburger button to modify the issue, the buttons are grouped into two groups: the close option and everything else:

<img src="https://user-images.githubusercontent.com/25517624/44527566-37303e00-a6b5-11e8-8a2f-28c867b1b571.jpeg" width="200">

**Describe the solution you'd like**
I suggest this divider be moved up one spot, above the lock button. This would divide the options into ones that prompt for more information (above the line) and ones that take action immediately (lock/close).

**Describe alternatives you've considered**
We could leave it as-is, but there’s currently no indication that locking the issue will lock it right away instead of prompting for confirmation, like all similarly-styled options do.

**Comment by Huddie** [comment]
I agree

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kokkimphal** [comment]
@````
~~~~
````

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kokkimphal** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I’m down with this. Lift gray would be good for the icon. Easy issue for someone to pick up.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
This issue should be able to be closed

**Comment by Huddie** [comment]
@j-f1 really?! That’s cool. Thank you

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
@Huddie https://help.github.com/articles/closing-issues-using-keywords/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
I think the requirement is that either you or the person merging the PR has the ability to close the issue (although I’m not sure about the former).

**Comment by Huddie** [comment]
@j-f1 Well, thanks for the tip. I never knew that.
