### ISSUE TITLE
Can’t upload images

### ISSUE THREAD

**Issue by selwin** [GitHawkApp/GitHawk#2141]
Whenever I try to upload an image, it always fails with “Something went wrong”

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone X (iOS 12.0)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
Could it be iOS 12 related?

**Comment by selwin** [comment]
Yeah, I’m running iOS 12 public beta. Sorry I forgot to mention such as important thing.

Best,
Selwin

**Comment by BasThomas** [comment]
Are you still running into the issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by selwin** [comment]
Yes, I'm running iOS 12 public beta 10. Since iOS 12 will probably be released sometime in the next few weeks, it's likely this issue will still be present in the GA version.

**Comment by Sherlouk** [comment]
![GitHawk Upload by Sherlouk](https://i.imgur.com/Ucn8w7p.jpg)

Doesn't appear to be ios 12 completely, uploaded fine for me! Could be a lot of reasons annoyingly, we only display a generic error

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Do we show a specific when the Imgur limit is reached?

I’d be super grateful to anyone that figures out how GitHub content uploads work and we just use that...

Otherwise maybe we need another image upload service?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
> Do we show a specific when the Imgur limit is reached

Yeah I made sure I was ready for the time we have so many users we exceeded the rate limit ([code here](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Image%20Upload/ImgurClient.swift#L73))

I did look into GitHub URL but as it's not a public API it wasn't the easiest to work out and has the typical issue of maintaining that

If there's a different upload service with an increased limit then all for switching away from Imgur

**Comment by Huddie** [comment]
Guess it’s not iOS 12 related

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
