### ISSUE TITLE
Long comment on issues not expandable

### ISSUE THREAD

**Issue by muuvmuuv** [GitHawkApp/GitHawk#2153]
I tried to click on the expand button but nothing happened, instead the small preview above is scrollable... made a Video, but can not upload it here

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone 6s (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by muuvmuuv** [comment]
![](https://ufile.io/lz4ir)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
@muuvmuuv I don’t think GitHub itself supports videos.

**Comment by BasThomas** [comment]
Yeah, you should be able to tap anywhere else in the cell to trigger the expansion, not just the button. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
