### ISSUE TITLE
“Copy name” and more actions when browsing code

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2161]
- ... button in right nav when browsing dir 
- Replace right bar nav with ... button when viewing code
- Add following options:
  - “Copy path”
  - “Copy name”
  - “Share URL”
  - “Share content” (field only)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ashleyng** [comment]
I can start work on this. and assuming you meant `files only` instead of `field only`?
