### ISSUE TITLE
Change repo branch

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2162]
I know this is requested elsewhere but just listing out how the feature should work:

- New option in repo ... menu “Change branch”
  - Append active branch “:branch” to alert title, eg `GitHawkApp/GitHawk:branch`
- Selecting menu item shows centered ContextMenu (ex Labels)
  - Load all available branches
  - Check mark on selected
  - Only one selected at a time (see Milestones, code might be bad?)
- On dismiss, having changed selection, reload Overview and Code VCs
  - (_stretch_) If not at root in Code, restore to active file with new branch selected

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrianLitwin** [comment]
Will give this a go

**Comment by BrianLitwin** [comment]
@rnystrom or anyone else that has thoughts - 
1) Do you envision users selecting a row and the contextMenu dismissing immediately, or selecting a row and then confirming with an "Ok" or "Cancel" button at the bottom of the contextMenu? 

2) Should we get all the repo branches as a field in the first GQL query (ie the SearchRepo query), or make a separate request for them when the user asks to switch branches?

**Comment by Huddie** [comment]
For 1 I'd say no confirmation needed but not necessarily dismiss right away. Maybe have the button at the top right say "dismiss".  So the user can pick 1 branch and then pick another if they made a mistake or something.

**Comment by BrianLitwin** [comment]
@huddie what would the button at the top right look like? I'm envisioning this as similar to a tableView embedded in an Action Sheet, with Cancel and Select/OK buttons at the bottom.

**Comment by BrianLitwin** [comment]
Look good? 

![contextmenuswitchbranch](https://user-images.githubusercontent.com/26695477/45979700-e72ef900-c01d-11e8-9244-91d70c48e14d.gif)

**Comment by rnystrom** [comment]
@BrianLitwin amazing!! Love it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Ya that’s perfect!!!! @BrianLitwin super cool!!!!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrianLitwin** [comment]
@Huddie I see what you mean by top right button now! Haha 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
