### ISSUE TITLE
Repo level permissions instead of organization level

### ISSUE THREAD

**Issue by a-b** [GitHawkApp/GitHawk#2163]
As a user in large organization I have full permissions for my repository, but it’s hard to get access to the whole organization access for 3rd party app. I’d like to connect only my repo instead of requesting permissions organization wide.

**Comment by a-b** [comment]
Apparently, personal token could be used for such occasion. Perhaps it worth to simplify UX discoverability of that option.

**Comment by j-f1** [comment]
Thanks for pointing that out! I’ve been wondering how to get the app to work for orgs I wasn’t able to get permissions for.
