### ISSUE TITLE
Enable localised Inbox Zero dates

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#2164]
**Is your feature request related to a problem? Please describe.**
Currently the "Inbox Zero" message can be changed depending on the current date and if there's a holiday such as Christmas or New Years but these dates are mostly for America and there are some differences around the world.

As GitHub is world-wide it would be nice if we had a way to change the holidays and the dates they land on depending on the origin of the user. For example: Mother's Day is 31st March 2019 in the UK and 12th May 2019 in the US!

**Describe the solution you'd like**
As per Ryan's suggestion in the PR we could add the user's locale to the holiday's endpoint like below:
http://githawk.com/holidays-UK.json

This would return different holidays or the same ones on different days.

We would likely want to handle the case where we don't support a particular locale, maybe falling back to a default one without a locale?

**Describe alternatives you've considered**
Alternatives could be using one file as it currently does but providing an array of locale codes that it is enabled for.

On the same line of suggestion, we could provide a dictionary of locale code to dates if they differ.

Open to suggestions!

**Additional context**
Some comments in the pull request which introduced the functionality
https://github.com/GitHawkApp/GitHawk/pull/2142

**Comment by rnystrom** [comment]
Actually that’s a better idea than I’d been doing it. We can just store the file on another repo and let ppl submit updates.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
