### ISSUE TITLE
When using mark all as read, the split view on iPad still kept the last issue I was viewing open even though the list was now empty.

### ISSUE THREAD

**Issue by shaps80** [GitHawkApp/GitHawk#2166]
![GitHawk Upload by shaps80](https://i.imgur.com/h9qL4Za.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPad7,3 (iOS 12.0)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Hmm, idk if I'm too offended. Are there other apps that handle this better? What do you expect to happen?

I kind of like how it's sort of "multi tasking" views. If we were to just drop the right view, we could interrupt something you were doing.

**Comment by shaps80** [comment]
I just don’t know of any other app (unless it’s a bug) that shows detail on the right, that’s no longer visible on the left. Seems odd to me. Am I alone in this?

Obviously not a major bug or issue, agreed. 

But if i made a conscious choice to clear the left list, I’m clearly done.

Anyway, I agree it’s minor just thought you’d prefer bugs were logged 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
