### ISSUE TITLE
“New features” banner in inbox

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2170]
I’ve got some ideas on a design for this, I’ll spec it out later. Basic idea is a banner in feed that says there are new features. Show a button that says “View” and show notes in a modal. Another X button to dismiss.

I want to call out important features between app updates that might be easy to miss (eg notifications).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah this seems nice. Love how Workflow did (does?) this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas got any screenshots? I haven’t seen there’s!

I love Things 3s “new today” banner. Really little and you can tap to expand or dismiss. I’ll try to nab a shot.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Well they have it on the site: https://workflow.is/whatsnew, seems like they removed it from the app

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
But is was basically a modal (a la big contextmenu) with the changelog as far as I can remember

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
This is iA Writer’s

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
