### ISSUE TITLE
Add option to automatically mark issues as complete when opening them

### ISSUE THREAD

**Issue by nikitavoloboev** [GitHawkApp/GitHawk#2174]
Same as GitHub does. If user opens the issue/pr to see it, it will no longer be in the Inbox. With GitHawk I have to not only see the issue but then mark it as complete which very annoying.

**Comment by BasThomas** [comment]
You can enable “Read on Open”

![GitHawk Upload by BasThomas](https://i.imgur.com/mqA8qu1.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
