### ISSUE TITLE
Filter icon instead of 3 dots

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2177]
On the inbox page, the 3 dots (top left) allow for switching to a specific repo or view all. Maybe a filter icon is more appropriate

**Comment by rnystrom** [comment]
I dig it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
So I couldn't find a filter octicons so I went at making it myself.
Anyone have a better filter icon or suggestions to improve this one?

![simulator screen shot - iphone xr - 2018-09-25 at 22 27 56](https://user-images.githubusercontent.com/10662471/46053814-4f5f0700-c112-11e8-8a02-984d5752c93e.png)

**Comment by Huddie** [comment]
My bad filling in the top. We seem to use outlined icons for navBar items

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Take 2
![simulator screen shot - iphone xr - 2018-09-26 at 21 57 56](https://user-images.githubusercontent.com/10662471/46119054-497f2980-c1d7-11e8-9741-58e52cb6c773.png)

**Comment by Huddie** [comment]
Thoughts on improvements, or anyone have an icon ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Looks a little sharp on the edges. How about this one?

https://thenounproject.com/search/?q=Filter&i=1956576

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
There’s no icon at all in the latest beta here?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas 😱 your right me neither! Where’d it go? Ha

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
No idea 😛

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom I like the icon but I don’t have the ability to download it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom would you be able to add the icon to the project ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Any interest in this still?

**Comment by kocheck** [comment]
@Huddie  I can download and package that up for you ✌️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@kocheck thank you 😊 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Almost wondering if we should revisit some ideas for the inbox. One is maybe putting a drop down title and showing a menu with more per-repo options? I know folks really want the per-repo inbox (which is technically very complicated).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@kocheck if your free would you be interested in whipping up a few new inbox designs using what we have now + per-repo inbox + maybe issue Dashboard #2413 ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@kocheck awesome. Take your time, should we create a new issue to inbox concepts/ideas?

**Comment by kocheck** [comment]
@Huddie Ya lets do that, Do you think over in the design repo would work?

**Comment by Huddie** [comment]
Hmm. Not sure. Design repo is great for storing concepts etc but contributor traffic I feel is low. If we want to have a conversation about the new inbox I think GitHawk repo is the best place. @rnystrom would have a better sense

**Comment by kocheck** [comment]
Whatever works best honestly 😄 but a new issue would help keep things organized I think.

**Comment by BasThomas** [comment]
I'm going to close this as we do not have an icon to filter anymore, but a dropdown.
