### ISSUE TITLE
Git Ignore

### ISSUE THREAD

**Issue by rob-nash** [GitHawkApp/GitHawk#2179]
**Is your feature request related to a problem? Please describe.**

After working through the project setup guide, the project compiles and Apps run. No problems. 
Guide is awesome by the way.

However, I now have a bunch of files tracked by .git in staging. Such as:

```xml
 <dict>
 	<key>com.apple.security.application-groups</key>
 	<array>
		* <string>group.com.whoisryannystrom.freetime</string> *
		<string>group.com.robertnash.freetime</string>
 	</array>
 </dict>
 </plist>
```

PODS files are also tracked.

When contributing, I only commit the stuff that's relevant to the pull request in question. However, it's a bit of a pain having all these files lit up in staging. Any advice on how to organise the staging area without committing to `.gitignore`?

**Describe the solution you'd like**

An easy win for ~%70 of the stuff currently in my staging area (see below) would be to stop tracking PODS files. Committing that to `.gitignore` would be a win for all users of the repo no? Not a total solution to the problem but it's all I got...

**Describe alternatives you've considered**

Stashing changes and applying the stash when it's needed. Keep forgetting though. Feels ugly anyway.

**Additional context**

My current staging area

```
Freetime.entitlements
Podfile.lock
Freetime.xcodeproj/project.pbxproj
Freetime.xcodeproj/xcshareddata/xcschemes/Freetime-AppCenter.xcscheme
FreetimeWatch/FreetimeWatch.entitlements
FreetimeWatch/Info.plist
FreetimeWatch Extension/FreetimeWatch Extension.entitlements
FreetimeWatch Extension/Info.plist
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/Target Support Files/Alamofire-iOS/Alamofire-iOS.xcconfig
Pods/Target Support Files/Alamofire-watchOS/Alamofire-watchOS.xcconfig
Pods/Target Support Files/AlamofireNetworkActivityIndicator/AlamofireNetworkActivityIndicator.xcconfig
Pods/Target Support Files/Apollo-iOS/Apollo-iOS.xcconfig
Pods/Target Support Files/Apollo-watchOS/Apollo-watchOS.xcconfig
Pods/Target Support Files/AutoInsetter/AutoInsetter.xcconfig
Pods/Target Support Files/cmark-gfm-swift/cmark-gfm-swift.xcconfig
Pods/Target Support Files/ContextMenu/ContextMenu.xcconfig
Pods/Target Support Files/DateAgo-iOS/DateAgo-iOS.xcconfig
Pods/Target Support Files/DateAgo-watchOS/DateAgo-watchOS.xcconfig
Pods/Target Support Files/FBSnapshotTestCase/FBSnapshotTestCase.xcconfig
Pods/Target Support Files/FLAnimatedImage/FLAnimatedImage.xcconfig
Pods/Target Support Files/FlatCache/FlatCache.xcconfig
Pods/Target Support Files/FLEX/FLEX.xcconfig
Pods/Target Support Files/FMDB/FMDB.xcconfig
Pods/Target Support Files/GitHubAPI-iOS/GitHubAPI-iOS.xcconfig
Pods/Target Support Files/GitHubAPI-watchOS/GitHubAPI-watchOS.xcconfig
Pods/Target Support Files/GitHubSession-iOS/GitHubSession-iOS.xcconfig
Pods/Target Support Files/GitHubSession-watchOS/GitHubSession-watchOS.xcconfig
Pods/Target Support Files/Highlightr/Highlightr.xcconfig
Pods/Target Support Files/HTMLString/HTMLString.xcconfig
Pods/Target Support Files/IGListKit/IGListKit.xcconfig
Pods/Target Support Files/MessageViewController/MessageViewController.xcconfig
Pods/Target Support Files/NYTPhotoViewer/NYTPhotoViewer.xcconfig
Pods/Target Support Files/Pageboy/Pageboy.xcconfig
Pods/Target Support Files/Pods-Freetime/Pods-Freetime-frameworks.sh
Pods/Target Support Files/Pods-Freetime/Pods-Freetime-resources.sh
Pods/Target Support Files/Pods-Freetime/Pods-Freetime.debug.xcconfig
Pods/Target Support Files/Pods-Freetime/Pods-Freetime.release.xcconfig
Pods/Target Support Files/Pods-Freetime/Pods-Freetime.testflight.xcconfig
Pods/Target Support Files/Pods-FreetimeTests/Pods-FreetimeTests-frameworks.sh
Pods/Target Support Files/Pods-FreetimeTests/Pods-FreetimeTests-resources.sh
Pods/Target Support Files/Pods-FreetimeTests/Pods-FreetimeTests.debug.xcconfig
Pods/Target Support Files/Pods-FreetimeTests/Pods-FreetimeTests.release.xcconfig
Pods/Target Support Files/Pods-FreetimeTests/Pods-FreetimeTests.testflight.xcconfig
Pods/Target Support Files/Pods-FreetimeWatch/Pods-FreetimeWatch-frameworks.sh
Pods/Target Support Files/Pods-FreetimeWatch/Pods-FreetimeWatch-resources.sh
Pods/Target Support Files/Pods-FreetimeWatch Extension/Pods-FreetimeWatch Extension-frameworks.sh
Pods/Target Support Files/Pods-FreetimeWatch Extension/Pods-FreetimeWatch Extension-resources.sh
Pods/Target Support Files/SDWebImage/SDWebImage.xcconfig
Pods/Target Support Files/SnapKit/SnapKit.xcconfig
Pods/Target Support Files/Squawk/Squawk.xcconfig
Pods/Target Support Files/StringHelpers-iOS/StringHelpers-iOS.xcconfig
Pods/Target Support Files/StringHelpers-watchOS/StringHelpers-watchOS.xcconfig
Pods/Target Support Files/StyledTextKit/StyledTextKit.xcconfig
Pods/Target Support Files/SwipeCellKit/SwipeCellKit.xcconfig
Pods/Target Support Files/Tabman/Tabman.xcconfig
Pods/Target Support Files/TUSafariActivity/TUSafariActivity.xcconfig
```

**Comment by rnystrom** [comment]
We shouldn’t stop tracking Pods because I’d prefer the project is build-and-runnable from just downloading. 

I guess that’s sort of moot since you have to setup API keys and stuff tho.

Open to suggestions if someone has a solid e2e solution. But simply removing the pods from git probably isn’t enough.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rob-nash** [comment]
I guess this ticket is focused on the contributing experience.  That being the ease in which developers can contribute. For instance, I'm about to create branch and start working on #1745 and all of the following code has to come along for the ride.

<img width="741" alt="screenshot 2018-09-25 at 06 43 43" src="https://user-images.githubusercontent.com/14126999/45995052-59d7bd00-c08e-11e8-98d5-fcd4c8f98dd8.png">

**Comment by rob-nash** [comment]
I suppose it's a battle between how smooth it is to run the initial fetch vs how smooth it is to run every code change going forward for the lifetime of the project.

Pod install is part of the setup guide's instructions. And as you say, you can't do anything with the App until you have added keys. So I agree that it's moot to keep tracking PODS for the benefit of a `build-and-run` experience. There is no build and run experience right now, right? I don't think you can really achieve a build and run experience for Apps that depend heavily on third party libraries and services like Fabric? Inevitably, you're going to have to run some sort of setup, which is to be expected I think. The setup guide is quite clear anyway.

**Comment by rob-nash** [comment]
I would actually like to ask a question about the setup guide (I'm not familiar with the project or its history of technical decisions). 

Is it essential to change the bundle identifier throughout the project, right off the bat?  

If not, we may want to cut the setup guide down and hyperlink to a separate document explaining the bundle identifier stuff. 

To that end we can then hyperlink to the document for those individual tickets that demand a unique bundle identifier. 

The acting developer on the day would understand the need for the changes and make those changes on that particular day for that particular ticket. 

Afterwards, he/she can reset the changes.

**Comment by rob-nash** [comment]
I have got in the habit recently of demonstrating terminal commands with `asciinema` because sometimes it helps illustrate how quick the setup actually is versus how it appears when listed as a series of steps in a readme. [Example here](https://github.com/rob-nash/Rotary/wiki/Installation).

**Comment by rob-nash** [comment]
If we commit the following, then there won't be a need to mention changing this in the setup guide because you can still run on the simulator with `none` selected.

<img width="326" alt="screenshot 2018-09-25 at 07 34 50" src="https://user-images.githubusercontent.com/14126999/45996827-817e5380-c095-11e8-9872-fd4eee7e870c.png">

Furthermore, I think everyone understands these days that deployment to a device requires a paid account.

**Comment by rob-nash** [comment]
We may want to ignore the scheme?

```
Freetime.xcodeproj/xcshareddata/xcschemes/Freetime-AppCenter.xcscheme
```

That way the GITHUB_CLIENT_ID stuff won't light up for everyone.

Or maybe not ignore the scheme, but pull out the client ID and add it as a line of code in a `.swift` file somewhere and ignore that file?

I dunno
