### ISSUE TITLE
Unable to turn on notifications

### ISSUE THREAD

**Issue by timonus** [GitHawkApp/GitHawk#2181]
In the latest beta the notifications rows just say “Settings”, but when I tap through Settings.app doesn’t show notifications permissions for GitHawk. The app needs to request permission at some point via [this method](https://docs.developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649527-requestauthorizationwithoptions?language=objc).

![GitHawk Upload by timonus](https://i.imgur.com/MGkXcDD.jpg)

![GitHawk Upload by timonus](https://i.imgur.com/vmk0N6c.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Oh no, thanks for this! Def need to fix

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
I have managed to turn them on, but I'm yet to receive a notification.

Am I missing something?

**Comment by Huddie** [comment]
I think I also was supposed to receive and didn’t. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by drewvolz** [comment]
The app does contain the call to prompt for notification permissions via `requestAuthorization`, but the conditions that trigger it to prompt might need tweaking.

https://github.com/GitHawkApp/GitHawk/blob/05fe58394c5067340ebb29eea1fca484f593feed/Classes/Systems/BadgeNotifications.swift#L59-L72

@rnystrom on a clean install of the application:

* `isBadgeEnabled` and `isLocalNotificationEnabled` are both `false`, so...
* `options.isEmpty` is `true`.

So both `.badge` and `.alert` are not being inserted into `options`.

The app currently _does_ have notifications enabled for me via TestFlight, but I've yet to see a local notification be generated. Prompting and generating/receiving could be separate issues here.

**Comment by gingerbeardman** [comment]
I've started to see notifications in 1.23 without doing anything different
