### ISSUE TITLE
Consider Twitter keyboard again for commenting

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2183]
Now that we have `#` support for issues, maybe we should reconsider the keyboard or add a `#` option to the options bar.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1537716040)
Device: iPhone X (iOS 12.0)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Maybe we add it as an action bar key instead? I like having the return key

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
The return key is still available:

![](https://im4.ezgif.com/tmp/ezgif-4-6f514dedcb.gif)

**Comment by BasThomas** [comment]
Yeah action bar works too (like I mentioned)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
>The return key is still available:

We tried it before and reverted if I remember correctly. Either makes sense to me. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas yup we did

**Comment by ijm8710** [comment]
New here but please don’t do it as twitter. Do the action bar! I’ve been begging the engineers for weeks at twitter to switch back and make it an action ba. Return is such a used stoke and it stinks having it a layer back.

**Comment by BasThomas** [comment]
> Maybe we add it as an action bar key instead? I like having the return key
> 
> Sent with [GitHawk](http://githawk.com)

I'm leaning towards this now. Should I create a new issue in favor of this one?

**Comment by ijm8710** [comment]
Are there any other keyboard supports that should be added as well such as numbering or quoting?

**Comment by ijm8710** [comment]
Hey @BasThomas, were you still planning to re-issue this :)
Are there any other keyboard supports that should be added as well such as numbering or quoting?

**Comment by ijm8710** [comment]
#113
