### ISSUE TITLE
Old PRs/Issues "Fail to load"

### ISSUE THREAD

**Issue by crrapi** [GitHawkApp/GitHawk#2184]
PRs and Issues that are more than about a year old "Fail to load" and show the error. (Observed in the Rapptz/discord.py repository)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone X (iOS 12.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
@crrapi could you give us an issue #?

**Comment by crrapi** [comment]
My bad, the issue seems to have resolved itself. (maybe it was because of the bad WiFi connection at the time?) Closing as I don't experience this anymore.
