### ISSUE TITLE
Add # autocomplete for issue references

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#219]
Version 1.4.0 (1136)
Device: iPhone 7 Plus (iOS 10.3.3)

**Comment by rnystrom** [comment]
Absolutely!

**Comment by TheCodeTalker** [comment]
```
  func fetch(
        owner: String,
        repo: String,
        number: Int,
        width: CGFloat,
        prependResult: IssueResult?,
        completion: @escaping (IssueResultType) -> () 
```  is IssueResult contains issue references or how can i get those objects ??  i have make a seperate call or what .

**Comment by rnystrom** [comment]
Did a quick investigation, this might be too difficult w/ just number autocomplete. None of the APIs provide a way to search via the number. All of the search is done by matching text in the title, body, or comments ([ref](https://developer.github.com/v3/search/#search-issues)).

How about we change this to do a search like "#search" that autocompletes issues w/ the word "search" in them? The comments UI works like this now.

<img width="502" alt="screen shot 2017-08-09 at 12 15 29 pm" src="https://user-images.githubusercontent.com/739696/29131966-960b35c6-7cfc-11e7-91e7-8c31d7bf4fb0.png">

Now the question is if we use the v3 API (ref above) or the [GraphQL API](https://developer.github.com/v4/reference/query/). Haven't dug on what is better suited, but probably the GraphQL API.

@TheCodeTalker in that case we'll need to build a new query for this.

**Comment by BasThomas** [comment]
That's not cool :(

I think searching with words could work 👍. Didn't even know that also worked, thought you could only search by number...

**Comment by rnystrom** [comment]
Agree, search-by-number is obvious, might be confusing. But I'll settle for _something_ working, I guess.

**Comment by TheCodeTalker** [comment]
I think search by words would be great 👍

**Comment by dakeshi** [comment]
@rnystrom  I didn't check GraphQL API v4 yet but we can get a list of issues in v3 Rest API (https://developer.github.com/v3/issues/)

> https://api.github.com/repos/rnystrom/Freetime/issues

**Comment by Sherlouk** [comment]
For what it's worth regardless of whether you use GQL or V3, if you use "in:title" it does include the number if it's an exact match.

Example:
```gql
query {
  search(first: 20, query: "repo:rnystrom/GitHawk in:title 12", type: ISSUE) {
    nodes {
      ... on Issue {
        number
        title
      }
    }
  }
}
```

`https://api.github.com/search/issues?q=repo%3Arnystrom%2FGitHawk+in%3Atitle+12&access_token=redacted`

Annoyingly though GitHub doesn't support any sort of "fuzzy" search, so it will show issue 12 but not issue 123! (Likewise if you search for "autocomplet" it will return nothing, if you search for "autocomplete" it will return a bunch!)

I think that's as good as this'll be though!
