### ISSUE TITLE
Write a review space/indent

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2190]
Anyone else see this? I can only see it on iPhone XR simulator.
![simulator screen shot - iphone xr - 2018-09-26 at 15 23 44](https://user-images.githubusercontent.com/10662471/46107018-4751a680-c1a8-11e8-848e-7cdd41fb30b0.png)

**Comment by j-f1** [comment]
No repro on 8:

![GitHawk Upload by j-f1](https://i.imgur.com/enOpVqD.jpg)

**Comment by rizwankce** [comment]
Yup. Attaching iPhone xs max screenshot. ![GitHawk Upload by rizwankce](https://i.imgur.com/0yD3gBf.jpg). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Ah ha! It does exist! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Any ideas ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
