### ISSUE TITLE
Bottom border of PR status box missing

### ISSUE THREAD

**Issue by j-f1** [GitHawkApp/GitHawk#2199]
When I don’t have push access, the bottom border doesn’t show up.

![GitHawk Upload by j-f1](https://i.imgur.com/Z6gufmW.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1538176803)
Device: iPhone 8 (iOS 12.0)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
@Huddie from the merge change

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
I’m on it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
I think this should be able to be closed, but totally get waiting for the next beta to confirm
