### ISSUE TITLE
Background updates and pushes not working?

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2213]
When debugging, I’m getting pushes and updated badge numbers, but not when using the latest TestFlight version. 

Unsure if it’s the bg fetch not triggering or something else... when I open the app I get all the new notifications.

Anyone else seeing this?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (SEE BUILD PHASE)
Device: iPhone X (iOS 12.0)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
I believe I experienced this, only once I opened the app did the notifications come.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Oops I had low power mode on 😳

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom does getting notifications when you open the app make sense or should notifications be cleared if you open the app on low-power mode?

**Comment by rnystrom** [comment]
@Huddie notifications in-app? Or local notifications? IMO they should be cleared.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Local notifications. You mentioned 

> Unsure if it’s the bg fetch not triggering or something else... when I open the app I get all the new notifications.

Which sounded like after you opened the app, the notifications appeared. The issue was closed because push notifications are working, but it sounds like a bug in low-power mode where you get notifications after opening the app.
