### ISSUE TITLE
Try again when loading fails

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2214]
This is what can happen if you lack a network (see imagine) when trying to view an issue (similar view would appear with many other sections) 
I happen to know to pull down the view to cause the pull to refresh to occur but someone else just looking at this view may not think they can pull to refresh.

Maybe we can add a “Try again” or “Refresh” button beneath the “Issue cannot be found” wording. That way people can click it to start a refresh. 
 ![GitHawk Upload by Huddie](https://i.imgur.com/PcRQWN4.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
This would be great. Much better UX.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cameronmoreau** [comment]
How does something like this look? I'll follow up with a PR soon. 

![img_1927](https://user-images.githubusercontent.com/732722/46390661-bdb14580-c68d-11e8-84c3-aeb6cc255eb0.PNG)

**Comment by Huddie** [comment]
Looks nice! I think the current GitHawk style would be more of just "Try Again" in blue, no background (See "Load More" cells and "Review Github Access", which don't have backgrounds to them).

**Comment by kngu9** [comment]
@cameronmoreau I think "Cannot load README" defines a system specific behavior, like there might or might not contain a README, but unable to parse it.

Maybe specify that there is not a README for the repository?

**Comment by rnystrom** [comment]
Exactly what @Huddie said 😄

**Comment by BasThomas** [comment]
This is there now 👍
