### ISSUE TITLE
Sent with GitHawk

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2220]
Anyone like this? (For GitHub, GitHawk signature should remain the same) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a><img src="https://github.com/GitHawkApp/GitHawk/raw/master/Resources/Assets.xcassets/splash.imageset/splash%403x.png" height="15"> </sub>

**Comment by Huddie** [comment]
For those on GitHawk 
<img width="362" alt="screen shot 2018-10-03 at 12 14 41 am" src="https://user-images.githubusercontent.com/10662471/46389666-54d3c880-c6a1-11e8-9a21-39889eff0243.png">

**Comment by j-f1** [comment]
I like how it gets converted into an icon next to the timestamp currently.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@j-f1 That won’t change. See my parenthesis. This would only effect the way it appears on GitHub not GotHawk

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I think it’s a little noises tbh

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
