### ISSUE TITLE
No items in inbox

### ISSUE THREAD

**Issue by d-ivashchuk** [GitHawkApp/GitHawk#2225]
**Description**
For some reason I always have zero inbox in the app
**To Reproduce**
Just open the app section `inbox`
**Expected behavior**
See notifications and mentions 

**Smartphone**
Iphone XS ios12

Maybe I didn't do something to allow notifications to be sent. I enjoy app very much and want it to work properly. Thanks for making it!

**Comment by BasThomas** [comment]
Can you see any notifications on https://github.com/notifications ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d-ivashchuk** [comment]
Nope, I guess I need to tick web notifications to see them in GitHawk. I guess it’s solved, sorry my mistake. Thanks for quick answer!
