### ISSUE TITLE
Extra space at bottom of pull request status view

### ISSUE THREAD

**Issue by j-f1** [GitHawkApp/GitHawk#2229]
Screenshot:

![](https://user-images.githubusercontent.com/25517624/46486220-4b467f80-c7cb-11e8-81fc-ea517e8b95ae.jpeg)

**Comment by rnystrom** [comment]
That’s because the floating button isn’t visible. Seems like we should add bottom inset only if we’re gonna show the button.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
Closed by #2761
