### ISSUE TITLE
Infinite load on inbox

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2230]
I’ve hit this a few times. Flex doesn’t show the inbox request finishing. There’s nothing to cancel and reload either so I have to force quit the app.

Anyone else?

![GitHawk Upload by rnystrom](https://i.imgur.com/fJtAcPQ.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1538537771)
Device: iPhone X (iOS 12.0)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
Just happened to me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bmeverett** [comment]
I'm seeing this too

**Comment by rnystrom** [comment]
Everyone on TestFlight right? Not prod?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
I’m on TF

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
Me too, on TestFlight.

**Comment by BasThomas** [comment]
Haven't seen this, weird. Anything going on with GitHub maybe?

**Comment by rnystrom** [comment]
My guess is its [this commit](https://github.com/GitHawkApp/GitHawk/commit/cf09107576b0c6e771e01badffaed024046807ae#diff-c79f1ba47b613ca4b8a3451abd4ca1f1) that just doesn't load when refreshing from [app background](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Notifications/NotificationModelController.swift#L55). I'll admit this was a hack in the first place.

The issue I'm trying to avoid is double-fetching the inbox, which has been happening for a while for badging:

- [App background fetch events](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Systems/AppRouter/AppController.swift#L52)
- [Notifications fetch](https://github.com/GitHawkApp/GitHawk/blob/3ebd279d555c9e139637e68c53d2a7d87802d4c7/Classes/Notifications/NotificationsViewController.swift#L85-L94) called eventually via [viewDidLoad](https://github.com/GitHawkApp/GitHawk/blob/3ebd279d555c9e139637e68c53d2a7d87802d4c7/Classes/Systems/Feed.swift#L79)

To the user, this doesn't do anything wrong. But we're wasting network requests as well as API rate limits.

I tried originally to just avoid `.view` being accessed in the controller (prevent `viewDidLoad` being called), but the `UISplitViewController` internals access the view no matter what. I don't want to inject some state when launching from a background event either in case the user actually opens the app before the process is killed.

This is a tough. 🤔

**Comment by rnystrom** [comment]
Open to ideas on how to avoid double fetching from background fetch events.

**Comment by BasThomas** [comment]
Oh wow, that's good to know. Ugh.
