### ISSUE TITLE
Manager button feedback

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2231]
I want to add some feedback to the manager button. 

Reason by example: 
1. Open an issue or PR which has comments greater than view size.
2. Scroll to top
3. Close the issue/PR

Did it get closed? 

It did, but there’s really no way of you knowing unless you scroll down and see the new cell added that says closed. 

Same goes for reopen, lock...etc

Options:
- Some banner appears indicating you closed/etc the issue/PR
- Auto-scroll to bottom after data updates
- Someone else has an idea

Thoughts? Ideas?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Auto scroll seems like the simplest. Agree with this!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Cool! I’ll take this one then! Thanks for the feedback 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Taking this one, now I want this feature

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Sorry 😔I’ve been swamped at school. Thanks for taking care of it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
