### ISSUE TITLE
Sync GitHub stars to local bookmarks automatically

### ISSUE THREAD

**Issue by jdmarshall90** [GitHawkApp/GitHawk#2235]
Could this be added please?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone X (iOS 12.0)
TestFlight: false
</pre>
</details>

**Comment by BrianLitwin** [comment]
this sounds like a good idea, wouldn't be too much trouble to make/ seems like an intuitive feature.. others thoughts? I'll work on this if there are no objections

**Comment by rnystrom** [comment]
Stars will eventually just be part of starred repos in your profile. I don’t think we should conflate the two.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
