### ISSUE TITLE
Show my repositories

### ISSUE THREAD

**Issue by jdmarshall90** [GitHawkApp/GitHawk#2236]
A tab that has all of the currently logged in user’s repositories would be nice.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone X (iOS 12.0)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
Gonna close this in favor of #2106 and #317 which are to build the user profile tab (which will have the user's repositories in)
