### ISSUE TITLE
can not find starred project

### ISSUE THREAD

**Issue by hedaobaishui** [GitHawkApp/GitHawk#2239]
cannot find starred project in my account

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPad7,5 (iOS 12.0)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
See #317 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
