### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by bmeverett** [GitHawkApp/GitHawk#224]
Not sure how feasible this would be with the API, but have notifications received via push. Even better, customize the repos/types of notifications you would like to recieve pushes for.

**Comment by Sherlouk** [comment]
This would require quite a lot of work in terms of having to authenticate users and store this in a web server polling regularly for new notifications in order to send a notification - think we’ll have more luck with background fetching on devices, which i know there’s a ticket for!

Would love this though

**Comment by rnystrom** [comment]
Yup, I feel you. I think a good temp mid solution would be a bg job that badges the app. We could even schedule **local** push notifications with the bg job too! But for me personally pushes would be annoying. 

However we could put all of this in settings.

**Comment by Anviking** [comment]
Is a polling server desired more long-term? I made one for exactly this purpose once 😅  . Not sure how sane my approach was, but taking another look at it would be interesting.

**Comment by shaps80** [comment]
Sometimes (like with polling services) I tend to consider the UX in order to understand what solution would be best.

For me, the question to be answered would be how long do people spend in the app for a single session. Because if like me its a few mins at a time, polling would probably be overkill tbh.

--- 
I'm 100% with he background fetches though. I've been doing thorough testing with this over the past couple of weeks and found it to be quite reliable. Triggering almost every hour or so with my app that I'm using a couple of times a day. 

I think its a viable long term solution as well tbh.

**Comment by shaps80** [comment]
Notes I found on background fetch. (Some from an Apple fellow)
Background fetch is largely undocumented, however a few of tips I've come across are things like Application Launch times and Energy Usage.

---
By adding this env var, you'll see a bunch of statistics when your app launches in Xcode's debug console. It can be really useful. They suggest your app should be able to launch in under 400ms I tend to aim for 2-300 personally.

<img width="324" alt="screen shot 2017-08-12 at 13 26 57" src="https://user-images.githubusercontent.com/251310/29240685-3a93fdf0-7f62-11e7-8d15-48f6cb1249af.png">

---
Energy Usage can obviously be checked from Xcode or Instruments. 

--- 
The background fetch API (as I'm sure you know) has a completionHandler you need to call when you're done. Previously I had mostly just called it with `.newData` in all cases. This was a mistake. Not sure exactly how it ranks this, but its important to call `.noData` when there wasn't any. Improves fetch intervals.

---
The main thing is to keep these numbers low. If the app can be launched quite quickly, use little battery and finished fairly quickly the system tends to give you more background time. 

Again this is in my own limited testing, but I have worked on several apps with successful background fetch implementations over the years.

**Comment by rnystrom** [comment]
+1 that the goal is to badge the app and optionally notify when there are new things when **not** in app. Lets stick with bg tasks for now.

**Comment by rnystrom** [comment]
Badges added but I'll leave this open for now to track adding local notifications. I think that'd be cool. Semi complicated because we have to track what has already been notified. Also probable batching them into one that says like "4 new notifications".

Maybe we can even split the notifications by repo?

**Comment by dkhamsing** [comment]
@rnystrom very cool

question: the app got a badge on the home screen but when I opened it, got the :tada: icon and had to pull to refresh.. is that the current way it works?

**Comment by Sherlouk** [comment]
Also I have the badge turned off, but I'm still getting it showing up 😔

**Comment by dkhamsing** [comment]
@Sherlouk can u turn it off with Settings / Notifications / Freetime .. uncheck Allow Notifications

**Comment by Sherlouk** [comment]
I get that, but as an app owner myself having users turn it off at that level is really bad in case you want to take advantage of notifications in other ways further down the line - Should have better in-app control over that setting.

There is also a toggle which is worded, or at least interpreted by me, as "Turn off the badge" - Which doesn't work

**Comment by dkhamsing** [comment]
Right right, I meant for you to fix this in the meantime :)

**Comment by rnystrom** [comment]
@Sherlouk so you gave it disBled in settings but it's still badging? Ah shit I think I know why. Will fix.

**Comment by gingerbeardman** [comment]
Local notifications would be very welcome.

**Comment by rstockm** [comment]
+1 for local notifications.

**Comment by Binlogo** [comment]
#Ghjihvf ghjijvfdddvyhbbv

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schrodincat** [comment]
I’m absolutely 100% for real server-side push-notifications. I know GitHub not a messaging service, but reaction time is still important and fast response can help to get conversions going faster and therefore resolve issues faster. I’m actually baffled GitHub itself still hasn’t provided an official app with push.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
I use [CodeHub](https://github.com/CodeHubApp/CodeHub) for notifications. I'm not sure how they do it but I had to pay to activate the feature. I just have to remember to open GitHawk instead.

**Comment by schrodincat** [comment]
Here you go, it’s open source: https://github.com/CodeHubApp/CodeHub-Push

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
Looking at CodeHub-Push (thanks @schrodincat !) it seems their approach is _per-user_ (me, you, etc.) not _per-app_ (GitHawk), so rate limiting should not be an issue?

**Comment by Sherlouk** [comment]
The rate limit issues I've been seeing are per user 😔 we should, and definitely in the past have, look at optimising stuff but ultimately if you open 50 notifications that's a lot of api calls! Not much we can do about that!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@rnystrom With this merge, will we **receive push notifications** from GitHawk on iOS **for any update in our repo's on Github?**

**Comment by gingerbeardman** [comment]
@mesqueeb anything you receive a notification for on the website.
