### ISSUE TITLE
Can’t search forks

### ISSUE THREAD

**Issue by mvrozanti** [GitHawkApp/GitHawk#2240]
And also I cannot some find my own repos.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone 5s (iOS 11.4.1)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
@mvrozanti try searching mvrozanti/ (with the slash)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mvrozanti** [comment]
[I did](https://imgur.com/a/YCx4tHd]

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Without the st. Just mvrozanti/. I searched and got a lot of results 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mvrozanti** [comment]
I also tried searching for mvrozanti/ and while it did return many results, `st`, for instance did not show up.

**Comment by rnystrom** [comment]
@mvrozanti ya that should show up like anything else. Is it a private repo?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mvrozanti** [comment]
It is not.

**Comment by rnystrom** [comment]
Could be something with the search API or query that doesn't show fork results? That would be really strange...

**Comment by mvrozanti** [comment]
Actually, some "self-owned" (not forks) repos are missing as well. Example: [rastreamento-correios](https://github.com/mvrozanti/rastreamento-correios)

**Comment by mvrozanti** [comment]
Maybe it's my iOS version? Pardon my ignorance it's an old phone.

**Comment by Huddie** [comment]
I’m on iOS 12 and missing. Also doesn’t seem like that would be it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
Looks like GitHub search will ignore fork repos by default. If we want to see the forked repos we have to specify that in search query like `fork:true` or we can even search only for forked repos by `fork:only`.

Checkout more on [Searching for Repositories](https://help.github.com/articles/searching-for-repositories/)

I also fired up GraphQl Explorer to check and was able to get forked repos as like mentioned in docs.

```
query {
  search(query: "fork:true rizwankce/", type: REPOSITORY, first: 100) {
    repositoryCount
    edges {
      node {
        ... on Repository {
          name
        }
      }
    }
  }
}
```

**Comment by mvrozanti** [comment]
That still wouldn’t explain non-forks not appearing though

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
@mvrozanti I was able to get that as well in search. ![GitHawk Upload by rizwankce](https://i.imgur.com/FeYqcth.jpg)


We can compare the search with github search and cross verify it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
I was able to get my forked repo just by entering `Rizwankce/ fork:true` so there is no difference between Github search and Githawk. But it's tricky to remember all search keywords. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mvrozanti** [comment]
@rizwankce ok rastreamento-correios is actually there, my bad; I thought I didn’t see it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
But this should be either added by default or we need a filter option. Users shouldn’t have to know to add /fork:true. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mvrozanti** [comment]
Maybe only disable or unfilter if they want?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
🤷‍♂️I feel people’s expectations are that forks appear

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Let’s default to include forks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
