### ISSUE TITLE
Merged icon

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2261]
Any reason we use the pull request icon colored purple instead of the merged icon ?

Note the proper merged icon is used everywhere (PR/Labels) but inbox/bookmarks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Oh that seems like a bug. Would love a fix!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
I’ll take it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom So the icon comes from an extension on NotificationType. NotificationType has PullRequest but doesn’t have the state (merged, closed..).
I could switch the extension to be on the model which has the state information but that wouldn’t work with Bookmark who’s model doesn’t have the state. 

I could change NotificationType to have pullRequest and pullRequestMerged but that would mean changing v3notificationSubject since the NotificationType is made using the rawValue of V3NotificationSubject. This doesn’t feel like a great solution to me but let me know. 

I could do a simple check right before getting the icon and see if the type is pull request and see if state is merged. I’d have to do some manual check by bookmark as well. This seems like a patch not a great fix.

I just want to make sure I approach it in the best way since things seem tight nit right now. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom you want to keep the icon in the bookmark section as is and fix the merge icon in the inbox?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
