### ISSUE TITLE
New beta tester on iOS 12.1 not receiving notifications

### ISSUE THREAD

**Issue by ijm8710** [GitHawkApp/GitHawk#2265]
* Notifs are set to web on GitHub
* Push notifications are toggled on in GitHawk and in iOS Notification settings 
* Have created test cases and waited hours; feel free to test on here. They populate in notification inbox list but no push notification ever comes
* Happy to provide any other detail requested

**Comment by rnystrom** [comment]
Are there items in your inbox?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Yup. I’ll clarify in OP that that’s what third bullet referred to

**Comment by ijm8710** [comment]
Waited 11 minutes now and nothing btw...I’ve waited 2-3 hours yesterday on other test

**Comment by ijm8710** [comment]
Do you have ability to send test notifcations from server? Not actual github replies but just confirming your server is working to me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@ijm8710 There is no server. There’s a great article on how GitHawk implements notifications. Don’t have the link on me but it’s on the GitHawk blog which can be found on the GitHawk website! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Is there anything else I can provide or do to diagnose this?

**Comment by ijm8710** [comment]
Can you message me and I’ll let it sit and see please

**Comment by Sherlouk** [comment]
👋

**Comment by ijm8710** [comment]
So, the notofs pull in but only once I open the app. Just realized something. Perhaps is having background refresh off preventing your pseudo-notificaction system from working?

**Comment by Huddie** [comment]
@ijm8710 ya that’s possible. Pretty sure background refresh is essential. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Let me test once more. Can one of you comment on this again please

**Comment by ijm8710** [comment]
Made no difference. I don’t think that’s it

**Comment by ijm8710** [comment]
Badge only appears when entering app. Is there something I do that should control the frequency of the fetch

**Comment by Huddie** [comment]
Well if your badges aren’t updating until you enter then (to my knowledge) most likely a bg refresh issue. 

Your settings look like this?
![GitHawk Upload by Huddie](https://i.imgur.com/6YXpm7a.jpg)![GitHawk Upload by Huddie](https://i.imgur.com/sFAQego.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
>Badge only appears when entering app. Is there something I do that should control the frequency of the fetch 

@ijm8710 we use iOSs minimum interval for bg fetch, but the OS decides when to trigger, we have no control. Updates won’t be on real time, but for me at least, they are pretty quick (within the hour).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@ijm8710 Are you on low-power mode by any chance?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
@Huddie settings are correct for what you said (I’ve be been beta testing for years. I’m the lead tester for reddit, run their entire tracker on the beta subreddit and speak to them weekly so I’m pretty tech savvy :))
Low power mode can’t be on for bg-refresh but like I said that didn’t make a difference

@rnystrom
Yeah I’ve tried waiting several gours. No dice. Not sure if you want logs or whatever. Again 12.1. Toggled push in and off. Nothings getting it to work. Shocked it’s just me

**Comment by rizwankce** [comment]
to make a note here. I have enabled the push notification from TF app and I never got any notification from the app. 😢 

I don't know how OS decides to send notifications.

**Comment by ijm8710** [comment]
Hey so @rnystrom complete understand that some bg component is required at this time, but was unclear on if bg-always will be required or if there’s some permissions setting that’s adjustable that would allow for bg-wifi to work as well. Conceptually, I do not see the difference assuming the user is in fact on wifi

Also not related to being an issue, but how is your experience with bg-always on batttery life. My battery is just ok, would this likely cause a noticeable drop in battery life, something almost negligible or something somewhat I between the two?

**Comment by rnystrom** [comment]
@ijm8710 re: battery, haven’t ever had an issue. I use low power mode a lot tho and know that pushes won’t work in that case.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Oh cool, we can detect low power mode! Maybe we show something in your inbox that if you have notifications enabled, they wont appear?

https://useyourloaf.com/blog/detecting-low-power-mode/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
I wish android-sequel there was the option to manually approve certain processes like a bg exception for githawk fetching

@Rnystorm, still haven’t seen your remark on this. I understand notifications will not work when low power mode is on (bg is off). And they will work when bg is fully on. But, again, they do not work when bg is on wifi mode even if you’re on wifi. Have you looked into if there is a permission relating to this. Is there any way around that specifically. If I’m on wifi and bg is enabled, makes no sense why my setting has to be bg-always still and not just by-wifi whole on wifi.

**Comment by ijm8710** [comment]
I’m curious if it’s the “cellular data” portion of background refresh and not the background refresh in general that does the fetching. Not sure if this comment makes sense fully.

**Comment by ijm8710** [comment]
@Rnystrom were u able to test what I meant?

**Comment by Huddie** [comment]
@ijm8710 you should be able to set bg refresh to whatever you want in your fork

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
@huddie can you expand upon that..I’m saying that if you have bg set to work on wifi it won’t work on wifi...don’t think this is an edge axe but basically a major roadblock for notifcations

**Comment by Huddie** [comment]
@ijm8710 I’m saying if @rnystrom is busy and you want to test it out on different “settings”/frequency of bg refresh, you can do it in your personal fork of the repo (if you’ve forked it). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@ijm8710 ah. Well if you test it and confirm your hypothesis please let us know.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
I have confirmed!

**Comment by ijm8710** [comment]
I’ve tested this religiously and it’s 100% @huddie

**Comment by ijm8710** [comment]
That’s why I’m saying this is not an edge case

**Comment by Huddie** [comment]
@ijm8710 the best I can suggest is:
1. Create a PR solving this which I’m sure will be accepted 
2. Post an article or something that corroborates that bg-refresh’s cellular is different from bg-refresh on WiFi. To me it sounds interesting that something would work on cellular and not WIFI. I could see the opposite. Since this is a new feature (push notifications), I think there could be 100 things that are causing changes and since it’s working for me and others, it seems unlikely that it’s WiFi related. Again, not saying your wrong. Just suggesting you find an article or steps to reproduce that make it clear that this is the issue.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
@ijm8710 let me do some test on that. 

I have never received any push notification so far from GitHawk. Also I have been using the app at least more than one time in a day.

**Comment by ijm8710** [comment]
For some reason, this may be working on this beta version for bg-wifi. Not sure what has changed. Not sure if @rizwankce and @mesqueeb are starting to get them coming in as well as they weren’t before.

Out of curiosity, is the “intention” that if you’re in lower power mode, once you return to having bg, should the notifications that you missed in between be fetched to roll in or would it only be those subsequent to having fetch turned back on?

**Comment by mesqueeb** [comment]
I can confirm that on the latest beta and the one before that I think I now successfully receive notifications. I truly love GitHawk now and cannot live without it anymore.

**Comment by rizwankce** [comment]
I did some test from my side and I started receiving push notifications now. 

Looks like os decides the frequency of fetch based on the app usage. I was able to get push on both wifi and mobile data. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
@rizwankce was yours working on just bg-wifi as well or being on wifi for bg-always. It’s super inconsistent for me right now

**Comment by rizwankce** [comment]
@ijm8710 I have selected "WiFi & Mobile Data" in Settings and was able to receive notifications on both WIFI and Mobile data today.

**Comment by ijm87102** [comment]
Testing just to confirm that this is still working better :)

**Comment by ijm8710** [comment]
@rnystrom hopefully last time I ever tag you on this thread. I think the bg-wifi bg-always thing is no longer an issue, but hey I wasn’t the only one-Mesqueeb and rizwankce had issues as well that fixed themselves at same time

Revisiting the last useful piece from this thread, I do think an alert that if you have low power mode enabled, notifications will not come (as bg is completely off) would be nice!

**Comment by rnystrom** [comment]
I did add these introductions to the new settings info button. Let’s see if anyone has as much trouble with notifications before doing much more.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
