### ISSUE TITLE
Scroll to last read message on push notification open

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#2269]
https://twitter.com/_ryannystrom/status/1050070500708376576

Not 100% sure on the exact functionality but I believe from when I looked previously that the notification payload does include the trigger message sometimes though this might not be accurate.

Alternatively we could store within the app the last seen message for each issue/PR? Then just scroll to that? I could imagine something similar to Slack UI as well (screenshot below) where it tells you what's new versus what you have already seen. Makes it a lot easier IMO

![img_8dd6e96916bf-1](https://user-images.githubusercontent.com/15193942/46753554-18632680-ccb8-11e8-84b0-2821c9cbc5f9.jpeg)

**Comment by rnystrom** [comment]
It does but its base64 encoded and basically a private API that could change at any time. If someone feels strongly and wants to take this on I'm all for it, but not a priority for me atm.
