### ISSUE TITLE
Infinite load still a thing?

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2284]
Just hit this. Will debug. Ugh! Follow up from #2230

![GitHawk Upload by rnystrom](https://i.imgur.com/QtA7Bfz.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1539400019)
Device: iPhone X (iOS 12.0.1)
TestFlight: true
</pre>
</details>

**Comment by j-f1** [comment]
Looks even weirder on the 8 since the spinner overlays the emoji.

**Comment by rnystrom** [comment]
Just hit it again. Probably need to build a state machine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Really weird, I just got a notif for this (be it delayed) while on power saver mode. Reason I’m mentioning it here is it also gave me this issue as well when I tried to view it in inbox.

**Comment by Yonodactyl** [comment]
Finding my way around the refresh controls in the Feed class seems to be challenging.
I do have a question: Where does the application call refreshHead?

**Comment by rnystrom** [comment]
@Yonodactyl the main refresh mechanisms are `Feed`, `FreedRefresh`, and `BaseListViewController2`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
