### ISSUE TITLE
Hashtag automcomoletion experience seems like it doesn’t fully index right (adding video momentarily)

### ISSUE THREAD

**Issue by ijm8710** [GitHawkApp/GitHawk#2295]

**Comment by ijm8710** [comment]
https://streamja.com/MkEl

**Comment by rnystrom** [comment]
Unfortunately we’re constructed to GitHubs search API here. It’s def not ideal, but unless someone has an alternative API we can’t improve it too much 😞

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
@rnystrom just did the same on desktop with their native api and don’t encounter the same experience? https://streamja.com/mnPK

**Comment by ijm8710** [comment]
@rnystrom mind watching the video when you get a chance. I do think this is legit issue that should at least be open

**Comment by rnystrom** [comment]
I’m saying we limited by the API, and there’s only so much we can do. GitHub controls the API and doesn’t provide any ranking coefficient to my knowledge, so the best solution would be to concoct a ranking algorithm or extra search queries on the client which makes everything more complicated.

As a rule of thumb, GitHawk is bound to the APIs available. Only rarely would I advocate stretching and hacking our client to add features that don’t exist in a single API call (inbox status loading is a good example of bending the rules).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
