### ISSUE TITLE
Been seeing this OAuth app access restrictions alert quite often

### ISSUE THREAD

**Issue by ijm8710** [GitHawkApp/GitHawk#2299]
- Just attempting to post a comment several times, I was rejected. Tried force quitting and restarting app and didn’t let it post. But, when posting the same comment in another third party GitHub app, it worked first try
- Have also seen this error message when closing and reopening an issue. At first I thought it was restricted access per the repo, but actually I was later able to close reopen successfully in that same repo on another day.

Essentially there are inconsistencies here

![GitHawk Upload by ijm8710](https://i.imgur.com/rNngr8H.jpg)

**Comment by ijm8710** [comment]
Digging around this may relate to #2165 and some others, but haven’t found a firm answer as to why in any of the. Again, worked flawlessly in another third party app, trying to post same comment so doubt its github related.

**Comment by Huddie** [comment]
Ya, same issue as #2165 most likely 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Closing as seems like a dupe
