### ISSUE TITLE
Searching by issues is non-chronological (confirmed this behavior is different from native)

### ISSUE THREAD

**Issue by ijm8710** [GitHawkApp/GitHawk#2301]
![GitHawk Upload by ijm8710](https://i.imgur.com/9mv9Ceo.jpg)

**Comment by j-f1** [comment]
Looks like the dates the issues were opened aren’t in reverse-chronological order.

**Comment by BasThomas** [comment]
Oh right, #1840 is weird. 🤔

**Comment by ijm8710** [comment]
Yeah this is moreso a “bug” than a question. Can we set tags-in-app btw?

**Comment by BasThomas** [comment]
Yes, if you have access via the Options button (lower right in an issue/pull request, blue with three horizontal lines)

**Comment by ijm8710** [comment]
@BasThomas thanks I only have close reopen access. Is this basically a mod (or whatever GitHub terms it) feature?

**Comment by BrianLitwin** [comment]
I've noticed this before in the GraphQL api, sometimes you can't count on the issues being sorted chronologically. Easy to repro: 

<img width="299" alt="screenshot 2018-10-16 16 10 21" src="https://user-images.githubusercontent.com/26695477/47044604-a6c72480-d15e-11e8-9d9a-34786a033d34.png">

@BasThomas Is this worth a quick PR to sort them after they're fetched?

**Comment by BasThomas** [comment]
I think that makes sense, yep :)

**Comment by BasThomas** [comment]
> @BasThomas thanks. I only have close reopen access. Is this basically a mod (or whatever GitHub terms it) feature?

Oh that is just GitHub.

**Comment by ijm8710** [comment]
@BasThomas not following 🙈

**Comment by BasThomas** [comment]
Yes, because you're not a member or owner of the GitHawk organization.

**Comment by ijm8710** [comment]
@BasThomas gotcha last question, is that user-joinable any time or must it be approved or granted; by “admins”

**Comment by BasThomas** [comment]
@rnystrom can help you out I think :)

**Comment by Huddie** [comment]
@BasThomas Not sure it’s for members. I’m a member and I can only open and close issues in which I’ve created. Otherwise no manager button. Maybe different member levels or something 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I guess we shouldn’t close until it gets merged?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
@rnystrom thanks to @BasThomas for filing supposed fix, but intermittently I saw him tag my post as he’s done others. Curious, is this tagging ability allocated to just super-users essentially?

**Comment by BasThomas** [comment]
>@BasThomas Not sure it’s for members. I’m a member and I can only open and close issues in which I’ve created. Otherwise no manager button. Maybe different member levels or something  ...

@Huddie pretty sure it is, as there’s only members and owners. 

@ijm8710 so you’d have to be a member or owner to do that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@BasThomas So there must be different levels within those 2 groups. Cause I’m certain I can only open and close my own issues and I’m pretty certain I’m a member. So I guess within the member section there are different levels

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya folks added to the org are just members. @BasThomas is an admin. BUT I’d def like all members to be able to run the project. Let me look into that ASAP

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
