### ISSUE TITLE
Sign out only the current user

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2302]
**Describe the solution you'd like**
When you sign out, all user sessions are removed. It would be nice if it would only logout the current user session.

**Describe alternatives you've considered**
Leave it as-is.

**Additional context**
I didn't look at the implementation and wanted to make the button more user friendly by including the user that would be logged out... then I found out we log out all users (and we warn we do).

All I added for now was the following in `SettingsViewController`'s `viewDidLoad()`:

```swift
if sessionManager.userSessions.count > 1 {
    guard let userSession = sessionManager.focusedUserSession else {
        // If this won't be hit, it can be replaced with a force unwrapped
        // focused user session or a `fatalError` instead.
        return assertionFailure("Expected to have a focused user session")
    }
    signOutCell.textLabel?.text = "\(Constants.Strings.signout) \(userSession.username)"
}
```

**Comment by j-f1** [comment]
How about swiping left on the accounts to log them out using a similar UI to swipe-to-delete elsewhere on iOS?

**Comment by BasThomas** [comment]
That's another option, but would make it harder to find how to logout, which I'm not sure is a tradeoff we shoud make.

**Comment by Huddie** [comment]
I think @j-f1 suggestion is fine. We can have logout where it currently is as a universal logout (logout of app) and the under accounts you can logout of individual accounts. If you logout of all accounts in the accounts page, it auto logs out of the app

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
