### ISSUE TITLE
Blog about routing library evaluation and our "solution"

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2306]
See https://github.com/GitHawkApp/GitHawk/issues/2105#issuecomment-430376007

**Comment by rnystrom** [comment]
Can we move this to the blog repo?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Oh right that’s a thing now. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Doesn't have issues 😭

**Comment by rnystrom** [comment]
Oh lol, I’ll turn that back on

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
