### ISSUE TITLE
Read layer does not fully expand in horizontal notification cell

### ISSUE THREAD

**Issue by drewvolz** [GitHawkApp/GitHawk#2308]
**Describe the bug**

I think the width of the `readLayer` for `NotificationCells` is not being recalculated on rotation.

**To Reproduce**

If you have notifications, you can use the inbox view. Otherwise...
1. Tap on the `...` menu in the top left corner
2. Tap the `View All` button
3. Rotate the view from portrait to landscape
4. Notice the layer not being drawn to the full width of the cell

**Expected behavior**

I would expect for the `readLayer` to color the entire width of the landscape `NotificationCell`.

**Screenshots**

✅ Opening in landscape

<img width="812" alt="before-rotate" src="https://user-images.githubusercontent.com/5240843/47120499-253dc800-d22c-11e8-99b4-7a2a0d6f8113.png">

❌ Rotating to landscape

<img width="812" alt="after" src="https://user-images.githubusercontent.com/5240843/47120497-24a53180-d22c-11e8-9283-e138481fbaf9.png">

**Smartphone:**
 - Device: iPhoneX
 - OS: iOS12.1
 - Version: 1.23.0

**Comment by Huddie** [comment]
Nice eye 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Bummer! Good find.
