### ISSUE TITLE
Navigation bar title resize

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2329]
When opening a view who’s navigation bar title is:

Organization/User
Repo

The text starts at one font size and then shrink (quickly) to a smaller text size. I’ll try getting a gif if nobody can see this on their own.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah I saw this too

**Comment by rnystrom** [comment]
Ah I see it too. Closing as #2331 is the same bug

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
