### ISSUE TITLE
Feature request: clone repo in Working Copy

### ISSUE THREAD

**Issue by jdmarshall90** [GitHawkApp/GitHawk#2342]
Working Copy appears to have x-callback-url support for this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Love it! Could fit this in the “...” bar item

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by palmin** [comment]
The most suitable url to use is probably

    working-copy://show?remote=https%3A%2F%2Fgithub.com%2Fgit%2Fgit.git

that shows the given repository inside Working Copy if already cloned and will otherwise show a cloning dialog.

**Comment by Sherlouk** [comment]
Will need to make sure we use can open to make sure the user actually has WC installed too (just a reminder)

**Comment by palmin** [comment]
@rnystrom I would love to have this working and you can assign it to me if you like.
