### ISSUE TITLE
“Issue can not be found” has no failure haptic

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2343]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1540088759)
Device: iPhone X (iOS 12.0)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Do the other errors have haptics?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Not sure

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Just wondering where this issue comes from, like if it’s there in others but missing here. Should keep everything consistent.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
Yes they do.

**Comment by j-f1** [comment]
Try 👍ing prettier/prettier#4881.
