### ISSUE TITLE
Override keyboard to begin filter query with lowercase

### ISSUE THREAD

**Issue by ijm8710** [GitHawkApp/GitHawk#2345]
Filters such as is:open do not work if started with uppercase text. I’ve seen keyboard overrides that force full-caps, do you see feasibility in overriding keyboard to begin lowercase. Assuming it’s a relatively quick fix but extremely useful as majority of the time I type a query and have to double-check why I’m getting no results

**Comment by rnystrom** [comment]
Quick q: the “is” can’t be caps or the search term? We should probably just lowercase the whole query.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
