### ISSUE TITLE
How safe and secure are Githawk?

### ISSUE THREAD

**Issue by ma66nus** [GitHawkApp/GitHawk#2352]
**Is your feature request related to a problem? Please describe.**
We want to be as secure as possible even though it is not possible to be 100% safe and secure anywhere on the Internet.

**Describe the solution you'd like**
I wonder if Githawk is as safe and secure as Github if I use Githawk with two step authentication?

**Describe alternatives you've considered**
If not I continue to use Github on the web.

**Additional context**
Would be nice with a text describing how safety works for Githawk :-)

**Comment by BrianLitwin** [comment]
@ma66nus Here's our [security info](https://github.com/GitHawkApp/GitHawk/blob/master/SECURITY.md)

**Comment by ma666nus** [comment]
Many thanks :-D

**Comment by rizwankce** [comment]
May be we can have the `SECURITY.md` as a FAQ inside the app Settings. So users will have clear idea for the security concerns. Most of the users from App Store don't really visit our repo page to read markdown files. thoughts? @rnystrom

**Comment by ijm8710** [comment]
I feel the third paragraph on the push notifications disclaimer handles it

**Comment by rnystrom** [comment]
I feel like the `SECURITY.md` + disclaimer is enough for now. If we get more queries let's add something in-app.
