### ISSUE TITLE
Can’t make an comment to an issue

### ISSUE THREAD

**Issue by jukben** [GitHawkApp/GitHawk#2354]
“Something went wrong”

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone 7 Plus (iOS 12.0.1)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
Check #2224 #2187 #2165. Could be related 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jukben** [comment]
It's this issue. https://github.com/GitHawkApp/GitHawk/issues/2224#issuecomment-426740055

We should get a better error messaging for such a case. Wdyt?

**Comment by rnystrom** [comment]
@jukben try the TestFlight version, it has better error messaging
