### ISSUE TITLE
Reaction emoji doesn’t update in split view

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2356]
If your in split view and set a new default reaction in settings the emoji icon won’t update in the main view (settings). 

This is because the cells only update on viewDidAppear.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
Ah! Didn't notice that when I added the reaction vc to split view. I'll take care of this 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
