### ISSUE TITLE
Hide try beta when user is on TestFlight

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2362]
Not sure if we do this already. Seems like we don’t. But maybe we can hide the try beta if it doesn’t apply (the app is a TestFlight build)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
#2351

**Comment by Huddie** [comment]
@ijm8710 @rnystrom Unless I’m missing something,   The PR referenced is about telling users they are already on TestFlight. My suggestion here is hiding the cell since it’s unnecessary 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Fair

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
