### ISSUE TITLE
Cannot open issues

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#2364]
Sometimes I cannot open issues from the Inbox or Inbox Archive. 

On tap they become highlighted, but they do not open. 

Force quitting app solves this.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1540303812)
Device: iPhone 6s (iOS 12.0.1)
TestFlight: true
</pre>
</details>

**Comment by gingerbeardman** [comment]
https://imgur.com/a/T0CxmTe

**Comment by BrianLitwin** [comment]
Vid seems reminiscent of #2289

**Comment by gingerbeardman** [comment]
Yes indeed.

I'm using testFlight build, and probably landed there from a notfication.

**Comment by rnystrom** [comment]
@gingerbeardman do you have a repro for this? Would love to track it down.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Let’s keep this in #2289 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
