### ISSUE TITLE
Send comment starting with mention then comment again has wrong attributes

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2365]
Might be a fix in MessageViewController, need to dig

![GitHawk Upload by rnystrom](https://i.imgur.com/GsQpOPh.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1540303812)
Device: iPhone X (iOS 12.0.1)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
I’ve seen this as well. Meant to report it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
I also used to see an issue where the entire comment would be marked as a mention when it started with a mention and the comment failed to post.

**Comment by ijm87102** [comment]
Test

**Comment by rnystromtest** [comment]
@Huddie test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm87102** [comment]
Test
