### ISSUE TITLE
Crash on loginURL

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2367]
**Describe the bug**
Got an email from Crashlytics that [the loginURL](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Login/LoginSplashViewController.swift#L14) is crashing. I assume an incorrect token that causes an invalid URL @rnystrom?

**To Reproduce**
I assume logging out and in again in the latest version, so the URL gets used and it should crash. (Did not test)

**Comment by Sherlouk** [comment]
I believe this is just if you haven't actually done the setup steps defined here: https://github.com/GitHawkApp/GitHawk/blob/master/Setup.md

I also fell victim, easy to forget until it crashes 😅

**Comment by rnystrom** [comment]
Yup that should be it. Just tested and it’s working on TF

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
