### ISSUE TITLE
Ability to optionally opt-in to have bookmarks backed up, perhaps linked with iCloud

### ISSUE THREAD

**Issue by ijm8710** [GitHawkApp/GitHawk#2377]
Doubt you would want to make this the standard for privacy reasons, but for users that are not as worried in that regard, it would be cool to have a way to ensure bookmarks are being backed up.

**Comment by rnystrom** [comment]
I’m actually totally down with syncing bookmarks in iCloud! Great idea 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
