### ISSUE TITLE
Bookmarks show all issues in blue regardless of if issue was open or closed

### ISSUE THREAD

**Issue by ijm8710** [GitHawkApp/GitHawk#2379]
Is this intentional to not reflect from the list whether they are in an open or closed state?

**Comment by Huddie** [comment]
I was looking into this recently because of #2261. The bookmark model does not contain state so it just knows the notificationType.

I think changing this to match with notificationModel is a good idea. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
The complication here is that you will have to fetch data to get the latest status. Pretty big change. Might want to do this alongside a larger bookmarks refactor.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Just making a note that this also results in edited titles not dynamically reflecting

**Comment by rnystrom** [comment]
Good point

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
I’m sure I’m missing a few but at least bookmark items I’ve, for lack of a better word, bookmarked 🔥

Just aggregating everything for ease when project plan is laid out-

In addition to those from this post :

- icon reflect if item is open closed
- dynamically reflect edited titles

#2377 

- linked to iCloud for backup 

#1886 

- sort/reordering

#2441 

- personal request to reflect total count
