### ISSUE TITLE
Links not working across repos

### ISSUE THREAD

**Issue by muuvmuuv** [GitHawkApp/GitHawk#2385]
See: https://github.com/Unibeautify/unibeautify/issues/208

The last comment where steven points to another repos issue is not linking

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone 6s (iOS 12.0.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Might be the dash?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BrianLitwin** [comment]
Looking at this!

**Comment by muuvmuuv** [comment]
Thanks @BrianLitwin !

**Comment by Alyoto** [comment]
````

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
This is fixed.
