### ISSUE TITLE
Images have linebreak-sized gap above and none below

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#2396]
This causes the image to be near the text beneath it (which is a linebreak away) rather than the text above (as intended)

**Compare**

GitHawk
![GitHawk Upload by gingerbeardman](https://i.imgur.com/qrxlhFR.jpg)

GitHub Mobile
![GitHawk Upload by gingerbeardman](https://i.imgur.com/4EPOsGg.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.23.0 (1541192331)
Device: iPhone 6s (iOS 12.1)
TestFlight: false
</pre>
</details>

**Comment by gingerbeardman** [comment]
is his fixed? 

Issue I used in screenshot still has the odd spacing?

https://github.com/dear-github/dear-github/issues/331

**Comment by rnystrom** [comment]
Ah we added spacing below but now I see you’re also talking about the space above. Will take a look sometime.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
I’m ignoring the other items on here because I know I’ve pushed it too much but wouldn’t the line spacing referenced as the item with a 1 on my image example be similar to this?
https://github.com/GitHawkApp/GitHawk/issues/2274/%23issuecomment-/429837855

**Comment by rnystrom** [comment]
@ijm8710 I think the example 1 won’t be addressed but the others will have less spacing (soft breaks have tighter new lines)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
