### ISSUE TITLE
Unable to comment on any issue or PR

### ISSUE THREAD

**Issue by bkase** [GitHawkApp/GitHawk#2402]
Whenever I try to comment on an issue or PR, I get a "Something went wrong" error message and the message doesn't send.

If it matters: This is on a public repo within an organization that has not been granted access to githawk ( https://github.com/CodaProtocol/coda ).

Please let me know if you need any more info. Thanks!

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPhone X (iOS 12.0)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
@bkase could you try the TestFlight build and see if this still occurs? Also we have Flex enabled so we can get the raw response if necessary.

https://testflight.apple.com/join/QIVXLkkn

**Comment by ijm8710** [comment]
@rnystrom this probably relates to the credential stuff. I’ve been seeing this a lot

**Comment by bkase** [comment]
> Although you appear to have the correct authorization credentials, the `CodaProtocol` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, includeing how to whitelist this app, visit https://help.github.com/articles/restricting-access-to-your-organization-s-data/

So I guess I need to authorize Githawk in order to post? Any advice for justifying access to my organization?

**Comment by bkase** [comment]
(the quote was the error message when posted in the test-flight build)

**Comment by Huddie** [comment]
>@rnystrom this probably relates to the credential stuff. I’ve been seeing this a lot

@ijm8710 my thoughts 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Yup, closing in favor of #2165 

@bkase if you sign out and sign back in using a PAT w/ repo+user+notification scopes it'll go away. Atm appears to be an auth issue w/ the GraphQL API.

<img width="590" alt="screen shot 2018-11-04 at 7 09 14 pm" src="https://user-images.githubusercontent.com/739696/47972722-e487e080-e06c-11e8-8265-3411a607b57c.png">
