### ISSUE TITLE
inbox

### ISSUE THREAD

**Issue by tzh979215144** [GitHawkApp/GitHawk#2407]
The inbox can not show anything !
I need your help,thanks!

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.22.0 (1534395229)
Device: iPad6,11 (iOS 12.0.1)
TestFlight: false
</pre>
</details>

**Comment by tzh979215144** [comment]
Thank you for your help, I also want to know, when I was browsing a repository, can the directory tree  on the left as navigation bar?

**Comment by BasThomas** [comment]
What do you mean, @tzh979215144? I'm not sure if I understand what you mean.

**Comment by tzh979215144** [comment]
OK，thanks！

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tzh979215144** [comment]
I

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
