### ISSUE TITLE
Add issue referencing (#) to the action bar

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2408]
> Maybe we add it as an action bar key instead? I like having the return key
> 
> Sent with [GitHawk](http://githawk.com)

I'm leaning towards this now. Should I create a new issue in favor of this one?

_Originally posted by @BasThomas in https://github.com/GitHawkApp/GitHawk/issues/2183#issuecomment-431130380_

Opened in favor of #2183

**Comment by BasThomas** [comment]
This should add a `#` at the cursor point in the message and trigger the issue referencing interface.

**Comment by ijm8710** [comment]
Do you think numbering and/or quoting should also have action bar shortcuts ?

**Comment by BasThomas** [comment]
I don't feel like we should add them right now, or how they should work. Quoting is already in place for comments. Numbering is a bit trickier I think?

**Comment by BasThomas** [comment]
But feel free to open separate issues for them if you feel like it.
