### ISSUE TITLE
Can’t see all review comments

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2410]
Honestly haven’t used review comments so much on GitHawk so not sure if I’m doing this correctly but I don’t think I can see all the review comments in this post #2400. Not sure if it’s because there are a lot or for some other reason.

Example: it says Sherlouk commented but I don’t see any comments by him when I click to view, just all Bas. 

Is this an issue already? Or am I doing something wrong?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jazzbox** [comment]
Duplicate of #1760 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
