### ISSUE TITLE
iPad Pro support

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#2435]
I haven’t kept up to speed. What all needs to happen for this?

![GitHawk Upload by rnystrom](https://i.imgur.com/c1L99vv.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.24.0 (1542119087)
Device: iPhone X (iOS 12.1)
TestFlight: false
</pre>
</details>

**Comment by DevAndArtist** [comment]
I think you just need to link against iOS 12.1 SDK and ensure the app is already using safe area insets / layout guides. Currently the app is running in a so called compatibility mode. It will remain running in that mode even after you link against 12.1 SDK but only if you run it side by side with a different app in split view when the other app is not yet linked against the new SDK. That behavior just aligns the appearance of both apps. In every other case the app take advantage of the full screen. 

For more info you can check out this video:
https://developer.apple.com/videos/play/tech-talks/209/

**Comment by rnystrom** [comment]
> link against 12.1 SDK

Interesting. Let's try it out! Just bumped Bitrise to use Xcode 10.1. Pushing a new 1.24.0 GM build. Hopefully someone has an iPad Pro they can test!

**Comment by DevAndArtist** [comment]
I‘m a little confused. I installed the beta version before you opened the ticket. Now TestFlight send me a new notification that I can test a new app, yet it does not say that I can update it, which lets me to only open the app. The build version is 1542119087, I don‘t see any changes on my iPad Pro.

If it‘s the correct build then it did not work. I‘ll check tomorrow if I can compile the project on my device to test it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
@DevAndArtist Perhaps try closing and reopening TestFlight? You should get an &ldquo;UPDATE&rdquo; button.

**Comment by DevAndArtist** [comment]
Tried that already. Can someone share the build number of the new GM so I at least know which version to expect.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
FYI there's no new GM yet (and App Store Connect is down...). New build # will be 1542135906.

**Comment by rnystrom** [comment]
Ok GM is out on TestFlight. Please let me know how this looks/behaves on a Pro!

**Comment by DevAndArtist** [comment]
It works now :) ![GitHawk Upload by DevAndArtist](https://i.imgur.com/S9cjqac.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
