### ISSUE TITLE
Having issues previewing markdown

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2437]
I can’t seem to preview markdown. Anyone else?

Reproduce:
- Open new issue
- Start typing 
- Click preview
- Nothing 

Note: other bar button items work 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
Works fine for me.

**Comment by j-f1** [comment]
Ah, it’s only broken when _opening_ an issue, not when _commenting_.

**Comment by Huddie** [comment]
Ahh yes I see that now. Thanks 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ohh. Is that new? Has that ever worked?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
The issue also appears when editing a comment (OP or otherwise)

**Comment by ijm8710** [comment]
When trying to preview when opening a new issue intro-repository the preview button does nothing. Is this what was supposed to happen post-fix?

**Comment by rnystrom** [comment]
Hmm maybe that one got missed. I’ll take a look.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
