### ISSUE TITLE
Watch app cannot be installed

### ISSUE THREAD

**Issue by DevAndArtist** [GitHawkApp/GitHawk#2438]
I have a new Apple Watch Series 4 running the latest 5.1.1 OS and an old iPhone 6 Plus with iOS 12.1. However I‘m currently experiencing issues with the installation process of multiple watch apps. Some of the apps do always install other just don‘t, this also includes GitHawk watch app. 

Note: I had previously installed Shazam on my watch but yesterday I tried different solutions to get Spotify app on the watch and deleted all installed apps. Not Shazam is one of the apps that cannot be installed anymore.

I already tried different solutions:
- Rebooting the watch / phone
- Deleting the watch app
- Uninstalling everything on the watch
- Uninstalling the app on the phone and re-try installing it on the phone
- Unpair the watch and restore from backup
- Unpair and pair the app as a new device (dropped the backup)
- Resetting network settings on the phone

Nothing helped so far :(

***

Since I experience the same issue with the GitHawk app this GitHub issue is an opportunity to investigate further if it‘s the apps fault due to some kind of incompatibility with the series 4 watch or maybe an issue with the OS or something else. It‘s really frustrating.

To begin with, can someone with the same watch verify the same behavior?

Here are a few screenshots of alerts that I only get in TestFlight. In the watch app I only see the indicator spinning for a long time until it starts installing the app, then it reaches 100% and goes back to INSTALL again while the app icon on the watch itself disappears.

***

![GitHawk Upload by DevAndArtist](https://i.imgur.com/IuIZhfN.jpg)

![GitHawk Upload by DevAndArtist](https://i.imgur.com/utcFgPu.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
Google translate says the first dialog says:

> “GitHawk” can not be installed. GitHawk needs to be updated to run on this Apple Watch.

Which probably means there’s an incompatibility, although I’m not sure exactly what it is.

**Comment by DevAndArtist** [comment]
Well I'm confused as well. The whole story started yesterday when I was trying to install Spotify on my watch and failed. On the web I've seen people reporting that they have installed the app on a Series 4 watch running 5.1.1, but they had a different iPhone.

I'll do further testing later on with an iPhone 7, in the time being I'll download a few random apps and try to install them. In worst case I'm willing to do a factory reset of my iPhone, but this is already nuts. I already contacted Apple Support on that issue, let's see what they reply.

**Comment by DevAndArtist** [comment]
Small update: I was able to compile the project on my apple watch and it got installed as usually. Then I deleted if from the watch and installed it from the compiled phone app with the Watch app again. This also worked as expected.

Now it's getting strange why I cannot install the watch app from the latest GM version of the app.

**Comment by rnystrom** [comment]
I was able to delete and install the GM

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DevAndArtist** [comment]
Together with apple support we could at least sort out that it's not my Apple ID that has some wrong configuration which would prevent me from installing apps. We're still investigating.

More updates: It works just fine on the iPhone 7. I did a factory reset on the iPhone 6 Plus later on and it still failed. Today I tried with the new update from the app store and it failed again. I wanted to try to fully re-install iOS on my iPhone and see if it resolves, but before doing that I hooked up my iPhone to the mac and opened the Console app. Since there are tons of logs and I have no idea which were responsible for the installation or if those will even appear, but I think I got lucky this time. I found a reproducible log when observing by the `installd` keyword (not specifically the `Process`).

Here are the logs I discovered:

```
standard	08:47:21.553016 +0100	569	installd			0x16ee4b000 -[MIClientConnection getAppMetadataForApp:completion:]: Get app metadata requested by client appconduitd (pid 384) for app com.whoisryannystrom.freetime
standard	08:47:22.107772 +0100	569	installd			0x16f07b000 -[MIClientConnection snapshotWKAppInCompanionAppID:toURL:options:completion:]: Snapshot requested for com.whoisryannystrom.freetime by appconduitd (pid 384) to /var/mobile/Library/Caches/com.apple.AppConduit.staging/com.whoisryannystrom.freetime_rKHvji/Transfer with options {
    CreatePlaceholderOption = 1;
}
standard	08:47:23.530359 +0100	569	installd			0x16ee4b000 -[MIClientConnection snapshotWKAppInCompanionAppID:toURL:options:completion:]: Snapshot requested for com.whoisryannystrom.freetime by appconduitd (pid 384) to /var/mobile/Library/Caches/com.apple.AppConduit.staging/com.whoisryannystrom.freetime_kixWsF/Transfer with options {
    CreatePlaceholderOption = 0;
}
standard	08:47:31.945072 +0100	384	appconduitd			0x16fbcf000 -[ACXServerInstallOperation receivedDictionaryOrData:]: 591: Got error 17 in install done from remote side (MI error IncorrectArchitecture ; Extended 0x0 ; Desc Failed to find matching arch for 32-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Fc342r/extracted/Payload/FreetimeWatch.app/FreetimeWatch)
standard	08:47:31.947420 +0100	384	appconduitd			0x16fbcf000 -[ACXServerInstallOperation _onQueue_callCompletion:]: Resetting socket because of error Error Domain=ACXErrorDomain Code=17 "Got error 17 in install done from remote side (MI error IncorrectArchitecture ; Extended 0x0 ; Desc Failed to find matching arch for 32-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Fc342r/extracted/Payload/FreetimeWatch.app/FreetimeWatch)" UserInfo={SourceFileLine=591, NSLocalizedDescription=Got error 17 in install done from remote side (MI error IncorrectArchitecture ; Extended 0x0 ; Desc Failed to find matching arch for 32-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Fc342r/extracted/Payload/FreetimeWatch.app/FreetimeWatch), FunctionName=-[ACXServerInstallOperation receivedDictionaryOrData:]}
standard	08:47:31.947709 +0100	384	appconduitd			0x16fb43000 -[ACXInstallQueue _onQueue_deQueueNextOperation]_block_invoke_2: Failed to install app com.whoisryannystrom.freetime.watchkitapp (p = N, ui = N) : Error Domain=ACXErrorDomain Code=17 "Got error 17 in install done from remote side (MI error IncorrectArchitecture ; Extended 0x0 ; Desc Failed to find matching arch for 32-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Fc342r/extracted/Payload/FreetimeWatch.app/FreetimeWatch)" UserInfo={SourceFileLine=591, NSLocalizedDescription=Got error 17 in install done from remote side (MI error IncorrectArchitecture ; Extended 0x0 ; Desc Failed to find matching arch for 32-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Fc342r/extracted/Payload/FreetimeWatch.app/FreetimeWatch), FunctionName=-[ACXServerInstallOperation receivedDictionaryOrData:]}
standard	08:47:31.950190 +0100	384	appconduitd			0x16fb43000 -[ACXCompanionSyncConnection _onQueue_processPendingGizmoState]_block_invoke_3: Failed to install app com.whoisryannystrom.freetime.watchkitapp : Error Domain=ACXErrorDomain Code=17 "Got error 17 in install done from remote side (MI error IncorrectArchitecture ; Extended 0x0 ; Desc Failed to find matching arch for 32-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Fc342r/extracted/Payload/FreetimeWatch.app/FreetimeWatch)" UserInfo={SourceFileLine=591, NSLocalizedDescription=Got error 17 in install done from remote side (MI error IncorrectArchitecture ; Extended 0x0 ; Desc Failed to find matching arch for 32-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Fc342r/extracted/Payload/FreetimeWatch.app/FreetimeWatch), FunctionName=-[ACXServerInstallOperation receivedDictionaryOrData:]}
```

To sum up:

```
Got error 17 in install done from remote side (MI error IncorrectArchitecture; 
Extended 0x0; 
Desc Failed to find matching arch for 32-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Fc342r/extracted/Payload/FreetimeWatch.app/FreetimeWatch)

UserInfo = {
  SourceFileLine = 591, 
  NSLocalizedDescription = Got error 17 in install done from remote side (MI error IncorrectArchitecture ;
  Extended 0x0; 
  Desc Failed to find matching arch for 32-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Fc342r/extracted/Payload/FreetimeWatch.app/FreetimeWatch), 
  FunctionName = -[ACXServerInstallOperation receivedDictionaryOrData:]
}
```

I do not understand them but I can guess that the WatchApp thinks that one of my devices should be of an 32-bit architecture. Since 32-bit arch was dropped in iOS 11 it fails to find it in the app bundle, I guess and simply fails to successfully install. 😞

**Comment by rnystrom** [comment]
Can you try deleting the app on your phone and reinstalling?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DevAndArtist** [comment]
This won't help, I already tried any possible combination. In my last attempt I purged iOS via DFU and configured it as new phone. Then I downloaded latest GitHawk app from the store, paired the watch started installing it while observing the logs. Same issue over and over again: Error 17 IncorrectArchitecture. 

It seems like App Store is providing corrupted builds for my device combination, so it's not the fault of this project's configuration. I'm waiting for Apple to respond to my new findings. 

Btw. in the linked issue there was another user mentioned with an iPhone 6 Plus who experiencing the same issue that apps are not installing. We may be able to contact him and see if he's also getting Error 17 in the logs. That would give more evidence that App Store has a bug affecting device combinations like mine.

**Comment by rnystrom** [comment]
Let me know what you find!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by t9mike** [comment]
I tweeted to @9to5mac in hopes of getting some traction. https://twitter.com/t9mike/status/1063423145032458242. But I am a Twitter nobody so probably won't be of much help.

**Comment by DevAndArtist** [comment]
Well I tweeted to some other people but they didn‘t reply. I tested with a different iPhone 6 Plus today, same Error 17. It would help if more people would start reporting the issue so it gets some priority by Apple. It feels like some system is not aware on the iPhone 6 Plus that s 64bit Apple Watch exists. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DevAndArtist** [comment]
Created a blog post about this issue, all iPhone 6 Plus devices are affected that are paired with an Apple Watch Series 4.

https://devandartist.com/posts/apps-not-installing-on-the-apple-watch-or-error-17

I'll close the issue since the root issue is not in the app.

**Comment by t9mike** [comment]
The user who had an issue with my app and others sent me this:

> Many of the apps including Shazam, Dark Sky updated their apps and they loaded without issues. 
> Can’t explain it, put again all apps that updated are now running fine without updates to iPhone or watch. 

I submitted an update to my app (Sundial) this AM with some new features. I will report back on install status for my user after the update is in the store.

**Comment by t9mike** [comment]
My new version was approved and released to app store. My user was able to install :-).

Maybe they had a bug in translation from date X to Y and fixed it. But why not retroactively fix affected packages?

I don't see why this was not picked up by one of the Apple sites. They report on such trivial crap and this was (still is) driving some users crazy. My user spent hours going to Apple store and dealing with their ineffective wipe/restore attempts at a solution.

**Comment by DevAndArtist** [comment]
Hmm, I'll check again when GitHawk pushes a new release. I kind of doubt it will install correctly. A time related bug seems a little unlikely to me, because only a single device model is really affected.
