### ISSUE TITLE
HTML entities in inline code are shown as characters

### ISSUE THREAD

**Issue by antons** [GitHawkApp/GitHawk#2442]
`&lt;`  is shown as `<` in comments.

#### GitHub

<img width="375" src="https://user-images.githubusercontent.com/129705/48620310-5256d500-e9a8-11e8-817e-382560cfaf6f.png">

#### GitHawk 

<img width="375" src="https://user-images.githubusercontent.com/129705/48620274-394e2400-e9a8-11e8-9d97-9cf694951122.PNG">

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.24.0 (1542135906)
Device: iPhone X (iOS 12.1.1)
TestFlight: false
</pre>
</details>

**Comment by kudax6x** [comment]
@antons 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
Additionally, HTML comments (`<!-- example -->`) aren’t rendered.

**Comment by j-f1** [comment]
Inline or block:
```html
<!-- test -->
```
