### ISSUE TITLE
Deep links don't work if app is cold started via link

### ISSUE THREAD

**Issue by timonus** [GitHawkApp/GitHawk#2450]
**Describe the bug**
I've noticed since adding GitHawk support to Opener (detailed [here](https://github.com/GitHawkApp/GitHawk/issues/418)) that it seems to only work intermittently. Today I found that this malfunction *only* happens if GitHawk is cold started from a deep link, if it was launched previously the issue wouldn't occur.

**To Reproduce**
1. Force quit GitHawk
2. Go to Safari
3. Navigate to `freetime://RepoRoute?owner=timonus&repo=OpenerManifest&branch=master`, which should launch GitHawk.

**Expected behavior**
The app should launch and navigate to [this repository](https://github.com/timonus/OpenerManifest).

**Screenshots**
Video of this: https://db.tt/ONuuggeMxQ

**Smartphone (please complete the following information):**
- GitHawk 1.24.0 and above, not sure of iOS version but I believe it probably extends back to the oldest iOS version GitHawk supports.

**Additional context**
I'm trying to find the root cause of this.

**Comment by timonus** [comment]
Also notable
- Deep links don’t work for the entire of the session if the session is started via deep link. Not just the first time.
- This bug doesn’t occur on iPad at all, iPad always handles links correctly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Crap hmm. I’ll try to dig in too.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timonus** [comment]
Aha, didn't realize that was a part of it. Seems there is a discrepancy in `isCollapsed` between the error repro and successful cases.

![screen shot 2018-11-18 at 3 04 15 pm](https://user-images.githubusercontent.com/522951/48679291-4c492b80-eb43-11e8-9379-516287f0e19f.png)
