### ISSUE TITLE
Merge status pending

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2452]
Pretty sure when tests are pending on a PR it reads “merge status pending” rather than “tests pending”. Anyone able to confirm?

I forgot to take a screenshot sorry :/

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.24.0 (1542135906)
Device: iPhone XR (iOS 12.0.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Would love to see an example to repro. Does GitHub have different statuses for CI running?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
![GitHawk Upload by Huddie](https://i.imgur.com/SGPUynT.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Is that what GitHub says for the same UI?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Looks like we could just update the language

![GitHawk Upload by rnystrom](https://i.imgur.com/t81HPj8.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Sorry ya github has different language. 
One seems like you can’t merge yet, one is just test. 
Simple language update should be perfect 👌.
I should be able to do this unless someone is already on it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Huddie go for it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
How about “X Check(s) pending?“

**Comment by rnystrom** [comment]
Or keep it really simple with “Checks haven’t completed”, similar to GitHub’s message

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
I should have this by end of day. Gonna go with the github styled one for now 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Merged as is. Might wanna check iPhone 5 width to make sure it’s not too long. But probably fine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
