### ISSUE TITLE
Try again haptic feedback

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2460]
Should the “Try again” button that appears on lists that fail to load have haptic feedback attached to it?

Steps to reproduce:
1. Open app
2. Open repo (settings ~> view source code)
3. Turn phone on airplane mode
4. Switch to issues tab
5. Tap try again
6. See that No haptic feedback occurs

Not sure which buttons are supposed to have and which aren’t. Pretty sure that when you pull to refresh you get haptic feedback and therefore pushing a button to refresh should give feedback as well.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I don’t have any hard and fast rules for haptics tbh. I’d be fine adding them for this button.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
IMO the haptics for the pull-to-refresh button indicate that you’ve pulled far enough, whereas the button requires only a tap so the button doesn’t need haptics.

**Comment by Huddie** [comment]
Sounds good. No haptic for now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
