### ISSUE TITLE
Reword “view source code”

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2461]
I feel like “View Source Code” (found in settings tab) doesn’t fit too well. When you click View Source Code you’re brought to the GitHawk repo and the tab that is selected is the overview tab. Although there exists the source code under the code tab, I feel like “View GitHawk Repo” or something of that type fits better.

Thoughts? Suggestions different phrasing?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
View GitHub repo sounds good

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
