### ISSUE TITLE
Router Refactor issues

### ISSUE THREAD

**Issue by ijm8710** [GitHawkApp/GitHawk#2463]
Open issue #2450, then navigate to referenced #2453, try opening the commit code referenced at bottom, doesn’t action

Open issue #2453, try opening same commit code and does so successfully

**Comment by Huddie** [comment]
Appears to happen whenever you get pushed their from a link rather than from the pull requests tab in the repos view controller. 

When I click #2453 above I’m still not able to open the files

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
I can repro.

**Comment by ijm8710** [comment]
I’m filed a few things relating to push links. Like image previewing in theater as well. Not sure when it started breaking but essentially even though your in githawk in-app view, it’s not treating a push link the same as a direct open

**Comment by rnystrom** [comment]
I _think_ it’s all fallout from the router refactor.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
It should. I’m confused how it isn’t getting wired. I can repro tho.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
