### ISSUE TITLE
File button not working under certain circumstances

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2465]
Reproducable when opening #2450, then opening the pull request at the bottom (#2453), the file button now does not work (it no-ops)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
If I open #2453 directly, it does work. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Dupe #2463 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
