### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by jdmarshall90** [GitHawkApp/GitHawk#2471]
Any chance GitLab support could be added? I’d love to use this app even more than I do now, but I prefer GitLab.

I realize this would likely be non-trivial, but I thought I’d ask, as I’m not familiar with the app’s architecture.

P.S.

The `accessoryInputView` this app uses on the iPad is awesome.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
See also #408. I don't think there's any work being done on it at the moment. And as you say, it's pretty non-trivial.

Closing in favor of #408; let's discuss it further there if needed 👍
