### ISSUE TITLE
Nice Easter egg

### ISSUE THREAD

**Issue by ijm8710** [GitHawkApp/GitHawk#2472]
@Rnystrom I think you know what this is referencing

**Comment by Sherlouk** [comment]
🤔 👀

**Comment by BasThomas** [comment]
🦃

**Comment by Sherlouk** [comment]
Ahh I now realise 😂😂 thanks Twitter... gosh darn localised celebrations, why did I recommend that!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
