### ISSUE TITLE
Shows 404 after clicking "Sign in with GitHub" Button

### ISSUE THREAD

**Issue by peterzililuo** [GitHawkApp/GitHawk#2478]
When I click the button on the welcome's screen "Sign in with GitHub", then it shows 404 in GitHub
![image](https://user-images.githubusercontent.com/43706386/48965928-51eeb780-f002-11e8-87b6-645ff18980ac.gif)

**Comment by peterzililuo** [comment]
>Any idea what version of the app this is? I can’t reproduce this with v1.25.0, which is the latest App Store version.  ...

@BasThomas Eh... I download the project from GitHub & built it on my iPhone 6s, and, where is SafariViewController located?
I just downloaded it from TestFlight, the TestFlight version works well, I’m wonder if there’s any problem happened when I’m building

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@peterzililuo why was this closed? I’m getting this error 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
