### ISSUE TITLE
Spinner finishes before code file loads

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2492]
- If you go to this file: Freetime.xcodeproj/project.pbxproj

- The spinner should end pretty quickly but the page will remain blank. 

- Wait
- Document appears

I think the spinner should continue until the document is ready to show, I thought it was either blank or there was an error loading it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
It’s from rendering the code in the background. Could be interesting to keep the spinner til rendering finishes. Requires a little refactoring on the CodeView I think. Great task for someone.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
Could the unhighlighted code be displayed first, then replaced with the highlighted version?

**Comment by Huddie** [comment]
Is this rendered in a uitextview or tableview? Maybe find ways to reduce the amount needing highlighting at a time 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Text view

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
I know styledTextKit has a UITableView example. Would this help loading times?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
It would if we split big chunks of text into smaller pieces (maybe by line count?) and then calculated code style in order

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
