### ISSUE TITLE
Try again for “Cannot load file type” does not work

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2493]
- Head over to https://github.com/GitHawkApp/GitHawk/tree/master/tools/bin in GitHawk
- The screen will say that we could not load the file and there’s an option to try again 
- Tap try again 
- Nothing happens

Thoughts:
1) Hook up try again to make it work 
2) Remove try again (if we cannot load it the first time, we cannot load it the second time).

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.25.0 (1542806489)
Device: iPhone XR (iOS 12.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Does it actually not do anything, or does it just fail to load again? Does FLEX show new network requests?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom I’ll check. It didn’t show the spinner which is usually the first thing that happens when the try again is pushed 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
It may just load too fast, but also may not be wired up 🤷‍♀️

Either way retrying will just error and show the same screen again. More important for situations where the screen actually fails to load

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom I tried with FLEX. No network requests expect the initial attempt. 
This isn’t a big deal but I feel like if we have a button it should do something. Even though i suspect it will produce the same result  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@rnystrom I'll take this after finishing the Github V4 mutation stuff for #2482. Just in case someone wants to pick this up in the meantime.
