### ISSUE TITLE
Jump to page location opens in Safari

### ISSUE THREAD

**Issue by nickdaria** [GitHawkApp/GitHawk#2501]
In markdown overviews using a table of contents, when linking to a header on the page (example: #FAQ) GitHawk attempts to open the #FAQ in Safari. This fails to load as it is simply pointing safari to #header

Example: Signale Console Logger Readme

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nickdaria** [comment]
https://github.com/klaussinani/signale

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I think there are a few issues open on this, will find in a bit

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
#2256
