### ISSUE TITLE
Open external links in Safari

### ISSUE THREAD

**Issue by schrodincat** [GitHawkApp/GitHawk#2517]
It would be handy to have a setting to open all external links (or indeed GitHub links that GitHawk don’t handle through native UI) in Safari instead of in-app WebView.
This is a setting that you can find in many iOS apps and no doubt would be useful addition to many users.

**Comment by rnystrom** [comment]
@schrodincat would love a PR!

**Comment by schrodincat** [comment]
@rnystrom if only I knew how to code in Swift...😓
