### ISSUE TITLE
Search not working when keyboard connected

### ISSUE THREAD

**Issue by goerz** [GitHawkApp/GitHawk#2529]
When I have the Smart Keyboard Folio attached, I cannot use the Search field in Githawk. Tapping it immediately selects and deselects it. It works if I detach the keyboard, tap, and then use the on-screen keyboard to search for something.

~~~
App Information:
App Name: GitHawk for GitHub
App Version: 1.26.0 (1543766544)
Installed App Version: 1.26.0 (1543766544)

Device Information:
Device: iPad8,5 (2018 iPad Pro 12.9 inch)
iOS Version: 12.1
Language: en-US (English (United States))
Carrier: N/A
Timezone: EST
Architecture: N/A
Connection Status: WiFi
~~~

**Comment by rnystrom** [comment]
Yuck, @BasThomas have you hit this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
🤔

No, haven't used my iPad in a while 😅
