### ISSUE TITLE
Remove “bookmarks will be removed” on logout

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2530]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.26.0 (1543766544)
Device: iPhone X (iOS 12.1)
TestFlight: true
</pre>
</details>

**Comment by ijm8710** [comment]
Must we do anything for the syncing or is it automatic?

**Comment by rnystrom** [comment]
Auto, doesn’t delete anything

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
