### ISSUE TITLE
Github emoji not working (anymore?)

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2536]
Thought this was supported?

![GitHawk Upload by BasThomas](https://i.imgur.com/ApkE2qj.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.26.0 (1543766544)
Device: iPhone X (iOS 12.1)
TestFlight: true
</pre>
</details>

**Comment by ijm8710** [comment]
Was also about to post this as I saw labels for :bug: bug (assuming that’s related)

**Comment by BasThomas** [comment]
I don’t think we had those in labels before so I am not sure if they were supported in the first place, but yes. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
🚫 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Oh I bet it’s from moving the string replace into markdown text instead of the whole string. Needs to find/replace HTML too. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Nope we’ve never supported emoji in labels

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
