### ISSUE TITLE
Semi overlapping “more” button and bug report dump expander conflicting

### ISSUE THREAD

**Issue by jdmarshall90** [GitHawkApp/GitHawk#2541]
Hard to describe so here’s a screenshot:

![GitHawk Upload by jdmarshall90](https://i.imgur.com/PLQTCFd.jpg)

Tapping blue button either does nothing, expands the bug report dump, or if I leave the VC and come back, it might take me to a web view saying it can’t open a `tel` URL.

![GitHawk Upload by jdmarshall90](https://i.imgur.com/4XXlpna.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.26.0 (1543766544)
Device: iPhone X (iOS 12.1.1)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
I think there is a known issue about the expand button and the bug report and it not always working in general 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Probably my ticket on #2363?

**Comment by rnystrom** [comment]
Yup all dupes
