### ISSUE TITLE
Swipe left/right through images attached to issue / MR

### ISSUE THREAD

**Issue by jdmarshall90** [GitHawkApp/GitHawk#2542]
If there are multiple images attached to an issue (presumably for MRs as well?), you have to close the image and go tap on the other one if you want to see it. Would be nice to be able to page through them via swipe gesture.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.26.0 (1543766544)
Device: iPhone X (iOS 12.1.1)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
I think an issue exists for this 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Dupe #362

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
