### ISSUE TITLE
Bookmark organization

### ISSUE THREAD

**Issue by jdmarshall90** [GitHawkApp/GitHawk#2543]
It would be nice to be able to organize bookmarks. I’m thinking maybe:

* Manually sort
* Auto sort criteria
* Folders

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.26.0 (1543766544)
Device: iPhone X (iOS 12.1.1)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
Closing #2376 #1886 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
