### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by jdmarshall90** [GitHawkApp/GitHawk#2544]
GitLab (I think GitHub does too?) has some nice PM tools:

* Issue boards with customizable criteria
* Burndown charts for releases

If this were in GitHawk, it might just make me switch to GitHub just so I could do these things natively.

iPad support would be a must for these, IMO.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.26.0 (1543766544)
Device: iPhone X (iOS 12.1.1)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
Dupe #318

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
