### ISSUE TITLE
Deprecated status page

### ISSUE THREAD

**Issue by DaniSpringer** [GitHawkApp/GitHawk#2546]
Please link app to new GitHub status page

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.25.0 (1542806489)
Device: iPhone XR (iOS 12.1.1)
TestFlight: false
</pre>
</details>

**Comment by romankl** [comment]
The url changed to https://www.githubstatus.com/
Can I send a PR for this?

**Comment by Huddie** [comment]
@romankl ya!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Weird move 🤔

**Comment by BasThomas** [comment]
[This](https://github.com/GitHawkApp/GitHawk/blob/083155077e06347f944e690f10385d793327ebca/Classes/Settings/SettingsViewController.swift#L147) would now be `https://www.githubstatus.com/`, without adding the `messages` path.

[This](https://github.com/GitHawkApp/GitHawk/blob/8452d73ab9aab9db3891dce102c4b1574acc95d0/Local%20Pods/GitHubAPI/GitHubAPI/GitHubAPIStatusRequest.swift#L20) one I think can stay; I don't see that the API path changed.

**Comment by j-f1** [comment]
The old site will be removed in 7 days.
