### ISSUE TITLE
URL route for opening pull requests

### ISSUE THREAD

**Issue by timonus** [GitHawkApp/GitHawk#2551]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, just a request for a new URL route.

**Describe the solution you'd like**
Following up from https://github.com/GitHawkApp/GitHawk/issues/418, and similar to another feature that was just added to another GitHub client here https://github.com/jkpang/PPHub-Feedback/issues/179, I would love it if GitHawk had a URL route to open pull requests.

**Describe alternatives you've considered**
n/a

**Additional context**
Recently a variety of URL routes were added to GitHawk, which I integrated into Opener. Another GitHub client added PR routes, which I hadn't considered for GitHawk. Would be cool to have parity.

**Comment by rnystrom** [comment]
Sadly we don’t even allow opening PRs yet, lots of prereqs ha.

Opening a new issue would be an easy start.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timonus** [comment]
Ah, by “open” I meant “open the app to view a PR”, not creating a PR.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
@timonus Opening PR is same as opening an issue actually. Since Githawk handles everything as an issue. 

Try this to open the #1000

`freetime://IssueRoute?owner=GithawkApp&repo=GitHawk&number=1000`

**Comment by rizwankce** [comment]
Also you can use `scrollToBottom` to automatically make GItHawk to scroll to the bottom of an issue or PR

**Comment by timonus** [comment]
Oh rad, that worked perfectly! Thanks!

Added to Opener in 
https://github.com/timonus/OpenerManifest/commit/73ebaf680b082f4299b79fc726b78a8e94a0c343.
