### ISSUE TITLE
Support fixed holidays

### ISSUE THREAD

**Issue by j-f1** [GitHawkApp/GitHawk#2560]
I noticed that my inbox doesn’t have the expected 🎅 icon today. It looks like the code that sees if there’s a special icon looks first for a mapping for this year, then for a fixed mapping. Instead, it should try to get the **day** from each key. Example code:

```swift
let today = data["\(year)"]?["\(month)"]?["\(day)"] ?? data["fixed"]?["\(month)"]?["\(day)"]
```

Merry Christmas!

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.26.0 (1544968988)
Device: iPhone 8 (iOS 12.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
@j-f1 mind submitting a PR w/ the fix? Bummer we missed Santa!
