### ISSUE TITLE
When user likes a highlight, show story to people who follow that user

### ISSUE THREAD

**Issue by deekay** [GitHawkApp/GitHawk#2561]
Don't do this for comments.  We should separately track and design for comments which is more complicated.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.25.0 (1542806489)
Device: iPhone X (iOS 12.1.2)
TestFlight: false
</pre>
</details>

**Comment by rizwankce** [comment]
@deekay are you sure? You are reporting Githawk bug of feature request. If not pls close it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deekay** [comment]
Sorry, my bad.  Just downloaded Githawk and still trying to figure it out.  How do I close?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
