### ISSUE TITLE
When user follows a user, show follow as a story to users who follow that user

### ISSUE THREAD

**Issue by deekay** [GitHawkApp/GitHawk#2563]
Requires design

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.25.0 (1542806489)
Device: iPhone X (iOS 12.1.2)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Sorry, what?

**Comment by deekay** [comment]
Sorry, I was confused about how to use GitHawk.  Was meant to be on my own project, not on the GitHawk project.
