### ISSUE TITLE
Consistent Blues

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2569]
We updated the blue for the context menu. This blue is different from the remaining blue in the app. Do we want this or should we try migrating over to the new blue ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Nope, that blue is for better contrast against the dark bavkground

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
