### ISSUE TITLE
Update to 1.27.0 crashes on launch

### ISSUE THREAD

**Issue by garethtdavies** [GitHawkApp/GitHawk#2584]
**Describe the bug**
Upgraded via iOS updates to the latest version of 1.27.0. Now opening GitHawk immediately crashes.

**To Reproduce**
1. Update to 1.27.0.
2. Open the GitHawk app

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS:  - iOS 12.1.2

**Comment by rnystrom** [comment]
Ugh that’s not good! I just installed prod and it’s working fine. I’ll have to pull up some crash logs.

@garethtdavies can you try uninstalling and reinstalling? Or joining TestFlight?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by garethtdavies** [comment]
@rnystrom I just joined TestFlight and it still happens so hopefully, you can see the logs?
