### ISSUE TITLE
Repo top tab bar pixelated in latest beta

### ISSUE THREAD

**Issue by timonus** [GitHawkApp/GitHawk#2586]
Something strange seems to have happened in the latest beta, the top tab bar is always pixelated.

![GitHawk Upload by timonus](https://i.imgur.com/9QCCGmn.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ugh, [this line](https://github.com/GitHawkApp/GitHawk/pull/2573/files#diff-21ca3539bc6215ced0423adff0e610e9R312) wasn't pulled. Reverting #2573 temporarily.
