### ISSUE TITLE
Top tab bar text is soft

### ISSUE THREAD

**Issue by dbauducco** [GitHawkApp/GitHawk#2589]
![Example image by dbauducco](https://i.imgur.com/4xsdIlx.jpg)

On my iPhone XR, the top tab bar text looks soft.
Similar to another earlier issue, but in that case, the text was pixelated. (#2586)

Currently running Beta 1.27.0 from Test Flight.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Dupe #2586
