### ISSUE TITLE
Hamburger button expands

### ISSUE THREAD

**Issue by j-f1** [GitHawkApp/GitHawk#2591]
I’m not sure how to repro this, but I tapped it at the same time I was posting a comment, and this happened:

![GitHawk Upload by j-f1](https://i.imgur.com/cnzAqIe.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.0 (1546443046)
Device: iPhone 8 (iOS 12.1.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Yuck, if you find a way to repro lmk

**Comment by j-f1** [comment]
Test

**Comment by j-f1** [comment]
Yep, sending a comment and tapping the hamburger button at the same time repros.

**Comment by rnystrom** [comment]
Test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Can you give some detailed steps?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
Test 2

**Comment by j-f1** [comment]
1. Type a comment in an issue.
1. Place your right thumb over the send button.
1. Place your left thumb over the hamburger button.
1. Press the send button then the hamburger button in immediate succession.

**Comment by rnystrom** [comment]
Test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
Test

**Comment by j-f1** [comment]
Alternate repro: press and hold the hamburger button, then tap send to post the comment before releasing.

**Comment by j-f1** [comment]
Test
