### ISSUE TITLE
Odd pixelation in repo bar

### ISSUE THREAD

**Issue by crrapi** [GitHawkApp/GitHawk#2594]
There is some pixelation where the Overview/Issues/Pull Requests/Code bar is. (It looks much worse in person, believe me) Not sure why this is occurring, might be an issue on my end. ![GitHawk Upload by crrapi](https://i.imgur.com/jBSb9KP.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546566111)
Device: iPhone X (iOS 12.1.3)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
@rnystrom was this fixed in 1.27.1? Cause I assumed this was a dupe but the bug dump says 1.27.1 which is the new release ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Hmm this is looking fine for me now on 1.27.1 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Yup dupe and fixed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
