### ISSUE TITLE
Update “Request Changes” icon

### ISSUE THREAD

**Issue by j-f1** [GitHawkApp/GitHawk#2601]
GitHub [just](https://blog.github.com/changelog/2019-01-14-updated-request-changes-icon/) updated the icon used for requesting changes to this one:

![New icon](https://i.imgur.com/4voO6SS.jpg)

It doesn’t appear to be available in the Octicon set just yet.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546622353)
Device: iPhone 8 (iOS 12.1.2)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
I just saw this +1 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Filed an issue as it seems like it was added but somehow not deployed on the website; https://github.com/primer/octicons/issues/291

**Comment by BasThomas** [comment]
https://octicons.github.com/icon/request-changes/
