### ISSUE TITLE
GitHub status page deprecated

### ISSUE THREAD

**Issue by joseconstela** [GitHawkApp/GitHawk#2604]
Status.github.com is deprecated. The link on the app should be updated

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546622353)
Device: iPhone X (iOS 12.1.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Dupe of #2546 - fix in progress 😄
