### ISSUE TITLE
Support new reactions

### ISSUE THREAD

**Issue by j-f1** [GitHawkApp/GitHawk#2605]
GitHub [just released](https://github.blog/changelog/2019-01-18-more-reaction-emojis/) support for the 🚀 (“rocket”) and 👀 (“eyes”) reactions. It would be nice to be able to support these in GitHawk.

(the web UI now splits the reactions into two rows of four emoji on both desktop and mobile)

**Comment by Sherlouk** [comment]
Fun fact: The app actually renders unknown emojis as 👍. 

We should probably fix that here too? Maybe either ❓ or just hide the item?

**Comment by Sherlouk** [comment]
Unknown defaulting to 👍 is coded here:
https://github.com/GitHawkApp/GitHawk/blob/c23945ac7dfe015f3f7218668b5caef2355ac7db/Classes/Issues/Comments/Reactions/ReactionContent%2BReactionType.swift#L18

Possible reactions are here:
https://github.com/GitHawkApp/GitHawk/blob/e7386183de8b65aa0dd230100dd4a3eb5be14b32/Classes/Issues/Comments/Reactions/ReactionsMenuViewController.swift#L41-L48

Actual reaction content enum is here:
https://github.com/GitHawkApp/GitHawk/blob/master/gql/API.swift#L6-L59

Presumably we just need to regenerate the GQL file from GitHub schemas which will add the new reaction types. Update the extensions to provide correct values.
