### ISSUE TITLE
Ambiguous type name 'State' in 'UIButton'

### ISSUE THREAD

**Issue by pradeepb28** [GitHawkApp/GitHawk#2626]
**Describe the bug**
Followed all steps to build and run the app but unfortunately I have following issues:
- Multiple commands produce 
- Ambiguous type name 'State' in 'UIButton' / State' is ambiguous for type lookup in this context

**To Reproduce**
Run the app - Xcode 10.1

**Screenshots**

<img width="259" alt="screen shot 2019-02-03 at 1 47 44 pm" src="https://user-images.githubusercontent.com/6823101/52175794-4b2ab080-27ba-11e9-9018-813b916da3a7.png">
<img width="1053" alt="screen shot 2019-02-03 at 1 47 39 pm" src="https://user-images.githubusercontent.com/6823101/52175795-4fef6480-27ba-11e9-8991-a53bd4707802.png">
<img width="1056" alt="screen shot 2019-02-03 at 1 47 31 pm" src="https://user-images.githubusercontent.com/6823101/52175796-51b92800-27ba-11e9-8767-24a9e4343d9a.png">

**Comment by BasThomas** [comment]
I just built `master` and it ran fine on Xcode 10.1. Can you check if you can still reproduce the issue after cleaning derived data?

Feel free to reopen if it is still an issue!
