### ISSUE TITLE
Blurry Text on the Toolbar

### ISSUE THREAD

**Issue by amirmasoudabdol** [GitHawkApp/GitHawk#2630]
Hi,

I’ve noticed that tab’s texts in the toolbar are quite blurry. Check out the screenshot. 

Cheers,
Amir

![GitHawk Upload by amirmasoudabdol](https://i.imgur.com/H8vn9mR.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.0 (1546443046)
Device: iPhone XS (iOS 12.1.3)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Potential dupe #2586? Is this problem still in the latest version?

**Comment by BasThomas** [comment]
This should be fixed in the latest version on Testflight! Feel free to reopen this if that doesn't seem to be the case.
