### ISSUE TITLE
“API Status” needs to be updated

### ISSUE THREAD

**Issue by lebensterben** [GitHawkApp/GitHawk#2634]
Currently this function works well but there’s a warning that 

```
status.github.com has been deprecated. You can find the current github system status at githubstatus.com.
```

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546622353)
Device: iPad Air 2 (iOS 12.1.3)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Dupe of #2546 - fix in progress 😄
