### ISSUE TITLE
Collection view in repos do not respect safe area

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2636]
![GitHawk Upload by BasThomas](https://i.imgur.com/c0sxWbJ.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546622353)
Device: iPhone X (iOS 12.1.2)
TestFlight: true
</pre>
</details>

**Comment by RJ-Clegg** [comment]
I can take a look at this.

**Comment by ivenprillwitz** [comment]
is this still an issue? i could help :)

**Comment by RJ-Clegg** [comment]
> is this still an issue? i could help :)

Only managed to get time to look at this now and looking at it now. I'll let you know if I have any issues. Thanks!

**Comment by RJ-Clegg** [comment]
@BasThomas - How did you get the `UITabBar` to disappear? 
I've gone to the exact repo from the screenshot - via search and from bookmarks. The `UITabBar` remains in place; even whilst scrolling. 

With the `UITabBar` on screen; this issue isn't reproducible.

**Comment by j-f1** [comment]
If you open it from Notifications, the tab bar is not present.

**Comment by RJ-Clegg** [comment]
> If you open it from Notifications, the tab bar is not present.

Thanks, will check it out

**Comment by BasThomas** [comment]
And from the navigation bar in an issue 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
Ah yeah, only from the navbar in an issue. I wonder — should this just be worked around by always showing the tab bar?

**Comment by RJ-Clegg** [comment]
> And from the navigation bar in an issue 😊
> 
> Sent with [GitHawk](http://githawk.com)

Thanks, able top reproduce it easily enough now. I'll have a fix soon when I get home this evening.

**Comment by BasThomas** [comment]
>Ah yeah, only from the navbar in an issue. I wonder — should this just be worked around by always showing the tab bar?

@j-f1 not sure, but I feel that should / can be tackled separately. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by j-f1** [comment]
⏩ #2666

**Comment by LucianoPAlmeida** [comment]
Just taking a quick look at this one in the `RepositoryViewController`, seems like is an issue with the XLPagerTabStrip dependency. Here https://github.com/xmartlabs/XLPagerTabStrip/issues/722
