### ISSUE TITLE
Health Status

### ISSUE THREAD

**Issue by kbaker827** [GitHawkApp/GitHawk#2640]
![GitHawk Upload by kbaker827](https://i.imgur.com/FlQ93vv.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546622353)
Device: iPhone 8 Plus (iOS 12.1.1)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Dupe #2546
