### ISSUE TITLE
Crash on sign out

### ISSUE THREAD

**Issue by jhrcook** [GitHawkApp/GitHawk#2643]
App crashes when trying to sign out, preventing sign out

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPad7,5 (iOS 12.1.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
I can't reproduce this on `master`. Are you logged in with your account directly, or are you using a personal access token?

**Comment by BasThomas** [comment]
Also @rnystrom can you add the DSYMs to Crashlytics so I can maybe investigate this crash further? 😇

**Comment by jhrcook** [comment]
I've already removed the app from my iPad, but I was logged in through my GitHub account.
