### ISSUE TITLE
api status

### ISSUE THREAD

**Issue by ZaptoInc** [GitHawkApp/GitHawk#2653]
hello! the api status redirect to the old status page! try to fix this plz 😜

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 7 (iOS 12.1)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
Dupe #2546, fix pending

**Comment by ZaptoInc** [comment]
sorry and thanks 😍👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
