### ISSUE TITLE
ticking boxes in lists doesn't work

### ISSUE THREAD

**Issue by tooomm** [GitHawkApp/GitHawk#2655]
**Describe the bug**
If you have an issue with a tickable list like:
- [x] box a unchecked
- [x] box b checked

```
- [ ] box a unchecked
- [x] box b checked
```

You can click them in GitHawk, but it'll mess the markdown up .

**Expected behavior**
Tick/untick box correctly.

**Smartphone (please complete the following information):**
 - Device: iPad Mini 2
 - OS: iOS 12.1.4
 - Browser: Safari
 - Version: 1.27.2

**Additional context**
- before:
```
- [ ] For `aftermath` cards
```

- after ticking in the app:
```
- [ ] [x] `aftermath` cards
```

**Comment by BasThomas** [comment]
I can’t seem to reproduce this...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tooomm** [comment]
It must has been a special case. Works here.
