### ISSUE TITLE
Can you help expain this please

### ISSUE THREAD

**Issue by natta87** [GitHawkApp/GitHawk#2658]
0 {"timestamp":"2019-02-27 16:23:37.08 -0800","bug_type":"211","os_version":"iPhone OS 12.1.4 (16D57)","incident_id":"5D9BF77D-0A97-44CA-AA15-2645A9A1D264"}
1 {"_marker":"<metadata>","_preferredUserInterfaceLanguage":"en","_userInterfaceLanguage":"en","_userSetRegionFormat":"US","startTimestamp":"2019-02-27T00:19:28Z","version":"1.0"}
2 {"message":{"Count":1,"DeviceIsPowered":true,"LightningCableType":1,"LightningDigitalID":"100C00000000","LightningPrimaryPortNumber":1,"ScreenIsLocked":true,"TimeSinceLastLock":0,"TimeSinceLastUnlock":0,"UnlockedSinceBoot":false},"name":"CableTypeChangedV2","uuid":"9d75db50-aff8-4983-96e4-f8ef60f540b3"}
3 {"message":{"Count":2,"DeviceIsPowered":true,"LightningCableType":1,"LightningDigitalID":"100C00000000","LightningPrimaryPortNumber":1,"ScreenIsLocked":false,"TimeSinceLastLock":0,"TimeSinceLastUnlock":0,"UnlockedSinceBoot":true},"name":"CableTypeChangedV2","uuid":"9d75db50-aff8-4983-96e4-f8ef60f540b3"}
4 {"message":{"ChargingCurrent":3,"ChargingVoltage":5000,"Count":1,"LightningCableType":1,"LightningDigitalID":"100C00000000","LightningPrimaryPortNumber":1,"ScreenIsLocked":true,"TimeSinceLastLock":0,"TimeSinceLastUnlock":0,"UnlockedSinceBoot":false},"name":"ChargingConfigurationChangedV2","uuid":"cf4ae60c-ade2-4798-a83b-97a14897b120"}
5 {"message":{"ChargingCurrent":3,"ChargingVoltage":5000,"Count":2,"LightningCableType":1,"LightningDigitalID":"100C00000000","LightningPrimaryPortNumber":1,"ScreenIsLocked":false,"TimeSinceLastLock":0,"TimeSinceLastUnlock":0,"UnlockedSinceBoot":true},"name":"ChargingConfigurationChangedV2","uuid":"cf4ae60c-ade2-4798-a83b-97a14897b120"}
6 {"message":{"BogusFieldNotActuallyEverUsed":null,"Count":12},"name":"TwoHourHeartbeatCount","uuid":"7ad14604-ce6e-45f3-bd39-5bc186d92049"}
7 {"message":{"AirPlayVideoEventCount":0,"Count":1,"InSession":0,"Selected":false},"name":"AirPlayVideoCollectionEvent","uuid":"ec77580b-b7c9-47eb-8009-307bba9443f7"}
8 {"message":{"Count":1,"DisplayRegion":"0,2","Duration":0.0485,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":76.69,"Orientation":5,"ProxCovered":null,"TimeSinceWake":0.3678},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
9 {"message":{"Count":1,"DisplayRegion":"2,3","Duration":0.06683,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":0.0,"Orientation":1,"ProxCovered":null,"TimeSinceWake":0.4141},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
10 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":0.1158,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":49.66,"Orientation":0,"ProxCovered":null,"TimeSinceWake":0.4336},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
11 {"message":{"Count":1,"DisplayRegion":"3,1","Duration":0.09819,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":23.35,"Orientation":1,"ProxCovered":null,"TimeSinceWake":0.5016},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
12 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":0.166,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":0.0,"Orientation":0,"ProxCovered":null,"TimeSinceWake":0.5356},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
13 {"message":{"Count":1,"DisplayRegion":"0,2","Duration":0.01573,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":3.0,"Orientation":0,"ProxCovered":null,"TimeSinceWake":0.6166},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
14 {"message":{"Count":1,"DisplayRegion":"0,3","Duration":0.1807,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":29.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":0.6543},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
15 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":0.3831,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":0.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":0.7389},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
16 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":0.3841,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":0.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":0.739},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
17 {"message":{"Count":1,"DisplayRegion":"0,3","Duration":0.4487,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":36.77,"Orientation":2,"ProxCovered":null,"TimeSinceWake":0.7654},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
18 {"message":{"Count":1,"DisplayRegion":"0,3","Duration":0.4495,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":36.77,"Orientation":2,"ProxCovered":null,"TimeSinceWake":0.7658},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
19 {"message":{"Count":1,"DisplayRegion":"2,1","Duration":0.1459,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":13.93,"Orientation":0,"ProxCovered":null,"TimeSinceWake":1.0},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
20 {"message":{"Count":1,"DisplayRegion":"1,1","Duration":0.5987,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":17.46,"Orientation":5,"ProxCovered":null,"TimeSinceWake":1.137},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
21 {"message":{"Count":1,"DisplayRegion":"1,1","Duration":0.6447,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":81.31,"Orientation":5,"ProxCovered":null,"TimeSinceWake":1.137},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
22 {"message":{"Count":1,"DisplayRegion":"3,1","Duration":0.2102,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":323.3,"Orientation":1,"ProxCovered":null,"TimeSinceWake":1.302},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
23 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":0.2117,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":32.02,"Orientation":1,"ProxCovered":null,"TimeSinceWake":1.306},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
24 {"message":{"Count":1,"DisplayRegion":"0,3","Duration":0.5487,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":2.236,"Orientation":5,"ProxCovered":null,"TimeSinceWake":1.387},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
25 {"message":{"Count":1,"DisplayRegion":"0,3","Duration":0.716,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":50.6,"Orientation":5,"ProxCovered":null,"TimeSinceWake":1.387},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
26 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":0.5288,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":25.3,"Orientation":5,"ProxCovered":null,"TimeSinceWake":1.772},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
27 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":0.5311,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":25.3,"Orientation":5,"ProxCovered":null,"TimeSinceWake":1.774},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
28 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":0.01671,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":22.56,"Orientation":1,"ProxCovered":null,"TimeSinceWake":1.776},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
29 {"message":{"Count":1,"DisplayRegion":"2,3","Duration":0.2639,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":0.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":1.919},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
30 {"message":{"Count":1,"DisplayRegion":"2,3","Duration":0.2667,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":0.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":1.92},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
31 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":2.411,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":193.5,"Orientation":1,"ProxCovered":null,"TimeSinceWake":3.419},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
32 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":1.414,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":15.26,"Orientation":1,"ProxCovered":null,"TimeSinceWake":3.42},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
33 {"message":{"Count":1,"DisplayRegion":"0,0","Duration":160.3,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":341.6,"Orientation":5,"ProxCovered":null,"TimeSinceWake":3.494},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
34 {"message":{"Count":1,"DisplayRegion":"0,2","Duration":0.3481,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":0.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":4.186},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
35 {"message":{"Count":1,"DisplayRegion":"0,2","Duration":0.09174,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":20.1,"Orientation":5,"ProxCovered":null,"TimeSinceWake":4.503},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
36 {"message":{"Count":1,"DisplayRegion":"1,3","Duration":0.1802,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":0.0,"Orientation":1,"ProxCovered":null,"TimeSinceWake":4.878},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
37 {"message":{"Count":1,"DisplayRegion":"0,0","Duration":78.7,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":457.8,"Orientation":1,"ProxCovered":null,"TimeSinceWake":6.635},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
38 {"message":{"Count":1,"DisplayRegion":"0,3","Duration":8.297,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":23.41,"Orientation":5,"ProxCovered":null,"TimeSinceWake":9.874},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
39 {"message":{"Count":1,"DisplayRegion":"0,3","Duration":8.299,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":23.41,"Orientation":5,"ProxCovered":null,"TimeSinceWake":9.875},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
40 {"message":{"Count":1,"DisplayRegion":"0,3","Duration":0.1786,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":0.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":10.71},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
41 {"message":{"Count":1,"DisplayRegion":"0,2","Duration":2.06,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":13.93,"Orientation":5,"ProxCovered":null,"TimeSinceWake":13.59},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
42 {"message":{"Count":1,"DisplayRegion":"0,2","Duration":2.063,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":13.93,"Orientation":5,"ProxCovered":null,"TimeSinceWake":13.59},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
43 {"message":{"Count":1,"DisplayRegion":"0,2","Duration":0.4278,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":0.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":14.71},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
44 {"message":{"Count":1,"DisplayRegion":"0,2","Duration":0.4303,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":0.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":14.71},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
45 {"message":{"Count":1,"DisplayRegion":"0,2","Duration":0.4803,"GestureType":"UIGestureStudyInteractionEventTypeLongPressClick","HasAttention":null,"Movement":0.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":16.03},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
46 {"message":{"Count":1,"DisplayRegion":"0,2","Duration":0.4824,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":0.0,"Orientation":5,"ProxCovered":null,"TimeSinceWake":16.03},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
47 {"message":{"Count":1,"DisplayRegion":"0,0","Duration":23.44,"GestureType":"UIGestureStudyInteractionEventTypeLongPress","HasAttention":null,"Movement":578.7,"Orientation":5,"ProxCovered":null,"TimeSinceWake":25.01},"name":"ComAppleUiKitCoversheetGestureMessageV2","uuid":"2f5f83ca-e3f3-41bb-a366-344f60acedb9"}
48 {"message":{"Category":"TelemetrySignposts","Classification":"AllInspected","CountSum":810,"Subsystem":"com.apple.SpringBoard"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
49 {"message":{"Category":"KeyboardSignposts","Classification":"AllInspected","CountSum":41000,"Subsystem":"com.apple.TextInput"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
50 {"message":{"Category":"KeyboardSignpostsEphemeral","Classification":"AllInspected","CountSum":2000,"Subsystem":"com.apple.TextInput"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
51 {"message":{"Category":"UINavigationController","Classification":"AllInspected","CountSum":710,"Subsystem":"com.apple.UIKit"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
52 {"message":{"Category":"signpost","Classification":"AllInspected","CountSum":290,"Subsystem":"com.apple.coreduet.knowledge"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
53 {"message":{"Category":"AppLaunch","Classification":"Reported","CountSum":98,"Subsystem":"com.apple.FrontBoard"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
54 {"message":{"Category":"TelemetrySignposts","Classification":"Reported","CountSum":810,"Subsystem":"com.apple.SpringBoard"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
55 {"message":{"Category":"KeyboardSignposts","Classification":"Reported","CountSum":82,"Subsystem":"com.apple.TextInput"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
56 {"message":{"Category":"AppLifecycle","Classification":"Reported","CountSum":200,"Subsystem":"com.apple.UIKit"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
57 {"message":{"Category":"signpost","Classification":"Reported","CountSum":93,"Subsystem":"com.apple.coreduet.knowledge"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
58 {"message":{"Category":"LowDiskCondition","Classification":"ReportedEvents","CountSum":1,"Subsystem":"com.apple.ConditionInducer.LowSeverity"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
59 {"message":{"Category":"signpost","Classification":"ReportedEvents","CountSum":1,"Subsystem":"com.apple.coreduet.interaction"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
60 {"message":{"Category":"telemetry","Classification":"ReportedEvents","CountSum":1,"Subsystem":"com.apple.spotlight"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
61 {"message":{"Category":"ShareSheet","Classification":"StringWhitelistFiltered","CountSum":5,"Subsystem":"com.apple.UIKit"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
62 {"message":{"Category":"UINavigationController","Classification":"StringWhitelistFiltered","CountSum":710,"Subsystem":"com.apple.UIKit"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
63 {"message":{"Category":"UITabBarController","Classification":"StringWhitelistFiltered","CountSum":150,"Subsystem":"com.apple.UIKit"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
64 {"message":{"Category":"signpost","Classification":"StringWhitelistFiltered","CountSum":200,"Subsystem":"com.apple.coreduet.knowledge"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
65 {"message":{"Category":"general","Classification":"StringWhitelistFiltered","CountSum":11,"Subsystem":"com.apple.duetexpertd.atx"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
66 {"message":{"Category":"KeyboardSignposts","Classification":"SubsystemCategoryFiltered","CountSum":41000,"Subsystem":"com.apple.TextInput"},"name":"PerformanceSignpostCounts","uuid":"692f9696-0efe-48bf-8072-1c5e35556555"}
67 {"message":{"AnimationsNotReported":0,"AnimationsReported":0,"Count":1,"IntervalsNotReported":44000,"IntervalsReported":1400,"LogObjectsProcessed":94000,"ProcessingDurationInSeconds":290.0,"WasInterrupted":false},"name":"PerformanceSignpostsReportingStats","uuid":"cbb2a3af-4064-446c-a028-0e452d969dbe"}
68 {"message":{"BogusFieldNotActuallyEverUsed":null,"Count":1},"name":"OneDayHeartBeatCount","uuid":"a4813163-fd49-44ea-b3e1-e47a015e629c"}
69 {"_marker":"<end-of-file>"}
70

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone SE (iOS 12.1.4)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hey @natta87, not sure what I'm looking at. Can you explain a bit more of what it is you posted?

**Comment by varyP** [comment]
Needed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by varyP** [comment]
>Needed ...

@varyP l

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
@natta87 Gonna close for now, if you still need help just ping 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
