### ISSUE TITLE
Issue setting up project

### ISSUE THREAD

**Issue by RJ-Clegg** [GitHawkApp/GitHawk#2659]
Trying to get the app to run locally on my machine. Followed the instructions. However when I run the following command: `bundle` 

I get this error: 

> You must use Bundler 2 or greater with this lockfile.

Not really sure how to resolve this. Had a look at a few online resources without much success. 
Any suggestions?

**Comment by BasThomas** [comment]
Try `gem install bundler`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RJ-Clegg** [comment]
Thanks @BasThomas  - done that and it installs. However I still get the error. I think it’s installing the wrong version? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Ah – what about `gen update bundler`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RJ-Clegg** [comment]
All sorted now. Thanks @BasThomas
