### ISSUE TITLE
„Inbox Zero“

### ISSUE THREAD

**Issue by iDjay** [GitHawkApp/GitHawk#2662]
Hey, I would change the „Inbox Zero“ Text to „inbox empty“. Cheers and thanks for the nice app.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone XS (iOS 12.1.4)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
I believe this was a conscious wording choice from Ryan back in the day, and is a shoutout to the common strategy where people aim to achieve "inbox zero" (which, as you point out, is to empty your inbox)

Bit of reading here: https://whatis.techtarget.com/definition/inbox-zero
