### ISSUE TITLE
Re-arrange Bookmarks order

### ISSUE THREAD

**Issue by iDjay** [GitHawkApp/GitHawk#2664]
Would be great if we can re-arrange the bookmarks order :)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone XS (iOS 12.1.4)
TestFlight: false
</pre>
</details>

**Comment by iDjay** [comment]
And maybe a single swipe option to remove the items

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Dupe of #2376 #1886 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
