### ISSUE TITLE
Add haptics for merge results

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2668]
We should indicate a successful or unsuccessful merge with a haptic, I feel.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546622353)
Device: iPhone X (iOS 12.1.4)
TestFlight: true
</pre>
</details>

**Comment by akarataev** [comment]
I'll take a look at this, if nobody is against.

**Comment by Huddie** [comment]
@akarataev still on this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akarataev** [comment]
@Huddie, yep. 
Do you have any suggestions?

**Comment by akarataev** [comment]
@BasThomas hello,

Please see #2690 how you will have the opportunity.

**Comment by nambatee** [comment]
Should this issue be closed now that #2690 is in master?

**Comment by BasThomas** [comment]
Yep, nice catch!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
