### ISSUE TITLE
Save inbox preference

### ISSUE THREAD

**Issue by getjennyli** [GitHawkApp/GitHawk#2669]
Save inbox preference so I don’t need to change the view from navbar every time

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
Dupe #2654 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akarataev** [comment]
I'll take a look at this, if nobody is against.

**Comment by Huddie** [comment]
@akarataev Go for it! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akarataev** [comment]
Hi everybody, check #2693 how will the opportunity.

**Comment by IrenDoby** [comment]
```
`****`
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
