### ISSUE TITLE
Testing Issue # 2615

### ISSUE THREAD

**Issue by wayni208** [GitHawkApp/GitHawk#2674]
If this submits it is successful.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (SEE BUILD PHASE)
Device: Simulator (iOS 12.1)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
Yay

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
