### ISSUE TITLE
Cell size not correctly calculated on refresh

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2678]
Steps to reproduce:

1. Go to repo
2. Go to issues
3. Add a label to an issue without any
4. Go back
5. Refresh

![GitHawk Upload by BasThomas](https://i.imgur.com/G9k3GcS.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546622353)
Device: iPhone X (iOS 12.1.4)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
Dupe #2489 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
