### ISSUE TITLE
Toggle open/closed on issues

### ISSUE THREAD

**Issue by Huddie** [GitHawkApp/GitHawk#2679]
Every so often I want to check closed issues and I have to replace open ~> closed in the search bar.

I think a simple toggle could make this task easier and make it more in-line with GitHubs website.

My suggestion for design is:
![GitHawk Upload by Huddie](https://i.imgur.com/Go9wD8i.jpg)

All other suggestion are encouraged

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ijm8710** [comment]
Of course I agree and would love this. See #374

**Comment by Huddie** [comment]
Nice find.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
