### ISSUE TITLE
Dark Mode! Please...

### ISSUE THREAD

**Issue by Arutosio** [GitHawkApp/GitHawk#2691]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546622353)
Device: iPhone 6s (iOS 12.1.4)
TestFlight: true
</pre>
</details>

**Comment by Huddie** [comment]
#2553 also dupe #198 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
