### ISSUE TITLE
Github API Status : error

### ISSUE THREAD

**Issue by Shaquu** [GitHawkApp/GitHawk#2692]
When I’m in options of the GitHawk there is GitHub API Status section and it says error.
I clicked and it sends me to https://www.githubstatus.com/messages
![GitHawk Upload by Shaquu](https://i.imgur.com/MTD1nbX.jpg)
![GitHawk Upload by Shaquu](https://i.imgur.com/CyqkmQP.jpg)

I checked https://www.githubstatus.com in the browser and it’s working.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 6s (iOS 12.1.4)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
I believe this is taken care of. Will be fixed in next release. You can check the GitHawkApp/ReleaseNotes repo

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Shaquu** [comment]
Roger that.
