### ISSUE TITLE
deep links to pull requests

### ISSUE THREAD

**Issue by palmin** [GitHawkApp/GitHawk#2701]
Working Copy can deep link to issues in GitHawk but as far as I can tell there is no way to link to pull requests because there is no route type for these.

I'm adding the ability to open pull requests from within Working Copy and being able to point into GitHawk would be beneficial for our shared users.

Anyone else working on this? Should I try to add support?

**Comment by j-f1** [comment]
Does opening the PR as an issue work?

**Comment by palmin** [comment]
It does work. I feel super silly. 🥴
