### ISSUE TITLE
Not recurving notifications

### ISSUE THREAD

**Issue by Variable-X** [GitHawkApp/GitHawk#2704]
I have given GitHawk full access. What's the problem?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 6 (iOS 12.1.4)
TestFlight: false
</pre>
</details>

**Comment by Variable-X** [comment]
Receiving **not** recurving

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Variable-X** [comment]
API status: Error

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
You’ll get notifications in the background only, so they might be delayed. 

The API status error is unrelated; this will be resolved in the next version. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
