### ISSUE TITLE
API status on wrong website

### ISSUE THREAD

**Issue by Astrol99** [GitHawkApp/GitHawk#2706]
GitHub has recently removed the deprecated api status website that githawk uses currently. The new website is: https://www.githubstatus.com

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone SE (iOS 12.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @Astrol99, thanks for letting us know! This has been fixed and will be available in the next update.

See #2546
