### ISSUE TITLE
“API Status Page” returns a 404 or something

### ISSUE THREAD

**Issue by jasikpark** [GitHawkApp/GitHawk#2707]
https://www.githubstatus.com/messages

^^ this doesn’t load

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone SE (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @jasikpark, thanks for letting us know! This has been fixed and will be available in the next update.

See #2546
