### ISSUE TITLE
API status error

### ISSUE THREAD

**Issue by dferch** [GitHawkApp/GitHawk#2708]
I logged into my account, but the app shows only an API error. I‘m using 1.27.2 (latest release on the appstore).

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPad8,7 (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @dferch, thanks for letting us know! This has been fixed and will be available in the next update.

See #2546
