### ISSUE TITLE
API Status: error after giving PAT for user

### ISSUE THREAD

**Issue by HalfALifeLeft** [GitHawkApp/GitHawk#2709]
I gave the PAT User, Repo, and Notification scopes, but it still says API error when I input it to my user.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 7 (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @HalfALifeLeft, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546
