### ISSUE TITLE
Draft PRs show as merge status unknown

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#2711]
We should correct the merge status messaging and also update the icon on repo/notification views (gray icon like Web)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546622353)
Device: iPhone XS (iOS 12.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Want to merge this with #2642 or keep it as a separate issue?

**Comment by Sherlouk** [comment]
Naw lets keep it in one place - just noticed on phone and didn't check! my bad

**Comment by BasThomas** [comment]
All good!
