### ISSUE TITLE
API Status continously shown as „error“

### ISSUE THREAD

**Issue by mbaas2** [GitHawkApp/GitHawk#2712]
![GitHawk Upload by mbaas2](https://i.imgur.com/8f5sZZC.jpg)

Looks like a wrong call...?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.1 (1546622353)
Device: iPhone XS Max (iOS 12.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @mbaas2, thanks for letting us know! This has been fixed and is now available in the latest TestFlight release.

See #2546
