### ISSUE TITLE
API Status always on "error"

### ISSUE THREAD

**Issue by RobertAudi** [GitHawkApp/GitHawk#2717]
The API Status menu in the Settings always says "error" and when you click on it, it opens a 404 page.

![GitHawk Upload by RobertAudi](https://i.imgur.com/4M2O0eP.jpg)

I suspect it might be because the URL: The menu opens https://www.githubstatus.com/messages. Removing the "/messages" part redirects to the correct page: https://www.githubstatus.com

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone X (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @RobertAudi, thanks for letting us know! This has been fixed and is now available in the latest TestFlight release.

See #2546

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RobertAudi** [comment]
Good to hear! Thanks for the quick reply :slightly_smiling_face:
