### ISSUE TITLE
Show issue/pr count when viewing a repo

### ISSUE THREAD

**Issue by tooomm** [GitHawkApp/GitHawk#2718]
**Is your feature request related to a problem? Please describe.**
You have no idea how many issue's and pr's are listed in each category or get an idea how active, maintained, big, old... a repo is.

**Describe the solution you'd like**
Show the count of issue's/pr's in the top bar when viewing a repo:
`   Overview   |   Issues (132)  |   Pull Requests (2)   |   Code   `

**Comment by LamourBt** [comment]
I'll give this one a try.

**Comment by LamourBt** [comment]
Here is the current state of that feature

<img width="369" alt="Screen Shot 2019-06-03 at 10 42 31 AM" src="https://user-images.githubusercontent.com/14245117/58810643-579a0b00-85ec-11e9-9b67-361c6f0ac760.png">

As you can see the title size should be changed here. 

<img width="373" alt="Screen Shot 2019-06-03 at 10 40 24 AM" src="https://user-images.githubusercontent.com/14245117/58810550-2588a900-85ec-11e9-8545-1b4345a304e6.png">

Previously the title's font was set to 18, changing it to 10 made it worked.

we can bump up the font size if we handle value greater than 1000 like 1K+, 1000000 like 1M+. etc...

Any ideas, thoughts?

Thank you.

**Comment by jdisho** [comment]
Thank you @LamourBt, but it seems too small for me 😕 
Is't is possible to increase the width based on the text size?

**Comment by LamourBt** [comment]
@jdisho just solved it 
<img width="372" alt="Screen Shot 2019-06-03 at 4 05 01 PM" src="https://user-images.githubusercontent.com/14245117/58830910-677c1400-8619-11e9-9609-1fd3596986b9.png">

**Comment by jdisho** [comment]
Awesome! Feel free to create a PR 😊 @LamourBt 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jhjohn123** [comment]
Stop can’t help u anymore not a thief tried to do good not helping u guys
do bad things I a good guy that works hard
