### ISSUE TITLE
Can’t pull requests

### ISSUE THREAD

**Issue by TeamSoldierNub2** [GitHawkApp/GitHawk#2719]
![GitHawk Upload by TeamSoldierNub2](https://i.imgur.com/kUnTKfd.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.28.0 (1554002345)
Device: iPhone 6s Plus (iOS 11.3)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Hey @TeamSoldierNub2, I'm not sure what you mean — can you elaborate?

**Comment by TeamSoldierNub2** [comment]
>Hey @TeamSoldierNub2, I'm not sure what you mean — can you elaborate? Creating pull requests from within GitHawk is not supported as of yet.

@BasThomas ah, sorry. I thought it was possible before. Should this be a feature soon? You could pull some code to allow this. Like create issue but instead it pulls a request. Do those two work the same way?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
Closing this in favour of #1796 #2496
