### ISSUE TITLE
Strikethrough in combination with a URL does not work

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#272]
![img_0343](https://user-images.githubusercontent.com/4190298/29970410-bc843920-8f24-11e7-9a65-8944be28606e.PNG)
![img_0344](https://user-images.githubusercontent.com/4190298/29970411-bc88222e-8f24-11e7-95aa-1bacb6631e35.PNG)

Version 1.9.0 (1513)
Device: iPad Pro (iOS 10.3.3)

**Comment by rnystrom** [comment]
Interesting, GH markdown supports both `~` and `~~` for strikethrough. Will work on supporting this.
