### ISSUE TITLE
Difficult to tap small buttons on inbox items

### ISSUE THREAD

**Issue by gingerbeardman** [GitHawkApp/GitHawk#2721]
I tried tapping the tiny mute button a few times and always ended up in the issue. 

I have to be very precise when tapping. 

Please can the hit area be enlarged?

![GitHawk Upload by gingerbeardman](https://i.imgur.com/uqxo9y8.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.28.0 (1554002345)
Device: iPhone 6s (iOS 12.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Yes, let's make these at least 44x44.

**Comment by akarataev** [comment]
I'll look at this if nobody is against.

**Comment by BasThomas** [comment]
Go for it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akarataev** [comment]
Hello @BasThomas,

See #2726 how you will have an opportunity.
