### ISSUE TITLE
Api status check seems off

### ISSUE THREAD

**Issue by YesThatAllen** [GitHawkApp/GitHawk#2722]
The in app notification of GitHub status seems wrong. Maybe GitHub moved its start page since the feature was added to GitHawk?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone XS (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
See #2547

This issue is resolved in the testflight version and should be released in the upcoming update.
