### ISSUE TITLE
Slow push notifications

### ISSUE THREAD

**Issue by dvorakjan** [GitHawkApp/GitHawk#2724]
Hi, thanks for great app, but blocker for frequent usage are very slow notification that are not delivered instantly but in batches once each few days.

Regards, Jan
dvorakj@gmail.com

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 8 (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
Shouldn’t be every few days. GitHawk uses background app refreshes to implement a pseudo-push notification experience via local notifications.
For this reason we are bound by the os in terms of when background refreshes will occur and therefore when your notifications will get triggered. It’s also for this reason that you’ll tend to see batches of notifications. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
