### ISSUE TITLE
API status

### ISSUE THREAD

**Issue by FrancescoCalasso** [GitHawkApp/GitHawk#2725]
My API status is set in “error”, even if all your operational systems are going well, why?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 6 (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
This is a known bug and is fixed in the TestFlight version. Look out for the next release of
GitHawk. :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
