### ISSUE TITLE
API ISSUE

### ISSUE THREAD

**Issue by iFredOS** [GitHawkApp/GitHawk#2728]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 8 (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hey @iFredOS, did you report this by mistake? I’m going to close this for now, let us know if something’s up!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iFredOS** [comment]
It was mistake. I didn't know it posted a comment.
