### ISSUE TITLE
NOT a BUG: I’d love a dark mode

### ISSUE THREAD

**Issue by cppguru** [GitHawkApp/GitHawk#2730]
As in the title.  Me no designer, so I won’t contribute this and attempt to chose colors.  You’ll thank me later. ;)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.28.0 (1554002345)
Device: iPad8,8 (iOS 12.2)
TestFlight: true
</pre>
</details>

**Comment by jdisho** [comment]
#2553 also dupe #198
