### ISSUE TITLE
New install, no nothing

### ISSUE THREAD

**Issue by barbequesauce** [GitHawkApp/GitHawk#2732]
Hi - new install last night. For some reason nothing new is showing up. I have all the switches turned on in settings, and grape/Coderx works fine. Any idea what’s going on?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 8 (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hey, what are you referring to with grape/Coderx? Does this notification itself pop up?

**Comment by barbequesauce** [comment]
Hi - 

I didn't get any notification for that response, no. For more detail - I can see all my watched repos if I tap "Inbox" at the top of the screen, so I know the Github connection is working; I just don't see anything in inbox.

Grape (now known as CoderX, a competing app that doesn't offer notifications) works fine, with new issues/PRs/responses all flowing through nicely, so I know there is traffic that should be seen by GitHawk...

**Comment by BasThomas** [comment]
Oh noes — that's not supposed to happen. Would you be up to join the [TestFlight beta](https://testflight.apple.com/join/QIVXLkkn), then check the request/response using a three-finger tap to launch the debug menu?

**Comment by barbequesauce** [comment]
Sure thing - I've installed on my iPad & iPhone and can bring up the debug menu, but I think I need a bit more explanation what you're looking for with the request/respose? I dont see it in the menu...

**Comment by BasThomas** [comment]
Can you check Menu > Network History, and then try to refresh the inbox?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by barbequesauce** [comment]
[cid:C252AB56-3951-4FBA-AF3E-7C574B79E268][cid:C5DFBDF5-854D-45AB-8DB7-499FB429104A][cid:D8DA9674-687B-4B74-9455-2CBB275A0436][cid:4BE5A74F-2725-4F1B-AB61-871B1ED55321]

--
saucebarbeque@hotmail.com<mailto:saucebarbeque@hotmail.com>

On April 23, 2019 at 5:03:36 PM, Bas Broek (notifications@github.com<mailto:notifications@github.com>) wrote:

Can you check Menu > Network History, and then try to refresh the inbox?

Sent with GitHawk<http://githawk.com>

**Comment by barbequesauce** [comment]
![IMG_6007](https://user-images.githubusercontent.com/25070944/56662530-34d21980-6672-11e9-9c06-fa7eb2b4a821.png)
![IMG_6006](https://user-images.githubusercontent.com/25070944/56662533-36034680-6672-11e9-927c-d2d326dbec6c.png)
![IMG_6009](https://user-images.githubusercontent.com/25070944/56662534-36034680-6672-11e9-9919-bc0b1c0f2225.png)
![IMG_6008](https://user-images.githubusercontent.com/25070944/56662553-45828f80-6672-11e9-9ad9-dfd63e43b388.png)

**Comment by BasThomas** [comment]
Removed the images as they contained some tokens. Will take a look.

**Comment by BasThomas** [comment]
Can you check the `response body` — that should give us a hint of what goes wrong. It's only 2 bytes...

**Comment by barbequesauce** [comment]
this is... interesting:
```
[

]
```

**Comment by BasThomas** [comment]
Hm, yeah, it seems like there are no notifications. Can you see any [on the website](https://github.com/notifications)? If not, can you mark one as unread and try again in the app?

If that doesn't solve it, although I think you already checked, does everything look OK on [here](https://github.com/settings/applications) -> GitHawk?

**Comment by barbequesauce** [comment]
I removed & reinstalled, and it now matches the website... no real idea what was wrong...

Thanks!

**Comment by BasThomas** [comment]
Weird — glad it has been solved!
