### ISSUE TITLE
Crash on acc log out

### ISSUE THREAD

**Issue by tooomm** [GitHawkApp/GitHawk#2743]
When I try to log out of my linked Github account, the app crashes and simply closes. When I then reopen GitHawk I’m still signed in and everything is normal.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPad Mini 2 (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by Huddie** [comment]
Hmm I think this issue occurred in the past not sure if it was fixed or what the cause was

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I remember having seen the issue raised before, too. 

@tooomm, are you logged in with multiple accounts? With credentials or access tokens? Maybe we can reproduce this 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tooomm** [comment]
I tried it on my mobile too (with PAT) and there - instead crashing when I hit sign out,  I see a "Are you sure?" message. I didn't try further as that is different already (and I didn't want to deal with the key again).

So the problem appears only on my ipad mini 2. Same GitHawk version though.
Could it be a problem only with non-PAT accounts only? I was only logged in with one account.
