### ISSUE TITLE
API status ettor

### ISSUE THREAD

**Issue by pete1854** [GitHawkApp/GitHawk#2745]
Hi,
The API status field indicates an error although the Github service and API is up and running.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 8 Plus (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by TheRealBilaal** [comment]
This has been fixed in the TestFlight beta
