### ISSUE TITLE
Update README.md to amend issue label with icon

### ISSUE THREAD

**Issue by ninokierulf** [GitHawkApp/GitHawk#2746]
Update README.md to amend issue labels with icon
so that new contributors are able to find issues to help with.

The fixes suggested are stated below:

A great way to get started is by helping [organize and/or squish bugs](https://github.com/GitHawkApp/GitHawk/issues?q=is%3Aissue+is%3Aopen+label%3A%22🐛+bug%22)
https://github.com/GitHawkApp/GitHawk/issues?q=is%3Aissue+is%3Aopen+label%3A%22🐛+bug%22

 If you're looking to ease your way into the project try out a [good first issue](https://github.com/GitHawkApp/GitHawk/issues?q=is%3Aissue+is%3Aopen+label%3A%22✨+good+first+issue%22)
https://github.com/GitHawkApp/GitHawk/issues?q=is%3Aissue+is%3Aopen+label%3A%22✨+good+first+issue%22

**Comment by BasThomas** [comment]
Sounds good, would you like to make a pull request? 😃

**Comment by tooomm** [comment]
What about?

[![](https://img.shields.io/github/issues/GitHawkApp/GitHawk/🐛%20bug.svg)](https://github.com/GitHawkApp/GitHawk/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%90%9B+bug%22+sort%3Aupdated-desc)
[![](https://img.shields.io/github/issues/GitHawkApp/GitHawk/✨%20good%20first%20issue.svg)](https://github.com/GitHawkApp/GitHawk/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%9C%A8+good+first+issue%22+sort%3Aupdated-desc)

**Comment by guarland** [comment]
zacscsv

**Comment by guarland** [comment]
s fsg bsg

**Comment by guarland** [comment]
Sfvsvgdadacaf

**Comment by guarland** [comment]
sfaggh

**Comment by guarland** [comment]
asvfwvfwvfffsfv

**Comment by guarland** [comment]
wtwbgsgb

**Comment by guarland** [comment]
s s s g

**Comment by nambatee** [comment]
Looks like this could be closed now that https://github.com/GitHawkApp/GitHawk/pull/2760 is in master 🎉

**Comment by BasThomas** [comment]
Thanks again @nambatee!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
