### ISSUE TITLE
Not getting notifications

### ISSUE THREAD

**Issue by sdimartino510** [GitHawkApp/GitHawk#2748]
What the title says.  I have collaborators pushing, making pull requests, and merging, and GitHawk isn't notifying me about any of it.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 6 (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
See [here](https://github.com/GitHawkApp/GitHawk/issues/2724#issuecomment-482912117) for a potential reason for this not being as reliable as we'd love it to be.
