### ISSUE TITLE
API Status shows “error”

### ISSUE THREAD

**Issue by hughbe** [GitHawkApp/GitHawk#2749]
But clicking on it and going to github status website shows all clear

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 8 (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by hughbe** [comment]
![GitHawk Upload by hughbe](https://i.imgur.com/HvB6Awi.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Hi @hughbe, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546
