### ISSUE TITLE
Merged and closed PR is visible when is:open

### ISSUE THREAD

**Issue by Sissing** [GitHawkApp/GitHawk#2750]
List with open PRs is not the same as on github. In the app it’s showing an old PR that’s merged and closed.

Please let me know if you need any more data.

![IMG_2418](https://user-images.githubusercontent.com/8654110/57528581-9e1c8280-732a-11e9-936b-3f5e0d0b68f8.jpg)
<img width="575" alt="Screenshot 2019-05-10 at 13 51 00" src="https://user-images.githubusercontent.com/8654110/57528650-d3c16b80-732a-11e9-8247-60ae06c5e68d.png">

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.28.0 (1554002345)
Device: iPhone X (iOS 12.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Hi Ruben 👋

Can you reproduce this with a public repo, and if so, share the API request's response?

**Comment by Sissing** [comment]
Problem has been solved. The github dev team triggered a re-indexing of the repo what solved the issue. They told me that you can fix it yourself if it happens by adding and removing a random label to the PR. This will close the merged PR if this wasn’t the case.
