### ISSUE TITLE
API status shows error but everything is up

### ISSUE THREAD

**Issue by DanielOberlechner** [GitHawkApp/GitHawk#2752]
It’s all in the title ...
Greets from Italy :)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone X (iOS 12.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @DanielOberlechner, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546
