### ISSUE TITLE
API status error

### ISSUE THREAD

**Issue by cipy** [GitHawkApp/GitHawk#2757]
This field shows as error

But if I tap on it, all GitHub is green

Thanks,

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone XS (iOS 12.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @cipy, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546
