### ISSUE TITLE
Prompt in-app review after merging a pull request?

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#2765]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.28.0 (1559245431)
Device: iPhone X (iOS 12.3)
TestFlight: true
</pre>
</details>

**Comment by jdisho** [comment]
I would assume not everytime after merging a PR. Otherwise, it may be annoying. 🤔
How about every 5th? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Well I'd definitely not do it every time, but I've had good experiences with a one-time review request after a positive experience with an app — I feel merging a pull request is especially relevant for GitHawk and might be a good point to ask for such a review :)

**Comment by jdisho** [comment]
I agree with you 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
