### ISSUE TITLE
Issues behind SSO not shown

### ISSUE THREAD

**Issue by hazcod** [GitHawkApp/GitHawk#2771]
Hi, is it possible new issues that are on org repos with SSO are not displayed? I see them via the web interface.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone XS (iOS 12.3.1)
TestFlight: false
</pre>
</details>

**Comment by jdisho** [comment]
Hi @hazcod

Until approved by the respected organisation, `GitHawk` cannot access the private data.
https://github.com/settings/connections/applications/a8488ca1ed943b610815
