### ISSUE TITLE
Add a nice way to switch between open and closed issues/prs

### ISSUE THREAD

**Issue by nikitavoloboev** [GitHawkApp/GitHawk#2774]
Currently you have to edit the actual search field and swap open with closed. That takes too much time. 

Ideally the app provides a nice toggle between open and closed views of issues and prs. Perhaps by tapping on issues/prs field again would switch between two views. So if in issues, user taps issues tab on top, it would switch to closed issues view. Tap again, go to open.

**Comment by nikitavoloboev** [comment]
I would love to implement this. Any where I can look to dig into solving this?

**Comment by Huddie** [comment]
Hey this is already a PR #2687

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
Dup of #374
