### ISSUE TITLE
Retry button when action fails

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#278]
Version 1.10.0 (1555)
Device: iPhone 7 Plus (iOS 10.3.3) 
Esp. loading an issue is (for me) sometimes fixed just by reloading the view.

**Comment by rnystrom** [comment]
Retry like on the empty state view?

**Comment by BasThomas** [comment]
Yes!

**Comment by BasThomas** [comment]
This is here now
