### ISSUE TITLE
node js binary to text orange pi

### ISSUE THREAD

**Issue by lasuridze** [GitHawkApp/GitHawk#2782]
i have orange pi zero and i whant to read data, pin D0 12 and D1 11
pins get me binary codes and i whant to convert normal number

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Hey @lasuridze, I think you opend this issue in the wrong repository. Make sure to go to the repository you want to create the issue, then use the `...` menu to create a new issue there. :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
