### ISSUE TITLE
Open in GitHawk

### ISSUE THREAD

**Issue by moltar** [GitHawkApp/GitHawk#2783]
Would be great if the app would register as schema handler for github and then allow for “open in githawk” from safari.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huddie** [comment]
🤔 someone may have been working in something like this in the past. Sounds cool. Would you be able to implement it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mwz** [comment]
That would be super useful.

**Comment by jdisho** [comment]
Dup of #2738
