### ISSUE TITLE
Error loading API

### ISSUE THREAD

**Issue by GinesSarmiento** [GitHawkApp/GitHawk#2784]
![GitHawk Upload by GinesSarmiento](https://i.imgur.com/pYQjiFn.jpg)

I’ve restarted the app several times, always the same status: loading > error

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 8 (iOS 12.3.1)
TestFlight: false
</pre>
</details>

**Comment by peterkos** [comment]
Seems like an issue with how the error message is reported -- maybe it could be more detailed.

I've been unable to reproduce in simulator or on device -- Could you try logging the exact error code in `SettingsViewController#viewWillAppear`?

**Comment by BasThomas** [comment]
Hi @GinesSarmiento, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546
