### ISSUE TITLE
[REQUEST] Dark theme

### ISSUE THREAD

**Issue by akuankka128** [GitHawkApp/GitHawk#2788]
It burns my eyes I want dark mode

Ok jokes aside, dark mode is pretty cool. Also make themes for the app, that’d be even cooler. Also make a web-based theme picker so you can upload a theme file to somewhere and use it in this app, that’d be super cool.

**Comment by Sherlouk** [comment]
#2227 #2553 #2691 #2730

I'm right there with you, I'd love to see a dark mode! #DarkModeAllTheThings - If you'd like to join the conversation there's a number of existing threads though 😄 Thanks for your support

**Comment by akuankka128** [comment]
>#2227 #2553 #2691 #2730 #198  ...

@Sherlouk I figured I wasn’t the only one who wants dark theme but custom themes? Surprised how many people want that also. Now to wondering when that kind of update is gonna come out...

**Comment by jhjohn123** [comment]
U don’t even know me I don’t use it

**Comment by jhjohn123** [comment]
To u don’t know what I got ether do u now I been playing along I happy for
her I got tired of the telling me how bad she had it u don’t even know much
about it at all or who I am

**Comment by akuankka128** [comment]
>To u don’t know what I got ether do u now I been playing along I happy for ...

@jhjohn123 what? Not to offend you, but I don’t understand your grammar, can you explain what you meant?
