### ISSUE TITLE
API Status

### ISSUE THREAD

**Issue by SRLJustin** [GitHawkApp/GitHawk#2795]
Api status is showing Error when GitHub it up and running fine

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone X (iOS 11.3.1)
TestFlight: false
</pre>
</details>

**Comment by kooshan75** [comment]
Me too! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LucianoPAlmeida** [comment]
Duplicated #2777 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Hi @SRLJustin, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546
