### ISSUE TITLE
Not getting pushes

### ISSUE THREAD

**Issue by coolbnjmn** [GitHawkApp/GitHawk#2801]
Perhaps I’m misunderstanding how things are supposed to work, but I’m hoping to replace my email inbox with this app for github notifications — except they aren’t arriving here unless I manually pull to refresh. All my permissions seem enabled, any reason I wouldn’t be receiving pushes when stuff happens in my github repos?

Thanks!

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone X (iOS 12.3.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
See [here](https://github.com/GitHawkApp/GitHawk/issues/2724#issuecomment-482912117) for a potential reason for this not being as reliable as we'd love it to be.

**Comment by coolbnjmn** [comment]
I don’t even get notifications every few days, I’ve seen pushes come in once only and I’ve been using the app for ~2 weeks. Looks like I won’t be using it going forward though.   
  
  
  
  
  
Thanks
  
  
  
  
  

  
  
>

**Comment by tanner0101** [comment]
I’ve been using the app for three days now and still haven’t gotten any pushes. I’ve checked to make sure background app refresh is on and that the app is not being quit in multitasking. 
Is there anything else I should be doing? How can I help iOS learn that i want this app to be refreshed often.
