### ISSUE TITLE
General FAQs need to be updates

### ISSUE THREAD

**Issue by paysl-johnl** [GitHawkApp/GitHawk#2804]
Wrong prices for Recand Academy, etc

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 6s (iOS 12.2)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
It seems like you’ve created this issue in the wrong repository, closing :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
