### ISSUE TITLE
Notification is not relied

### ISSUE THREAD

**Issue by irshadpc** [GitHawkApp/GitHawk#2807]
I got the bunch of notification together, I don't why it happens.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.28.0 (1559245431)
Device: iPhone 7 (iOS 12.4)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
The app provides some information on why that is the case. Check the (i) button on Notifications in Settings, or see [here](https://github.com/GitHawkApp/GitHawk/blob/18de137111629ddb6698fb8556fcadecff14b591/Classes/Settings/PushNotificationsDisclaimerViewController.swift#L35).
