### ISSUE TITLE
[Critical Bug] Stuck after uploading a picture

### ISSUE THREAD

**Issue by iDjay** [GitHawkApp/GitHawk#2808]
When you upload a picture with githawk, you‘re currently stucked and can‘t close the window.
iOS 13 Beta 4
Githawk 1.28 beta

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment]
Duplicate of #2785.

**Comment by iDjay** [comment]
Oh yes sorry. Closed because of duplicate 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
