### ISSUE TITLE
API status is always error

### ISSUE THREAD

**Issue by geekkun** [GitHawkApp/GitHawk#2811]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone XR (iOS 13.0)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @geekkun, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546
