### ISSUE TITLE
Not able to sign out

### ISSUE THREAD

**Issue by rpotter12** [GitHawkApp/GitHawk#2813]
I was trying to sign out my account but I clicked on sign out button it closes app automatically.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPad7,5 (iOS 12.4)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @rpotter12, thanks for letting us know! This has been fixed and will be available in the next update. It should be fixed in the TestFlight as well — if it's an option, you can consider using that.

See #2762
