### ISSUE TITLE
API status gives an error

### ISSUE THREAD

**Issue by markgort86** [GitHawkApp/GitHawk#2814]
Cannot see anything from Github

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone XS (iOS 12.3.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @markgort86, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546

**Comment by markgort86** [comment]
Okay, it looks like a false positive then. My account is succesfully added to the app on my iOS device. But my inbox is completely empty. Any reason for that?
