### ISSUE TITLE
API ERROR

### ISSUE THREAD

**Issue by Owen1212055** [GitHawkApp/GitHawk#2815]
No matter what my API status is always Error.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 7 (iOS 13.0)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Hi @Owen1212055, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546
