### ISSUE TITLE
Start App on Bookmarks View

### ISSUE THREAD

**Issue by Schneppi** [GitHawkApp/GitHawk#2817]
Can we please set a specific view in which the App starts? Like the Bookmarks view for those (like me) who use it mainly for Issue Tracking?

**Comment by BasThomas** [comment]
You can do so with the home screen quick actions :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Alexandra1001** [comment]
#`~~~~`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
