### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by ke4roh** [GitHawkApp/GitHawk#2820]
The API status says "error" but I click through and all is well?  First time user, so I'm not sure what to expect.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 7 (iOS 12.4)
TestFlight: false
</pre>
</details>

**Comment by gingerbeardman** [comment]
+1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Hi @ke4roh, thanks for letting us know! This has been fixed and will be available in the next update.

You should be able to use the app regardless of the reported error.

See #2546
