### ISSUE TITLE
1.28 Build expired

### ISSUE THREAD

**Issue by iDjay** [GitHawkApp/GitHawk#2824]
The 90 days are over, the build expired and doesn‘t open anymore.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
+1

I seem to have been removed from the beta and cannot join again. 

I just migrated to the release version. Happy to help whilst beta was running

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
