### ISSUE TITLE
Sign out

### ISSUE THREAD

**Issue by markakinshev** [GitHawkApp/GitHawk#2826]
When I try to sign out of GitHawk (github profile in settings), the app crashes and doesnt sign out of the account.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPad Pro (iOS 12.4.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
This has been fixed in #2762 and will be available in the next update.
