### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by mbirman** [GitHawkApp/GitHawk#2837]
Hey guys! Thanks for the app.

Not sure if it's a bug or a feature but githawk.com is down: https://www.websiteplanet.com/webtools/down-or-not/?DorN=githawk.com

Cheers
![Screen Shot 2019-10-14 at 19 24 16](https://user-images.githubusercontent.com/2179164/66767046-3b6e7a80-eeb8-11e9-9621-aa86b178255b.png)

**Comment by tooomm** [comment]
This is still a persistent issue for me as well.

**Comment by bojanstef** [comment]
The website is still down
<sup><sup><sup>Bump</sup></su></sup>

**Comment by peternewman** [comment]
For now there's always:
http://web.archive.org/web/20190904174342/http://githawk.com/

**Comment by mbirman** [comment]
🚀🚀🚀
