### ISSUE TITLE
embedded busybox

### ISSUE THREAD

**Issue by jonnyfonny** [GitHawkApp/GitHawk#2841]
my iphone and android devises all seem to have embedded busybox and was wondering how this could be installed,how commands are sent to it and how to stop it!! thankyou john.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 7 (iOS 13.2)
TestFlight: false
</pre>
</details>

**Comment by rizwankce** [comment]
@jonnyfonny are you sure this is related GitHawk app? if yes please create issue with detailed description and issue you face.
