### ISSUE TITLE
Add issue/pr filter/sort

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#287]
Should add a way to filter and sort the issues and pull requests after entering into the repository view.

- Filter open/closed/all
- Sort date asc/desc

**Comment by rnystrom** [comment]
Woo! Great minds think alike 😄. Brainstorming how the UI for this might work. I'm thinking a new cell that sits at the top of the PR list that has search/filter/sort controls or something.

**Comment by joerocca** [comment]
Thought this may be a cool UI for this?
Custom presentation like this and possibly use pageboy with authors, issues, projects, milestones, assignees, and sort view controllers. Or may be better to keep it one page.

![img_0020 jpg](https://user-images.githubusercontent.com/10346184/31908106-d658351a-b803-11e7-9fc2-2b9419f01dfd.JPG)

**Comment by rnystrom** [comment]
Here’s my suggestion: 

Working on new filters interactions
https://dribbble.com/shots/2097072-Working-on-new-filters-interactions

- Drop down indicator that there are options
- Each filter has a cell with a label and then bubble options
- Options can be single or multi select
- Once you select a few things and close, totally refresh contents
  - this will help with paging bugs. **Do not** just filter existing models
- Button to quickly clear

Defaults should mirror GitHub too, eg open issues, not all.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
![img_0765](https://user-images.githubusercontent.com/15193942/32996957-95e53454-cd81-11e7-8383-96e9748c637e.PNG)

See linked issue (1008), but I quite like the idea of a custom keyboard for this - fairly easy to add (just a keyboard view with a horizontal collection view!)

Moving discussion into one issue for easier tracking, good candidate for upcoming release me thinks!

**Comment by rnystrom** [comment]
Part of me wonders if we should start super simple:

- Add the default `is:open ` to the bar
- Change to the [v3 API](https://developer.github.com/v3/issues/#list-issues-for-a-repository)
- Map different keywords to v3 params
- Fetch as text changes
- [List PRs API](https://developer.github.com/v3/pulls/#list-pull-requests) doesn't have documented search fields like Issues. Maybe they are undocumented? I've seen a few of those

**Comment by Sherlouk** [comment]
FWIW you can search for things like milestones etc via v4 API, it's just done as part of the search stirng e.g. `label:bug` (see how the web search bar fills when you change search options)

**Comment by jbraem** [comment]
Apologies if this has already been brought up, but I just started with Githawk and would love the ability to limit the inbox to issues & PRs that I'm assigned to and/or mentioned in (with per-repo settings, ideally). 

At my job our team uses issues heavily across several projects, and as-is most of the activity I get in the inbox isn't relevant to me personally.

(Tangentially related to #292)

**Comment by rnystrom** [comment]
@jbraem that's an interesting idea! Different from this issue (this is filtering issues/PRs within a repo). Would love another issue open to track that! Could be a useful setting or something.

**Comment by jbraem** [comment]
Thanks @rnystrom. I added it in #1924 

Keep up the good work!
