### ISSUE TITLE
Bookmarks dont work

### ISSUE THREAD

**Issue by AtakanButik** [GitHawkApp/GitHawk#2871]
When i add a new repository on my bookmarks and the app was started again, i cant reach the repository that i added

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.27.2 (1546696737)
Device: iPhone 8 Plus (iOS 13.1.3)
TestFlight: false
</pre>
</details>

**Comment by booDoo1990** [comment]
```
```

```
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
