### ISSUE TITLE
Did I 👍🏻 this?

### ISSUE THREAD

**Issue by eladeyal-intel** [GitHawkApp/GitHawk#2897]
I would often see an issue with +1 "reaction" (emoji) and I can't tell if it's my reaction or someone else's. So I have to click the icon to see if it goes to 0 or 2...

I propose to show "👍🏻you" or "👍🏻4 and you".

**Comment by noxify** [comment]
If you have liked a comment, it‘s already highlighted with a light blue background.

Not sure if an additional text is needed.

![F8E99E54-6FD7-4575-BD8C-FB8CBE6DAF71](https://user-images.githubusercontent.com/521777/74782138-388af880-52a3-11ea-9d31-c9f4253717af.jpeg)

**Comment by eladeyal-intel** [comment]
Thanks I didn't notice that before.
