### ISSUE TITLE
Darkmode for iOS

### ISSUE THREAD

**Issue by F3000** [GitHawkApp/GitHawk#2903]
Hi , 

would be grade when a Darkmode is possible for iOS

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Aarojas3012a** [comment]
dark power full ios 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Aarojas3012a** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Aarojas3012a** [comment]
```
#~~```
```````
```

```
```````
```~~
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
