### ISSUE TITLE
3d touch shortcuts 

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#342]
Anything cool we could do? Random ideas:

- [x] Switching accounts
- [ ] “new issue” on last viewed repo
- [x] straight to search

**Comment by rnystrom** [comment]
Also maybe jump to the latest 2 notifications (ala Spotify)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Damn it.

**Comment by BasThomas** [comment]
On Spotify: I am a frequent user of 3D Touch and Quick actions, but practically never use Spotify’s

**Comment by rnystrom** [comment]
@BasThomas can you clarify a little? You never use Spotify's shortcuts?

**Comment by BasThomas** [comment]
Yeah, never use their 3D Touch Quick Actions from the homescreen

**Comment by BasThomas** [comment]
Reopening as we don’t have the new issue on last viewed repo yet

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Guess I am going to close this after all; lets pick this back up once needed.
