### ISSUE TITLE
Reply to comment

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#380]
Auto fill comment box with username and text in quotes. Like:

@Sherlouk

> This would be the text in the original comment.

Then this is my reply.

**Comment by rnystrom** [comment]
Probably want to add the “...” menu to comments with options to edit, delete, and reply.

**Comment by Sherlouk** [comment]
Linking to #846

**Comment by jdisho** [comment]
Isn't it the same issue as this https://github.com/GitHawkApp/GitHawk/issues/1551 ? @rnystrom @Sherlouk
