### ISSUE TITLE
Rename issue/PR

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#381]
Put in ... menu. Show alert with text field and original title in field. Save, then update the issue.

**Comment by Sherlouk** [comment]
We've recently introduced edit comments, I wonder if we could reuse the native create issue UI to add this functionality?

Obviously prefilling both the title and message allowing both fields to be edited at once? Saving updates both?

**Comment by rnystrom** [comment]
Ooooooh great idea @Sherlouk

**Comment by BasThomas** [comment]
Would that mean that you update the title by updating the original comment?

**Comment by Sherlouk** [comment]
Yea @BasThomas

**Comment by BasThomas** [comment]
Not sure if that would be intuitive. It's a tricky one - because something like long-pressing the title wouldn't make sense to me either. Maybe add it to the global "more options" for an issue/PR?

**Comment by BasThomas** [comment]
Would love this to be tackled soonish! Been running into this a few times, and having to open the issue in Safari, needing to go to Desktop Mode to edit is isn't... the most ideal.

**Comment by rnystrom** [comment]
@BasThomas take it on!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
But... but... 😜

**Comment by BasThomas** [comment]
Closed in favor of #2054
