### ISSUE TITLE
Sample locked issue

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#385]
testing

**Comment by Sherlouk** [comment]
Interesting that as a collaborator I can reply, but I can't react

**Comment by BasThomas** [comment]
Hi 👋

**Comment by BasThomas** [comment]
Woah, indeed @Sherlouk. Can you, @rnystrom? I feel this might be either expected behavior or a bug on GitHub?

**Comment by Sherlouk** [comment]
I don't see why that would be intended functionality, feels like a weird limitation - if Ryan can react then I'd say 100% bug since it should basically be same

**Comment by BasThomas** [comment]
If he can react - yeah, I definitely feel like it’s a bug. Otherwise it *just might* be very weird behavior

**Comment by rnystrom** [comment]
Huh, nope I can't react on anything either.... 🤔

**Comment by Sherlouk** [comment]
Super bizarre behaviour that, locking down reacting completely...

Going to quickly unlock, react, and then lock and see if we can add extra reactions at that point (I'm just curious at this point!)

**Comment by rnystrom** [comment]
rofl

**Comment by BasThomas** [comment]
This is laughable. Wtf

**Comment by BasThomas** [comment]
I will try to open an issue / file a bug at GH somewhere.
