### ISSUE TITLE
Related Issues

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#403]
When creating an issue I wonder if there's something we could do with background searching to see if an issue has been raised with similar contents?

https://developer.github.com/v3/search/#text-match-metadata

Using the text match metadata API we can search the title, body and comments to see if there's anything going on.

Would obviously have to do some magic to find out the keywords so we're not just seeing "has anyone created an issue with the word bug"

If we do find a duplicate then we should prompt the user and say we found something similar giving them the ability to check it out before submitting, but then still having the option to tap back and submit the original issue!

**Comment by rnystrom** [comment]
Could be interesting to, just before posting, show a list of "similar issues" or something. Then if you see something similar maybe you can then tap on the similar issue and have a comment prefilled w/ what you were going to post as an issue?

**Comment by BasThomas** [comment]
No API yet as this is now in beta on GitHub.com if I understand it correctly.

**Comment by Huddie** [comment]
Has this become a dupe if #2445 ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
