### ISSUE TITLE
URL Schemes & Opener Support

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#418]
Opener is an iOS app which basically lets the user choose where to open links, basically takes advantage of URL schemes.

We should add support for basic URL schemes to deeplink to certain UI within the app. Namely:

freetime://issue/rnystrom/GitHawk/418 would go to this issue!
freetime://repository/rnystrom/GitHawk
freetime://notifications

(Also aware that we may want to rename our URL Scheme??)

Once we add this feature, we should add our app to the [Opener manifest](https://github.com/timonus/OpenerManifest). It's not a perfect solution, but it would be a nice companion app to start opening GitHub stuff in our app rather than Safari!

**Comment by Sherlouk** [comment]
Also worth noting that this will go slightly hand-in-hand with any work on home screen widgets, apple watch stuff, etc hence why I've given it a mid priority and not low!

![](https://media.giphy.com/media/GZc9TILZ8pax2/giphy.gif)

**Comment by BasThomas** [comment]
I want to take a look at this soon :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timonus** [comment]
Would happily integrate into Opener once there’s a URL scheme 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
URL scheme architecture is on my mind for the next release!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Somebody could take a look at this now we have routing in place :)

**Comment by palmin** [comment]
I plan to link to repositories and issues in GitHawk as soon as the App Store version of GitHawk supports this. 

![image](https://user-images.githubusercontent.com/1230554/47716297-9032ca00-dc42-11e8-879e-d2579b42232d.png)

**Comment by palmin** [comment]
@rnystrom: Is there anything I can do to assist?

I'm not sure if the url format representing routes is going to change and I'm also not able to tell if the app currently looks at URL's when launched.

But if you give me some specific tasks I can move this forward.

**Comment by rnystrom** [comment]
@palmin the App Store version should be able to handle deep links now using the route scheme in GitHawkRoutes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by palmin** [comment]
@rnystrom I would expect 
  `freetime://RepoRoute?owner=GitHawkApp&branch=master&repo=GitHawk`
to open the overview screen for GitHawk but it opens the app without going to any particular screen.

Am I misunderstanding how these deep links are supposed to work?

**Comment by timonus** [comment]
Awesome, just tried this out and seems to work! I've got https://github.com/timonus/OpenerManifest/tree/githawk waiting in the wings for when this version of GitHawk makes it to the App Store.

**Comment by palmin** [comment]
![deep-loop](https://user-images.githubusercontent.com/1230554/48317067-b5351e80-e5ec-11e8-9769-7f40bb7783b7.gif)

**Comment by rnystrom** [comment]
You guys 😍😭🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thebearjew** [comment]
@rizwankce you're amazing

**Comment by timonus** [comment]
It's lit fam 🔥

https://github.com/timonus/OpenerManifest/compare/a2b50cd7...c38dc3c7
https://twitter.com/OpenerApp/status/1063257573795651585
