### ISSUE TITLE
Add "Try Beta" to Settings

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#430]
We could upsell how to add yourself as a beta tester in settings. Get more early feedback on stuff. Not sure how to collect emails tho. I've seen the fastlane tools to do this, but it requires a Heroku app. Maybe it just opens Mail.app to email me?

**Comment by BasThomas** [comment]
Yes, that seems 👍

**Comment by Sherlouk** [comment]
If you're using https://github.com/fastlane/boarding it's basically all automated from what I've heard!

**Comment by rnystrom** [comment]
@Sherlouk ya that's the tool I was talking about. It requires a Heroku setup.

**Comment by Sherlouk** [comment]
Just use the free Heroku instance, it'll work more than fine for what we want -- takes five minutes tops!

Love Heroku!

**Comment by Sherlouk** [comment]
Now that we have the `#if TESTFLIGHT` compiler flag we could actually dynamically add this to settings for people who are not on testflight already - would be pretty nice!

**Comment by rnystrom** [comment]
I’m down. If someone wants to setup that free Heroku account and get the fastlane boarding or whatever tool setup That’d be awesome.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
@rnystrom I don't mind setting it up (Heroku is super simple) but I'd require a whole bunch of iTC information!

Genuinely if you go to Heroku and create a free account: https://id.heroku.com/signup/login
then go to this URL: https://www.heroku.com/deploy?template=https://github.com/fastlane/boarding
It'll ask you for various API keys etc that it needs from iTC, after that it'll give you a URL and all be done. Share that and we can work on the next step of adding it to the app!

**Comment by BasThomas** [comment]
We can do this with the new beta invite link :)
