### ISSUE TITLE
Swipe to Unsubscribe

### ISSUE THREAD

**Issue by Sherlouk** [GitHawkApp/GitHawk#434]
We currently have Swipe to Read on notifications, but as per [SwipeCellKit](https://github.com/SwipeCellKit/SwipeCellKit) we can have multiple options

One I'd find quite helpful is Swipe to Unsubscribe which stops you from getting further notifications on the given issue/pr

https://developer.github.com/v3/activity/notifications/#set-a-thread-subscription

**Comment by rnystrom** [comment]
Marking low since IMO unsub from the issue itself would be more useful (use it in multiple places).

**Comment by BasThomas** [comment]
We have this now
