### ISSUE TITLE
Search 3D Touch should pop root and focus search bar

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#558]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (2013)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Should also be clearer: what search? Add a subtitle “search repositories” or something similar 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Does focus search bar now, but does not pop any modals (eg. new issue). Not sure if that's expected? If so, this can be closed.
