### ISSUE TITLE
Create Contributing guide

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#562]
I will probably cause a lot of churn & push back w/out clear expectations. h/t @orta for the tips.

**Comment by BasThomas** [comment]
Do you actually mean a Vision? 🤔

**Comment by BasThomas** [comment]
Anyway, for inspiration:

Moya's [Contributing.md](https://github.com/Moya/Moya/blob/master/Contributing.md)
Moya's [Vision.md](https://github.com/Moya/Moya/blob/master/Vision.md)

**Comment by rnystrom** [comment]
Both 😇

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
In case you forgot; you kinda already made a Vision: https://github.com/rnystrom/GitHawk#how

**Comment by Sherlouk** [comment]
Would be nice to get a bit more further ahead future though to be fair, we're essentially at Northstar 😅 

Also we have my messy contributing guide with a few simple things in

**Comment by BasThomas** [comment]
Is this still relevant now the Readme has expanded?
