### ISSUE TITLE
Add back search to Inbox?

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#686]
Has been removed with the recent changes w/ archives and stuff. Do we want to bring this back at some point?

**Comment by Sherlouk** [comment]
Personally never found search on inbox particularly helpful, granted I'm in a small breed of people who never has more than 20 (until Ryan goes on a storm overnight and I wake up to 50)

I'd honestly find grouping them by repo more helpful, as a way to quickly get to the ones you're more interested about. Dunno maybe just me!

**Comment by rnystrom** [comment]
Thinking about adding it back to the archives view. I never used it on Inbox either.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
Gonna second @Sherlouk re grouping. Some projects take higher priority than others and it’d be awesome to view those first. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ok I’ll start brainstorming some ideas. This was actually my v1. The hardest UX is paging. It gets weird when you load more and it’s in another repo. 

Maybe we can add a dropdown that lets you select a repo and view its notifications:

https://developer.github.com/v3/activity/notifications/#list-your-notifications-in-a-repository

I’m not sure if the “watched repositories” endpoint is enough to show you all the repos you get notifications for?

https://developer.github.com/v3/activity/watching/#list-repositories-being-watched

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Closing this, haven't felt the need. Feel free to open another issue regarding the grouping.

**Comment by ijm8710** [comment]
I have felt the need though of it missing in bookmark search though which only recently fell off. You agree @BasThomas

**Comment by BasThomas** [comment]
Yeah, I can see that being an issue if you have many. Can you open a separate issue to track?

**Comment by ijm8710** [comment]
I will, I have a bunch of things that seem like issue with the bookmarks refactor and id rather just group them together when Ryan comes back. I’ll def do it though
