### ISSUE TITLE
Sync bookmarks accross devices

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#702]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (2112)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by rizwankce** [comment]
With iCloud support? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
CloudKit would work perfectly for this, do we sync accounts/settings at all? If not, we should! 😄

**Comment by BasThomas** [comment]
Let's create another ticket for the settings maybe? :)

**Comment by BasThomas** [comment]
This is done now by #2483!
