### ISSUE TITLE
Dismissing label popover on iPad should not cancel adding the labels

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#745]
Instead I feel it should add the selected labels.
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPad Pro (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
I should check if this is still happening.

**Comment by rnystrom** [comment]
It adds them now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
