### ISSUE TITLE
SwipeCellKit does not respect SafeArea

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/GitHawk#832]
![GitHawk Upload by BasThomas](https://i.imgur.com/CuIDTNZ.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1137)
Device: iPhone10,6 (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
(OK, so the notch is on the right and goes over the "read" thing. Screenshots 🤷‍♂️

**Comment by rizwankce** [comment]
@BasThomas you got iPhone X one first day 😮

**Comment by Sherlouk** [comment]
Wonder who'll be the first person to hide an easter egg under the notch. Only visible if you take a screenshot. Would be a good way to watermark apps to be fair. Slip a githawk logo in there 🤔🤔🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
@Sherlouk pcalc did that already. Type 42 in the app to get it. 😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
removed from inbox at least
