### ISSUE TITLE
GQL only has 6 file changes while PR has 12

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#880]
#879

https://github.com/rnystrom/GitHawk/pull/879/files

![GitHawk Upload by rnystrom](https://i.imgur.com/W23SbRf.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1157)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: false
</pre>
</details>

**Comment by rizwankce** [comment]
*.png and *.psd files are missing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Oh wow, GQL just ignores them? Holy crap. 💩 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Lol ya very confused. Maybe I’m doing something wrong in the request?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
PSD:
```
"sha": "08728f8b5398feebcf1dca18f65e235298840f21",
"filename": "Design/nav-items-66.psd",
"status": "added",
"additions": 0,
"deletions": 0,
"changes": 0,
"blob_url": "...",
"raw_url": "...",
"contents_url": "..."
```

File:
```
"sha": "7946d9aba5839b9586924dd607415c1672139eda",
"filename": "Classes/Repository/RepositoryViewController.swift",
"status": "modified",
"additions": 49,
"deletions": 21,
"changes": 70,
"blob_url": "...",
"raw_url": ".",
"contents_url": "...",
"patch": "..."
```

https://github.com/rnystrom/GitHawk/blob/master/Classes/Models/File.swift#L34

File model expects a "patch" value, and if it doesn't have it will simply fail to add it. As you can see above, binaries will not have a patch and therefore won't be added.

**Comment by rnystrom** [comment]
Well dang. The whole way I did this is wrong 😝 

Some thoughts:

- This is built w/ IGListKit but repo code browsing is a table view
  - Maybe we can unify and pass in a requester object to the file-list VC (b/c the endpoints are so different)
  - Or we leave them separate and just convert code to use IGListKit
- Looks like even if we include binary data, there's no way to open it
  - Probably ok for now, but would also love to unify this so that we can open images

**Comment by Sherlouk** [comment]
Where we currently have the additions/deletions, maybe if that is just replaced in gray to say "BINARY"?

Also if the file is deleted, rather than `-100` should it just say "DELETED" in red?

When you tap on a binary we could just take them to another page which will try to load it. Obviously in 99% of the files it'll just display an error saying "We don't support this file type" but for images it'd  be nice to just render the new version? (Obviously we can get super advanced down the line with diffing, and supporting other formats)

I'd vote to keep inline and use IGLK where we can!

**Comment by BasThomas** [comment]
Well, I am happy to see that it's not actually the API at least 😂

I think we should at least display them in the overview, then just not render them in the detail. Basically just like github.com works. Then if we want to support rendering in the future (as said, images would make sense), we can just add this functionality gradually.

**Comment by rnystrom** [comment]
@Sherlouk great idea when "deleted", much easier to parse visually. Maybe even for binaries we just load a webview and let GitHub try to handle it? Haha.

**Comment by BasThomas** [comment]
I would opt for not showing anything, then creating issues to add support to do so. GitHub doesn't render most of those either, so I think it would only complicate things/confuse users.

**Comment by Sherlouk** [comment]
I actually quite like the idea of just opening the file in Safari if it's binary, feels like an easy temporary solution that gives the user _something_ if they really want it.

**Comment by BasThomas** [comment]
If we have a resource URL, I'd rather add it to the more options (or maybe as a button in the "could not load" message).

Or at least make it / keep it consistent with code browsing in repos.

**Comment by Sherlouk** [comment]
"Raise a feature request" button 🤔😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
