### ISSUE TITLE
Focus keyboard as “new issue” presents

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#895]
Feels a little jerky. The keyboard pops into place as the VC is animating. Could we animate it together somehow? Maybe a custom transition coordinator?

Being picky, but putting this tiny polish on stuff is fun 😇

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1166)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Created a quick hack to do this. Feels pretty smooth. I'll work on cleaning this up and making it a more permanent part of the app. Will also figure out better modal presentation animations for iPad (maybe just not use this on iPad...)

[ViewControllerKeyboardAnimated.zip](https://github.com/rnystrom/GitHawk/files/1454440/ViewControllerKeyboardAnimated.zip)

[Gist of the interesting code](https://gist.github.com/rnystrom/4f66312601952fdcf62a985c1fdd0567)

**Comment by rnystrom** [comment]
So edit comments, new issue, and report bug will benefit from this. Their transitions are a little inconsistent atm.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
Interesting approach, may I ask why you have hard-coded 0.3 in one delegate call while in the other parts you seem to get it from the keyboard notification?

**Comment by rnystrom** [comment]
Good point, I'll use the current value and fallback to 0.3 if we haven't gotten a time from the keyboard yet. I need to put some BPs in there and see the order of operations...

**Comment by rnystrom** [comment]
Test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I tried using the gist above and got some weird behavior. I'll dig into it later. This also breaks on iPad. I'd rather have an unsynchronized keyboard animation over bad iPad support.

**Comment by BasThomas** [comment]
This still an issue?

**Comment by rnystrom** [comment]
Nope!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
