### ISSUE TITLE
Cotton Bureau campaign

### ISSUE THREAD

**Issue by rnystrom** [GitHawkApp/GitHawk#997]
I want to make GitHawk shirts. Had the idea of making a pretty simple shirt and putting it on Cotton Bureau.

I don’t want money, so I’d love to donate all proceeds to [The Hispanic Foundation](http://hispanicfederation.org/) (Lin Manuel Miranda recommended for Puerto Rico relief).

Planning on doing this, leaving this here as a reminder for myself.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.13.0 (1197)
Device: iPhone X (iOS 11.1.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Latest design:

<img width="596" alt="screen shot 2017-11-25 at 5 12 10 pm" src="https://user-images.githubusercontent.com/739696/33235316-d8e8cf64-d203-11e7-8493-91c727a3c9f5.png">

**Comment by BasThomas** [comment]
Looking dope! 😍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Nudge nudge 😉
